
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-26T20:25:02+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2350633baa7a3caf7ba295e884fb4681e5c1207",
 "version": "4.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
