# Generated by Django 3.1.2 on 2020-10-16 20:58

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ayewa', '0005_auto_20201016_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=40, verbose_name='name')),
                ('description', wagtail.core.fields.RichTextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Resource Class',
                'verbose_name_plural': 'Resource Classes',
            },
        ),
    ]
