# -*- coding: utf-8 -*-
"""Calculate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x2LEsDlU9Se2o25Ofcd1evGq5Bj18j5X
"""

def add():
  ask= input("Enter your number separated by a comma: ")
  ask= ask.split(",")
  a= int(ask[0])
  b= int(ask[1])
  result=a+b
  print(result)

add()