
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-20T15:57:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c472fcaa4e50fcd82cffda99ca96ca965d440db8",
 "version": "3.10.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
