
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-25T21:53:52-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "344bc481ed6413df7923ecca4a21c32c0d9524c4",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
