
# This file was generated by 'versioneer.py' (0.14) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '4.12.2'
version_full = 'bdcd60f54a639365723aea831eb5d3c13ebdeca4'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

