
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-13T07:02:08-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "443019ac97f87e135842c1c938aa769138dd405b",
 "version": "v0.3.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
