#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

install_requires = \
['nbclient', 'nbformat', 'jupyter_client', 'ipykernel']

setup(name='princess',
      version='0.1',
      description='Please Run IPython Notebook in the Current Environment with Stdout & Stderr',
      author='European XFEL GmbH',
      author_email='da-support@xfel.eu',
      url='https://github.com/European-XFEL/princess',
      py_modules=['princess'],
      install_requires=install_requires,
      python_requires='>=3.6',
     )
