
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-28T19:40:13+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "150310a5c08cd09a79e0ca9eff989d63538ec141",
 "version": "1.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
