
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-28T17:12:34-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a5db00394b43d9408cd7b116efc1ab1622e16f1",
 "version": "2.1.10.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
