from typing import Any, Optional

class SwarmError(Exception):
    message: Any = ...
    status: Any = ...
    def __init__(self, message: Optional[Any] = ..., status: Optional[Any] = ...) -> None: ...

class SwarmNotFoundError(SwarmError): ...
