from .endpoints.reviews import Reviews as Reviews
from .exceptions import SwarmError as SwarmError, SwarmNotFoundError as SwarmNotFoundError
from typing import Any

class Swarm:
    reviews: Any = ...
    def __init__(self, url: str, user: str, password: str) -> None: ...
    def get_version(self) -> dict: ...
