# Generated by Django 2.1.15 on 2020-04-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opening_hours_management", "0002_auto_20200402_1527"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openinghours",
            name="always_open",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If checked, prevails on week day values",
                verbose_name="Open 24/7",
            ),
        ),
        migrations.AlterField(
            model_name="specificperiodhours",
            name="closed",
            field=models.BooleanField(
                default=False,
                help_text="If checked, prevails on time range values",
                verbose_name="Closed",
            ),
        ),
        migrations.AlterField(
            model_name="weekdayhours",
            name="closed",
            field=models.BooleanField(
                default=False,
                help_text="If checked, prevails on time range values",
                verbose_name="Closed",
            ),
        ),
    ]
