# Generated by Django 2.1.15 on 2020-04-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opening_hours_management", "0004_specificperiodhours_closure_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specificperiodhours",
            name="from_date",
            field=models.DateField(db_index=True, verbose_name="From"),
        ),
        migrations.AlterField(
            model_name="specificperiodhours",
            name="to_date",
            field=models.DateField(db_index=True, verbose_name="To"),
        ),
    ]
