
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-26T18:45:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a931e1ebb3f7da2f7f0f44165a7366c1bae8d5a",
 "version": "0.3.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
