from momotor.rpc.const import DEFAULT_PORT, DEFAULT_SSL_PORT

DEFAULT_TOKEN_STORE_CLASS = 'momotor.django.token_store.model.ModelTokenStore'
DEFAULT_CACHE_KEY = 'momotor-broker-auth-token-{[API_KEY]}'
DEFAULT_INFO_MAX_AGE = 30
DEFAULT_BROKER_HOST = 'localhost'
DEFAULT_BROKER_PORT = DEFAULT_PORT
DEFAULT_BROKER_SSL_PORT = DEFAULT_SSL_PORT

__all__ = [
    'DEFAULT_TOKEN_STORE_CLASS', 'DEFAULT_CACHE_KEY', 'DEFAULT_INFO_MAX_AGE',
    'DEFAULT_BROKER_HOST', 'DEFAULT_BROKER_PORT', 'DEFAULT_BROKER_SSL_PORT',
]
