
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-20T14:50:44-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0caf81309c4ebf8ae2e5ed7384640a17791456f",
 "version": "2.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
