# Generated by Django 3.1.1 on 2020-09-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayewa', '0003_remove_resource_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='solution',
        ),
    ]
