# Generated by Django 3.1.2 on 2020-10-19 14:51

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('ayewa', '0012_actionapproach_actionapproachindexpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('first_name', models.CharField(blank=True, default='', max_length=40, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, default='', max_length=40, verbose_name='last_name')),
                ('role', modelcluster.fields.ParentalManyToManyField(blank=True, to='ayewa.Role')),
            ],
            options={
                'verbose_name': 'Person',
            },
            bases=('wagtailcore.page',),
        ),
    ]
