# Generated by Django 3.1.2 on 2020-10-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayewa', '0018_auto_20201023_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='nav_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Navigation Description'),
        ),
    ]
