
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-22T15:49:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "15fd5e0106605d554e19315f88e67c3dcd5b6a82",
 "version": "0.6.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
