# coding: utf-8

"""
    MailMojo API

    v1 of the MailMojo API  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: hjelp@mailmojo.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import mailmojo_sdk
from mailmojo_sdk.models.campaign_detail import CampaignDetail  # noqa: E501
from mailmojo_sdk.rest import ApiException


class TestCampaignDetail(unittest.TestCase):
    """CampaignDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCampaignDetail(self):
        """Test CampaignDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = mailmojo_sdk.models.campaign_detail.CampaignDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
