
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-21T12:33:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b8d44250ee0e8bfecf9981beb5f31bc6e167394c",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
