
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-27T14:36:28-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "24400d459409282850cffbfaa339e8f8edb58708",
 "version": "2.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
