# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './widgets/ui/alarms.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(999, 786)
        self.gridLayout_2 = QtWidgets.QGridLayout(Frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.set = QtWidgets.QPushButton(Frame)
        self.set.setObjectName("set")
        self.gridLayout_2.addWidget(self.set, 0, 0, 1, 1)
        self.get = QtWidgets.QPushButton(Frame)
        self.get.setObjectName("get")
        self.gridLayout_2.addWidget(self.get, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(Frame)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.fpga_enabled = QtWidgets.QCheckBox(self.groupBox)
        self.fpga_enabled.setObjectName("fpga_enabled")
        self.gridLayout_4.addWidget(self.fpga_enabled, 0, 0, 1, 1)
        self.fpga_triggered = QtWidgets.QCheckBox(self.groupBox)
        self.fpga_triggered.setObjectName("fpga_triggered")
        self.gridLayout_4.addWidget(self.fpga_triggered, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 2, 0, 1, 1)
        self.fpga_threshold = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.fpga_threshold.setDecimals(1)
        self.fpga_threshold.setObjectName("fpga_threshold")
        self.gridLayout_4.addWidget(self.fpga_threshold, 2, 1, 1, 1)
        self.fpga_plot = QtWidgets.QStackedWidget(self.groupBox)
        self.fpga_plot.setObjectName("fpga_plot")
        self.gridLayout_4.addWidget(self.fpga_plot, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.s0_enabled = QtWidgets.QCheckBox(self.groupBox_2)
        self.s0_enabled.setObjectName("s0_enabled")
        self.gridLayout_5.addWidget(self.s0_enabled, 0, 0, 1, 1)
        self.s0_triggered = QtWidgets.QCheckBox(self.groupBox_2)
        self.s0_triggered.setObjectName("s0_triggered")
        self.gridLayout_5.addWidget(self.s0_triggered, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 2, 0, 1, 1)
        self.s0_threshold = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.s0_threshold.setDecimals(1)
        self.s0_threshold.setObjectName("s0_threshold")
        self.gridLayout_5.addWidget(self.s0_threshold, 2, 1, 1, 1)
        self.s0_plot = QtWidgets.QStackedWidget(self.groupBox_2)
        self.s0_plot.setObjectName("s0_plot")
        self.gridLayout_5.addWidget(self.s0_plot, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.s1_enabled = QtWidgets.QCheckBox(self.groupBox_3)
        self.s1_enabled.setObjectName("s1_enabled")
        self.gridLayout_3.addWidget(self.s1_enabled, 0, 0, 1, 1)
        self.s1_triggered = QtWidgets.QCheckBox(self.groupBox_3)
        self.s1_triggered.setObjectName("s1_triggered")
        self.gridLayout_3.addWidget(self.s1_triggered, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.s1_threshold = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.s1_threshold.setDecimals(1)
        self.s1_threshold.setObjectName("s1_threshold")
        self.gridLayout_3.addWidget(self.s1_threshold, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 1, 1, 1)
        self.s1_plot = QtWidgets.QStackedWidget(self.groupBox_3)
        self.s1_plot.setObjectName("s1_plot")
        self.gridLayout_3.addWidget(self.s1_plot, 4, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_3, 1, 2, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.s2_enabled = QtWidgets.QCheckBox(self.groupBox_4)
        self.s2_enabled.setObjectName("s2_enabled")
        self.gridLayout_6.addWidget(self.s2_enabled, 0, 0, 1, 1)
        self.s2_triggered = QtWidgets.QCheckBox(self.groupBox_4)
        self.s2_triggered.setObjectName("s2_triggered")
        self.gridLayout_6.addWidget(self.s2_triggered, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setObjectName("label_12")
        self.gridLayout_6.addWidget(self.label_12, 2, 0, 1, 1)
        self.s2_threshold = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.s2_threshold.setDecimals(1)
        self.s2_threshold.setObjectName("s2_threshold")
        self.gridLayout_6.addWidget(self.s2_threshold, 2, 1, 1, 1)
        self.s2_plot = QtWidgets.QStackedWidget(self.groupBox_4)
        self.s2_plot.setObjectName("s2_plot")
        self.gridLayout_6.addWidget(self.s2_plot, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.s3_threshold = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.s3_threshold.setDecimals(1)
        self.s3_threshold.setObjectName("s3_threshold")
        self.gridLayout_7.addWidget(self.s3_threshold, 2, 1, 1, 1)
        self.s3_enabled = QtWidgets.QCheckBox(self.groupBox_5)
        self.s3_enabled.setObjectName("s3_enabled")
        self.gridLayout_7.addWidget(self.s3_enabled, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 2, 0, 1, 1)
        self.s3_triggered = QtWidgets.QCheckBox(self.groupBox_5)
        self.s3_triggered.setObjectName("s3_triggered")
        self.gridLayout_7.addWidget(self.s3_triggered, 1, 0, 1, 1)
        self.s3_plot = QtWidgets.QStackedWidget(self.groupBox_5)
        self.s3_plot.setObjectName("s3_plot")
        self.gridLayout_7.addWidget(self.s3_plot, 3, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox_5, 2, 1, 1, 1)
        self.groupBox_21 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_21.setStyleSheet("QGroupBox {\n"
"    border: 3px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.groupBox_21.setObjectName("groupBox_21")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_3 = QtWidgets.QLabel(self.groupBox_21)
        self.label_3.setObjectName("label_3")
        self.gridLayout_8.addWidget(self.label_3, 1, 0, 1, 1)
        self.alarm_hold = QtWidgets.QSpinBox(self.groupBox_21)
        self.alarm_hold.setMaximum(99999)
        self.alarm_hold.setSingleStep(100)
        self.alarm_hold.setObjectName("alarm_hold")
        self.gridLayout_8.addWidget(self.alarm_hold, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_21)
        self.label_2.setObjectName("label_2")
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 1)
        self.interlock_delay = QtWidgets.QSpinBox(self.groupBox_21)
        self.interlock_delay.setMaximum(99999)
        self.interlock_delay.setSingleStep(100)
        self.interlock_delay.setObjectName("interlock_delay")
        self.gridLayout_8.addWidget(self.interlock_delay, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_21, 2, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 2)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Alarms"))
        self.set.setText(_translate("Frame", "SET"))
        self.get.setText(_translate("Frame", "GET"))
        self.groupBox.setTitle(_translate("Frame", "FPGA"))
        self.fpga_enabled.setText(_translate("Frame", "Enabled"))
        self.fpga_triggered.setText(_translate("Frame", "Triggered (read only)"))
        self.label.setText(_translate("Frame", "Threshold (ºC):"))
        self.groupBox_2.setTitle(_translate("Frame", "Hotpeltier (s0)"))
        self.s0_enabled.setText(_translate("Frame", "Enabled"))
        self.s0_triggered.setText(_translate("Frame", "Triggered (read only)"))
        self.label_6.setText(_translate("Frame", "Threshold (ºC):"))
        self.groupBox_3.setTitle(_translate("Frame", "Coldpeltier (s1)"))
        self.s1_enabled.setText(_translate("Frame", "Enabled"))
        self.s1_triggered.setText(_translate("Frame", "Triggered (read only)"))
        self.label_9.setText(_translate("Frame", "Threshold (ºC):"))
        self.label_8.setText(_translate("Frame", "Real threshold (ºC):"))
        self.label_10.setText(_translate("Frame", "TextLabel"))
        self.groupBox_4.setTitle(_translate("Frame", "Ambient (s2)"))
        self.s2_enabled.setText(_translate("Frame", "Enabled"))
        self.s2_triggered.setText(_translate("Frame", "Triggered (read only)"))
        self.label_12.setText(_translate("Frame", "Threshold (ºC):"))
        self.groupBox_5.setTitle(_translate("Frame", "Filter (s3)"))
        self.s3_enabled.setText(_translate("Frame", "Enabled"))
        self.label_15.setText(_translate("Frame", "Threshold (ºC):"))
        self.s3_triggered.setText(_translate("Frame", "Triggered (read only)"))
        self.groupBox_21.setTitle(_translate("Frame", "General settings"))
        self.label_3.setText(_translate("Frame", "Interlock delay (ms):"))
        self.label_2.setText(_translate("Frame", "Minimum alarm hold (ms):"))

