# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './widgets/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(886, 973)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tools_panel = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tools_panel.sizePolicy().hasHeightForWidth())
        self.tools_panel.setSizePolicy(sizePolicy)
        self.tools_panel.setObjectName("tools_panel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tools_panel)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.config_panel = QtWidgets.QWidget(self.tools_panel)
        self.config_panel.setObjectName("config_panel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.config_panel)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.connection = QtWidgets.QGroupBox(self.config_panel)
        self.connection.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.connection.setObjectName("connection")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.connection)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.spin_port = QtWidgets.QSpinBox(self.connection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_port.sizePolicy().hasHeightForWidth())
        self.spin_port.setSizePolicy(sizePolicy)
        self.spin_port.setMaximum(65535)
        self.spin_port.setProperty("value", 32000)
        self.spin_port.setObjectName("spin_port")
        self.gridLayout_3.addWidget(self.spin_port, 1, 1, 1, 1)
        self.text_ip = QtWidgets.QLineEdit(self.connection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_ip.sizePolicy().hasHeightForWidth())
        self.text_ip.setSizePolicy(sizePolicy)
        self.text_ip.setMaxLength(15)
        self.text_ip.setObjectName("text_ip")
        self.gridLayout_3.addWidget(self.text_ip, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.connection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.connection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.connection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.spin_aport = QtWidgets.QSpinBox(self.connection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_aport.sizePolicy().hasHeightForWidth())
        self.spin_aport.setSizePolicy(sizePolicy)
        self.spin_aport.setMaximum(65535)
        self.spin_aport.setProperty("value", 32001)
        self.spin_aport.setObjectName("spin_aport")
        self.gridLayout_3.addWidget(self.spin_aport, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.connection)
        self.geometry = QtWidgets.QGroupBox(self.config_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geometry.sizePolicy().hasHeightForWidth())
        self.geometry.setSizePolicy(sizePolicy)
        self.geometry.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}\n"
"\n"
"")
        self.geometry.setObjectName("geometry")
        self.formLayout = QtWidgets.QFormLayout(self.geometry)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.geometry)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.storage_rows = QtWidgets.QSpinBox(self.geometry)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.storage_rows.sizePolicy().hasHeightForWidth())
        self.storage_rows.setSizePolicy(sizePolicy)
        self.storage_rows.setMaximum(10000)
        self.storage_rows.setSingleStep(10)
        self.storage_rows.setProperty("value", 512)
        self.storage_rows.setObjectName("storage_rows")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.storage_rows)
        self.label_7 = QtWidgets.QLabel(self.geometry)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.active_rows = QtWidgets.QSpinBox(self.geometry)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.active_rows.sizePolicy().hasHeightForWidth())
        self.active_rows.setSizePolicy(sizePolicy)
        self.active_rows.setMaximum(10000)
        self.active_rows.setSingleStep(10)
        self.active_rows.setProperty("value", 544)
        self.active_rows.setObjectName("active_rows")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.active_rows)
        self.label_8 = QtWidgets.QLabel(self.geometry)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.prescan = QtWidgets.QSpinBox(self.geometry)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prescan.sizePolicy().hasHeightForWidth())
        self.prescan.setSizePolicy(sizePolicy)
        self.prescan.setMaximum(1000)
        self.prescan.setSingleStep(1)
        self.prescan.setProperty("value", 5)
        self.prescan.setObjectName("prescan")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.prescan)
        self.label_9 = QtWidgets.QLabel(self.geometry)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.overscan = QtWidgets.QSpinBox(self.geometry)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overscan.sizePolicy().hasHeightForWidth())
        self.overscan.setSizePolicy(sizePolicy)
        self.overscan.setMaximum(1000)
        self.overscan.setSingleStep(1)
        self.overscan.setProperty("value", 32)
        self.overscan.setObjectName("overscan")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.overscan)
        self.columnsLabel = QtWidgets.QLabel(self.geometry)
        self.columnsLabel.setObjectName("columnsLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.columnsLabel)
        self.columns = QtWidgets.QSpinBox(self.geometry)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.columns.sizePolicy().hasHeightForWidth())
        self.columns.setSizePolicy(sizePolicy)
        self.columns.setMaximum(10000)
        self.columns.setSingleStep(10)
        self.columns.setProperty("value", 1000)
        self.columns.setObjectName("columns")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.columns)
        self.verticalLayout.addWidget(self.geometry)
        self.expose = QtWidgets.QGroupBox(self.config_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expose.sizePolicy().hasHeightForWidth())
        self.expose.setSizePolicy(sizePolicy)
        self.expose.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.expose.setObjectName("expose")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.expose)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.check_clear = QtWidgets.QCheckBox(self.expose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_clear.sizePolicy().hasHeightForWidth())
        self.check_clear.setSizePolicy(sizePolicy)
        self.check_clear.setChecked(True)
        self.check_clear.setObjectName("check_clear")
        self.gridLayout_4.addWidget(self.check_clear, 3, 1, 1, 2)
        self.expose_pattern = QtWidgets.QComboBox(self.expose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expose_pattern.sizePolicy().hasHeightForWidth())
        self.expose_pattern.setSizePolicy(sizePolicy)
        self.expose_pattern.setEditable(True)
        self.expose_pattern.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.expose_pattern.setObjectName("expose_pattern")
        self.expose_pattern.addItem("")
        self.expose_pattern.addItem("")
        self.expose_pattern.addItem("")
        self.expose_pattern.addItem("")
        self.expose_pattern.addItem("")
        self.expose_pattern.addItem("")
        self.expose_pattern.addItem("")
        self.gridLayout_4.addWidget(self.expose_pattern, 8, 1, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.expose)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 1, 1, 1)
        self.check_fake = QtWidgets.QCheckBox(self.expose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_fake.sizePolicy().hasHeightForWidth())
        self.check_fake.setSizePolicy(sizePolicy)
        self.check_fake.setChecked(True)
        self.check_fake.setObjectName("check_fake")
        self.gridLayout_4.addWidget(self.check_fake, 7, 1, 1, 1)
        self.spin_exposeTime = QtWidgets.QSpinBox(self.expose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_exposeTime.sizePolicy().hasHeightForWidth())
        self.spin_exposeTime.setSizePolicy(sizePolicy)
        self.spin_exposeTime.setMaximum(1000)
        self.spin_exposeTime.setProperty("value", 1)
        self.spin_exposeTime.setObjectName("spin_exposeTime")
        self.gridLayout_4.addWidget(self.spin_exposeTime, 0, 2, 1, 1)
        self.combo_test = QtWidgets.QComboBox(self.expose)
        self.combo_test.setObjectName("combo_test")
        self.combo_test.addItem("")
        self.combo_test.addItem("")
        self.combo_test.addItem("")
        self.combo_test.addItem("")
        self.combo_test.addItem("")
        self.combo_test.addItem("")
        self.combo_test.addItem("")
        self.combo_test.addItem("")
        self.combo_test.addItem("")
        self.combo_test.addItem("")
        self.gridLayout_4.addWidget(self.combo_test, 9, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.expose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 1, 1, 1)
        self.combo_storage = QtWidgets.QComboBox(self.expose)
        self.combo_storage.setObjectName("combo_storage")
        self.combo_storage.addItem("")
        self.combo_storage.addItem("")
        self.gridLayout_4.addWidget(self.combo_storage, 1, 2, 1, 1)
        self.expose_mode = QtWidgets.QComboBox(self.expose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expose_mode.sizePolicy().hasHeightForWidth())
        self.expose_mode.setSizePolicy(sizePolicy)
        self.expose_mode.setEditable(True)
        self.expose_mode.setCurrentText("0: Pixel Average")
        self.expose_mode.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.expose_mode.setObjectName("expose_mode")
        self.expose_mode.addItem("")
        self.expose_mode.addItem("")
        self.expose_mode.addItem("")
        self.expose_mode.addItem("")
        self.expose_mode.addItem("")
        self.gridLayout_4.addWidget(self.expose_mode, 6, 1, 1, 2)
        self.verticalLayout.addWidget(self.expose)
        self.post_expose = QtWidgets.QGroupBox(self.config_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.post_expose.sizePolicy().hasHeightForWidth())
        self.post_expose.setSizePolicy(sizePolicy)
        self.post_expose.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.post_expose.setObjectName("post_expose")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.post_expose)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.images_dir = QtWidgets.QLineEdit(self.post_expose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.images_dir.sizePolicy().hasHeightForWidth())
        self.images_dir.setSizePolicy(sizePolicy)
        self.images_dir.setFrame(True)
        self.images_dir.setCursorPosition(4)
        self.images_dir.setObjectName("images_dir")
        self.gridLayout_5.addWidget(self.images_dir, 1, 1, 1, 1)
        self.check_save = QtWidgets.QCheckBox(self.post_expose)
        self.check_save.setEnabled(True)
        self.check_save.setChecked(False)
        self.check_save.setObjectName("check_save")
        self.gridLayout_5.addWidget(self.check_save, 1, 0, 1, 1)
        self.label_gfa_id = QtWidgets.QLabel(self.post_expose)
        self.label_gfa_id.setEnabled(True)
        self.label_gfa_id.setObjectName("label_gfa_id")
        self.gridLayout_5.addWidget(self.label_gfa_id, 2, 0, 1, 1)
        self.label_ccd_serial = QtWidgets.QLabel(self.post_expose)
        self.label_ccd_serial.setObjectName("label_ccd_serial")
        self.gridLayout_5.addWidget(self.label_ccd_serial, 3, 0, 1, 1)
        self.ccd_serial = QtWidgets.QLineEdit(self.post_expose)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ccd_serial.sizePolicy().hasHeightForWidth())
        self.ccd_serial.setSizePolicy(sizePolicy)
        self.ccd_serial.setText("")
        self.ccd_serial.setObjectName("ccd_serial")
        self.gridLayout_5.addWidget(self.ccd_serial, 3, 1, 1, 1)
        self.gfa_id = QtWidgets.QComboBox(self.post_expose)
        self.gfa_id.setObjectName("gfa_id")
        self.gfa_id.addItem("")
        self.gfa_id.addItem("")
        self.gfa_id.addItem("")
        self.gfa_id.addItem("")
        self.gfa_id.addItem("")
        self.gfa_id.addItem("")
        self.gfa_id.addItem("")
        self.gfa_id.addItem("")
        self.gfa_id.addItem("")
        self.gfa_id.addItem("")
        self.gfa_id.addItem("")
        self.gfa_id.addItem("")
        self.gfa_id.addItem("")
        self.gridLayout_5.addWidget(self.gfa_id, 2, 1, 1, 1)
        self.verticalLayout.addWidget(self.post_expose)
        self.verticalLayout_2.addWidget(self.config_panel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.status_info = QtWidgets.QGroupBox(self.tools_panel)
        self.status_info.setStyleSheet("QGroupBox {\n"
"    border: 1px solid blue;\n"
"    border-radius: 0px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}")
        self.status_info.setObjectName("status_info")
        self.gridLayout = QtWidgets.QGridLayout(self.status_info)
        self.gridLayout.setObjectName("gridLayout")
        self.calibrated_check = QCheckBoxReadOnly(self.status_info)
        self.calibrated_check.setEnabled(True)
        self.calibrated_check.setCheckable(True)
        self.calibrated_check.setObjectName("calibrated_check")
        self.gridLayout.addWidget(self.calibrated_check, 0, 1, 1, 1)
        self.configured_check = QCheckBoxReadOnly(self.status_info)
        self.configured_check.setEnabled(True)
        self.configured_check.setCheckable(True)
        self.configured_check.setObjectName("configured_check")
        self.gridLayout.addWidget(self.configured_check, 0, 0, 1, 1)
        self.discharge_check = QCheckBoxReadOnly(self.status_info)
        self.discharge_check.setObjectName("discharge_check")
        self.gridLayout.addWidget(self.discharge_check, 1, 1, 1, 1)
        self.offsets_check = QCheckBoxReadOnly(self.status_info)
        self.offsets_check.setEnabled(True)
        self.offsets_check.setCheckable(True)
        self.offsets_check.setObjectName("offsets_check")
        self.gridLayout.addWidget(self.offsets_check, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.status_info)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.control_buttons = QtWidgets.QWidget(self.tools_panel)
        self.control_buttons.setObjectName("control_buttons")
        self.control_buttons_layout = QtWidgets.QGridLayout(self.control_buttons)
        self.control_buttons_layout.setObjectName("control_buttons_layout")
        self.button_connect = QtWidgets.QPushButton(self.control_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_connect.sizePolicy().hasHeightForWidth())
        self.button_connect.setSizePolicy(sizePolicy)
        self.button_connect.setObjectName("button_connect")
        self.control_buttons_layout.addWidget(self.button_connect, 4, 0, 1, 1)
        self.button_configure = QtWidgets.QPushButton(self.control_buttons)
        self.button_configure.setObjectName("button_configure")
        self.control_buttons_layout.addWidget(self.button_configure, 3, 0, 1, 1)
        self.label_info = QtWidgets.QLabel(self.control_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_info.sizePolicy().hasHeightForWidth())
        self.label_info.setSizePolicy(sizePolicy)
        self.label_info.setStyleSheet("color: red;")
        self.label_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info.setObjectName("label_info")
        self.control_buttons_layout.addWidget(self.label_info, 5, 0, 1, 1)
        self.button_do_all = QtWidgets.QPushButton(self.control_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_do_all.sizePolicy().hasHeightForWidth())
        self.button_do_all.setSizePolicy(sizePolicy)
        self.button_do_all.setObjectName("button_do_all")
        self.control_buttons_layout.addWidget(self.button_do_all, 2, 1, 3, 1)
        self.button_stop_life_test = QtWidgets.QPushButton(self.control_buttons)
        self.button_stop_life_test.setEnabled(False)
        self.button_stop_life_test.setObjectName("button_stop_life_test")
        self.control_buttons_layout.addWidget(self.button_stop_life_test, 0, 0, 1, 2)
        self.button_read = QtWidgets.QPushButton(self.control_buttons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_read.sizePolicy().hasHeightForWidth())
        self.button_read.setSizePolicy(sizePolicy)
        self.button_read.setObjectName("button_read")
        self.control_buttons_layout.addWidget(self.button_read, 1, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.control_buttons)
        self.horizontalLayout_3.addWidget(self.tools_panel)
        self.tab = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setTabsClosable(True)
        self.tab.setObjectName("tab")
        self.horizontalLayout_3.addWidget(self.tab)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setSizeGripEnabled(False)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 886, 19))
        self.menuBar.setObjectName("menuBar")
        self.menuWindows = QtWidgets.QMenu(self.menuBar)
        self.menuWindows.setObjectName("menuWindows")
        self.menuACtion = QtWidgets.QMenu(self.menuBar)
        self.menuACtion.setObjectName("menuACtion")
        MainWindow.setMenuBar(self.menuBar)
        self.actionClear_buffers = QtWidgets.QAction(MainWindow)
        self.actionClear_buffers.setObjectName("actionClear_buffers")
        self.actionClearStack = QtWidgets.QAction(MainWindow)
        self.actionClearStack.setObjectName("actionClearStack")
        self.actionDiagnostics = QtWidgets.QAction(MainWindow)
        self.actionDiagnostics.setObjectName("actionDiagnostics")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionCalibrate_ADC = QtWidgets.QAction(MainWindow)
        self.actionCalibrate_ADC.setObjectName("actionCalibrate_ADC")
        self.actionSPI_write = QtWidgets.QAction(MainWindow)
        self.actionSPI_write.setObjectName("actionSPI_write")
        self.actionEnable_offset = QtWidgets.QAction(MainWindow)
        self.actionEnable_offset.setObjectName("actionEnable_offset")
        self.actionDisable_offset = QtWidgets.QAction(MainWindow)
        self.actionDisable_offset.setObjectName("actionDisable_offset")
        self.actionLogs = QtWidgets.QAction(MainWindow)
        self.actionLogs.setObjectName("actionLogs")
        self.actionDischarge_config = QtWidgets.QAction(MainWindow)
        self.actionDischarge_config.setObjectName("actionDischarge_config")
        self.actionTelemetry = QtWidgets.QAction(MainWindow)
        self.actionTelemetry.setObjectName("actionTelemetry")
        self.actionEnable_drivers = QtWidgets.QAction(MainWindow)
        self.actionEnable_drivers.setObjectName("actionEnable_drivers")
        self.actionDisable_drivers = QtWidgets.QAction(MainWindow)
        self.actionDisable_drivers.setObjectName("actionDisable_drivers")
        self.actionStart_console = QtWidgets.QAction(MainWindow)
        self.actionStart_console.setObjectName("actionStart_console")
        self.actionADC = QtWidgets.QAction(MainWindow)
        self.actionADC.setObjectName("actionADC")
        self.actionOffset = QtWidgets.QAction(MainWindow)
        self.actionOffset.setObjectName("actionOffset")
        self.actionPID = QtWidgets.QAction(MainWindow)
        self.actionPID.setObjectName("actionPID")
        self.actionAlarms = QtWidgets.QAction(MainWindow)
        self.actionAlarms.setObjectName("actionAlarms")
        self.actionPWM = QtWidgets.QAction(MainWindow)
        self.actionPWM.setObjectName("actionPWM")
        self.actionDAC = QtWidgets.QAction(MainWindow)
        self.actionDAC.setObjectName("actionDAC")
        self.actionCCD = QtWidgets.QAction(MainWindow)
        self.actionCCD.setObjectName("actionCCD")
        self.actionPower_down = QtWidgets.QAction(MainWindow)
        self.actionPower_down.setObjectName("actionPower_down")
        self.actionPower_up = QtWidgets.QAction(MainWindow)
        self.actionPower_up.setObjectName("actionPower_up")
        self.actionVersions = QtWidgets.QAction(MainWindow)
        self.actionVersions.setObjectName("actionVersions")
        self.actionClear_error_state = QtWidgets.QAction(MainWindow)
        self.actionClear_error_state.setObjectName("actionClear_error_state")
        self.actionSensors_monitor = QtWidgets.QAction(MainWindow)
        self.actionSensors_monitor.setObjectName("actionSensors_monitor")
        self.menuWindows.addAction(self.actionDiagnostics)
        self.menuWindows.addAction(self.actionSettings)
        self.menuWindows.addAction(self.actionADC)
        self.menuWindows.addAction(self.actionDAC)
        self.menuWindows.addAction(self.actionOffset)
        self.menuWindows.addAction(self.actionLogs)
        self.menuWindows.addAction(self.actionDischarge_config)
        self.menuWindows.addAction(self.actionTelemetry)
        self.menuWindows.addAction(self.actionPID)
        self.menuWindows.addAction(self.actionAlarms)
        self.menuWindows.addAction(self.actionCCD)
        self.menuWindows.addAction(self.actionPWM)
        self.menuWindows.addAction(self.actionVersions)
        self.menuWindows.addAction(self.actionSensors_monitor)
        self.menuWindows.addSeparator()
        self.menuWindows.addAction(self.actionStart_console)
        self.menuACtion.addAction(self.actionClear_buffers)
        self.menuACtion.addAction(self.actionClearStack)
        self.menuACtion.addAction(self.actionCalibrate_ADC)
        self.menuACtion.addAction(self.actionEnable_drivers)
        self.menuACtion.addAction(self.actionDisable_drivers)
        self.menuACtion.addAction(self.actionPower_down)
        self.menuACtion.addAction(self.actionPower_up)
        self.menuACtion.addAction(self.actionClear_error_state)
        self.menuBar.addAction(self.menuWindows.menuAction())
        self.menuBar.addAction(self.menuACtion.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.text_ip, self.spin_port)
        MainWindow.setTabOrder(self.spin_port, self.spin_aport)
        MainWindow.setTabOrder(self.spin_aport, self.storage_rows)
        MainWindow.setTabOrder(self.storage_rows, self.active_rows)
        MainWindow.setTabOrder(self.active_rows, self.prescan)
        MainWindow.setTabOrder(self.prescan, self.overscan)
        MainWindow.setTabOrder(self.overscan, self.columns)
        MainWindow.setTabOrder(self.columns, self.spin_exposeTime)
        MainWindow.setTabOrder(self.spin_exposeTime, self.check_clear)
        MainWindow.setTabOrder(self.check_clear, self.expose_mode)
        MainWindow.setTabOrder(self.expose_mode, self.check_fake)
        MainWindow.setTabOrder(self.check_fake, self.expose_pattern)
        MainWindow.setTabOrder(self.expose_pattern, self.check_save)
        MainWindow.setTabOrder(self.check_save, self.images_dir)
        MainWindow.setTabOrder(self.images_dir, self.button_connect)
        MainWindow.setTabOrder(self.button_connect, self.tab)
        MainWindow.setTabOrder(self.tab, self.button_read)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GFA GUI"))
        self.connection.setTitle(_translate("MainWindow", "Connection"))
        self.text_ip.setInputMask(_translate("MainWindow", "000.000.000.000"))
        self.label_6.setText(_translate("MainWindow", "Port number"))
        self.label_4.setText(_translate("MainWindow", "Server IP"))
        self.label_5.setText(_translate("MainWindow", "Async port"))
        self.geometry.setTitle(_translate("MainWindow", "Geometry"))
        self.label_2.setText(_translate("MainWindow", "Storage rows:"))
        self.label_7.setText(_translate("MainWindow", "Active Rows:"))
        self.label_8.setText(_translate("MainWindow", "Prescan:"))
        self.label_9.setText(_translate("MainWindow", "Overscan:"))
        self.columnsLabel.setText(_translate("MainWindow", "Columns"))
        self.expose.setTitle(_translate("MainWindow", "Expose configuration"))
        self.check_clear.setText(_translate("MainWindow", "Clear Before Read"))
        self.expose_pattern.setCurrentText(_translate("MainWindow", "0: All 0\'s"))
        self.expose_pattern.setItemText(0, _translate("MainWindow", "0: All 0\'s"))
        self.expose_pattern.setItemText(1, _translate("MainWindow", "1: All 1\'s"))
        self.expose_pattern.setItemText(2, _translate("MainWindow", "2: Fixed value (E: 0, F: 1000, G: 2000, H: 3000)"))
        self.expose_pattern.setItemText(3, _translate("MainWindow", "3: Row + Col + Offset (E: 0, F: 1000, G: 2000, H: 3000)"))
        self.expose_pattern.setItemText(4, _translate("MainWindow", "4: Pixel value = Row"))
        self.expose_pattern.setItemText(5, _translate("MainWindow", "5: Pixel Value = Column"))
        self.expose_pattern.setItemText(6, _translate("MainWindow", "6: Pixel Value = Row x Col"))
        self.label_3.setText(_translate("MainWindow", "Storage:"))
        self.check_fake.setText(_translate("MainWindow", "Fake Data"))
        self.combo_test.setItemText(0, _translate("MainWindow", "No tests"))
        self.combo_test.setItemText(1, _translate("MainWindow", "BIAS"))
        self.combo_test.setItemText(2, _translate("MainWindow", "DC"))
        self.combo_test.setItemText(3, _translate("MainWindow", "FCTE"))
        self.combo_test.setItemText(4, _translate("MainWindow", "PTC"))
        self.combo_test.setItemText(5, _translate("MainWindow", "FLATS"))
        self.combo_test.setItemText(6, _translate("MainWindow", "DARKS"))
        self.combo_test.setItemText(7, _translate("MainWindow", "LIFE"))
        self.combo_test.setItemText(8, _translate("MainWindow", "PSF"))
        self.combo_test.setItemText(9, _translate("MainWindow", "PSF_LOOPING"))
        self.label.setText(_translate("MainWindow", "Expose Time (s):"))
        self.combo_storage.setItemText(0, _translate("MainWindow", "Read"))
        self.combo_storage.setItemText(1, _translate("MainWindow", "Dump"))
        self.expose_mode.setItemText(0, _translate("MainWindow", "0: Pixel Average"))
        self.expose_mode.setItemText(1, _translate("MainWindow", "1: Split average"))
        self.expose_mode.setItemText(2, _translate("MainWindow", "2: Light map"))
        self.expose_mode.setItemText(3, _translate("MainWindow", "3: Bias map"))
        self.expose_mode.setItemText(4, _translate("MainWindow", "4: Raw data"))
        self.post_expose.setTitle(_translate("MainWindow", "Post-Expose configuration"))
        self.images_dir.setText(_translate("MainWindow", "/tmp"))
        self.check_save.setText(_translate("MainWindow", "Save images"))
        self.label_gfa_id.setText(_translate("MainWindow", "GFA ID:"))
        self.label_ccd_serial.setText(_translate("MainWindow", "CCD SERIAL:"))
        self.gfa_id.setItemText(0, _translate("MainWindow", "None"))
        self.gfa_id.setItemText(1, _translate("MainWindow", "1"))
        self.gfa_id.setItemText(2, _translate("MainWindow", "2"))
        self.gfa_id.setItemText(3, _translate("MainWindow", "3"))
        self.gfa_id.setItemText(4, _translate("MainWindow", "4"))
        self.gfa_id.setItemText(5, _translate("MainWindow", "5"))
        self.gfa_id.setItemText(6, _translate("MainWindow", "6"))
        self.gfa_id.setItemText(7, _translate("MainWindow", "7"))
        self.gfa_id.setItemText(8, _translate("MainWindow", "9"))
        self.gfa_id.setItemText(9, _translate("MainWindow", "8"))
        self.gfa_id.setItemText(10, _translate("MainWindow", "10"))
        self.gfa_id.setItemText(11, _translate("MainWindow", "12"))
        self.gfa_id.setItemText(12, _translate("MainWindow", "13"))
        self.status_info.setTitle(_translate("MainWindow", "Status"))
        self.calibrated_check.setText(_translate("MainWindow", "Calibrated"))
        self.configured_check.setText(_translate("MainWindow", "Configured"))
        self.discharge_check.setText(_translate("MainWindow", "Discharge"))
        self.offsets_check.setText(_translate("MainWindow", "Offsets"))
        self.button_connect.setText(_translate("MainWindow", "CONNECT"))
        self.button_configure.setText(_translate("MainWindow", "CONFIGURE"))
        self.label_info.setText(_translate("MainWindow", "DISCONNECTED"))
        self.button_do_all.setText(_translate("MainWindow", "CONNECT\n"
"+\n"
"CONFIGURE"))
        self.button_stop_life_test.setText(_translate("MainWindow", "STOP LIFE TEST"))
        self.button_read.setText(_translate("MainWindow", "READ"))
        self.menuWindows.setTitle(_translate("MainWindow", "Widget"))
        self.menuACtion.setTitle(_translate("MainWindow", "Action"))
        self.actionClear_buffers.setText(_translate("MainWindow", "Clear buffers"))
        self.actionClearStack.setText(_translate("MainWindow", "Clear stack"))
        self.actionDiagnostics.setText(_translate("MainWindow", "Diagnostics"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionCalibrate_ADC.setText(_translate("MainWindow", "Calibrate ADC"))
        self.actionSPI_write.setText(_translate("MainWindow", "SPI"))
        self.actionEnable_offset.setText(_translate("MainWindow", "Enable offset"))
        self.actionDisable_offset.setText(_translate("MainWindow", "Disable offset"))
        self.actionLogs.setText(_translate("MainWindow", "Logs"))
        self.actionDischarge_config.setText(_translate("MainWindow", "Discharge config"))
        self.actionTelemetry.setText(_translate("MainWindow", "Telemetry"))
        self.actionEnable_drivers.setText(_translate("MainWindow", "Enable drivers"))
        self.actionDisable_drivers.setText(_translate("MainWindow", "Disable drivers"))
        self.actionStart_console.setText(_translate("MainWindow", "Start console"))
        self.actionADC.setText(_translate("MainWindow", "ADC"))
        self.actionOffset.setText(_translate("MainWindow", "Offset"))
        self.actionPID.setText(_translate("MainWindow", "PID "))
        self.actionAlarms.setText(_translate("MainWindow", "Alarms"))
        self.actionPWM.setText(_translate("MainWindow", "PWM"))
        self.actionDAC.setText(_translate("MainWindow", "DAC"))
        self.actionCCD.setText(_translate("MainWindow", "CCD"))
        self.actionPower_down.setText(_translate("MainWindow", "Power down"))
        self.actionPower_up.setText(_translate("MainWindow", "Power up"))
        self.actionVersions.setText(_translate("MainWindow", "Versions"))
        self.actionClear_error_state.setText(_translate("MainWindow", "Clear error state"))
        self.actionSensors_monitor.setText(_translate("MainWindow", "Sensors monitor"))

from gfagui.widgets.qcheckboxreadonly import QCheckBoxReadOnly
