# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './widgets/ui/pid.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1078, 599)
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_4 = QtWidgets.QWidget(Frame)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.clear = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear.sizePolicy().hasHeightForWidth())
        self.clear.setSizePolicy(sizePolicy)
        self.clear.setObjectName("clear")
        self.verticalLayout.addWidget(self.clear)
        self.pid_plot = QtWidgets.QStackedWidget(self.widget_4)
        self.pid_plot.setObjectName("pid_plot")
        self.verticalLayout.addWidget(self.pid_plot)
        self.output_plot = QtWidgets.QStackedWidget(self.widget_4)
        self.output_plot.setObjectName("output_plot")
        self.verticalLayout.addWidget(self.output_plot)
        self.gridLayout.addWidget(self.widget_4, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Frame)
        self.groupBox.setMaximumSize(QtCore.QSize(187, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.percentage = QtWidgets.QLabel(self.groupBox)
        self.percentage.setObjectName("percentage")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.percentage)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.error = QtWidgets.QLabel(self.groupBox)
        self.error.setObjectName("error")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.error)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.p_val = QtWidgets.QLabel(self.groupBox)
        self.p_val.setObjectName("p_val")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.p_val)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.i_val = QtWidgets.QLabel(self.groupBox)
        self.i_val.setObjectName("i_val")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.i_val)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.d_val = QtWidgets.QLabel(self.groupBox)
        self.d_val.setObjectName("d_val")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.d_val)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.last_temp = QtWidgets.QLabel(self.groupBox)
        self.last_temp.setObjectName("last_temp")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.last_temp)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(Frame)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 11, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 12, 0, 1, 1)
        self.max_duty = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.max_duty.setMaximum(100.0)
        self.max_duty.setObjectName("max_duty")
        self.gridLayout_2.addWidget(self.max_duty, 11, 1, 1, 1)
        self.set = QtWidgets.QPushButton(self.widget_2)
        self.set.setObjectName("set")
        self.gridLayout_2.addWidget(self.set, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_23 = QtWidgets.QLabel(self.widget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 2, 4, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.widget_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 0, 3, 3, 1)
        self.label_22 = QtWidgets.QLabel(self.widget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 0, 0, 1, 1)
        self.duty_cycle = QtWidgets.QLabel(self.widget_3)
        self.duty_cycle.setObjectName("duty_cycle")
        self.gridLayout_3.addWidget(self.duty_cycle, 2, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.high_clocks = QtWidgets.QLabel(self.widget_3)
        self.high_clocks.setObjectName("high_clocks")
        self.gridLayout_3.addWidget(self.high_clocks, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.low_clocks = QtWidgets.QLabel(self.widget_3)
        self.low_clocks.setObjectName("low_clocks")
        self.gridLayout_3.addWidget(self.low_clocks, 2, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 1, 4, 1, 1)
        self.frequency = QtWidgets.QLabel(self.widget_3)
        self.frequency.setObjectName("frequency")
        self.gridLayout_3.addWidget(self.frequency, 1, 5, 1, 1)
        self.gridLayout_2.addWidget(self.widget_3, 17, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 18, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 4, 0, 1, 1)
        self.kp = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.kp.setMinimum(-10000.0)
        self.kp.setMaximum(10000.0)
        self.kp.setObjectName("kp")
        self.gridLayout_2.addWidget(self.kp, 6, 1, 1, 1)
        self.ki = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.ki.setMinimum(-10000.0)
        self.ki.setMaximum(10000.0)
        self.ki.setObjectName("ki")
        self.gridLayout_2.addWidget(self.ki, 7, 1, 1, 1)
        self.kd = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.kd.setMinimum(-10000.0)
        self.kd.setMaximum(10000.0)
        self.kd.setObjectName("kd")
        self.gridLayout_2.addWidget(self.kd, 8, 1, 1, 1)
        self.auto_update_period = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.auto_update_period.setObjectName("auto_update_period")
        self.gridLayout_2.addWidget(self.auto_update_period, 4, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 8, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.max_integral_error = QtWidgets.QSpinBox(self.widget)
        self.max_integral_error.setMinimum(-99999999)
        self.max_integral_error.setMaximum(99999999)
        self.max_integral_error.setObjectName("max_integral_error")
        self.horizontalLayout.addWidget(self.max_integral_error)
        self.min_integral_error = QtWidgets.QSpinBox(self.widget)
        self.min_integral_error.setMinimum(-99999999)
        self.min_integral_error.setMaximum(99999999)
        self.min_integral_error.setObjectName("min_integral_error")
        self.horizontalLayout.addWidget(self.min_integral_error)
        self.gridLayout_2.addWidget(self.widget, 12, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.widget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 16, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 5, 0, 1, 1)
        self.get = QtWidgets.QPushButton(self.widget_2)
        self.get.setObjectName("get")
        self.gridLayout_2.addWidget(self.get, 0, 1, 1, 1)
        self.enabled_label = QtWidgets.QLabel(self.widget_2)
        self.enabled_label.setObjectName("enabled_label")
        self.gridLayout_2.addWidget(self.enabled_label, 3, 1, 1, 1)
        self.setpoint = QtWidgets.QSpinBox(self.widget_2)
        self.setpoint.setObjectName("setpoint")
        self.gridLayout_2.addWidget(self.setpoint, 5, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 3, 0, 1, 1)
        self.is_fixed_duty = QtWidgets.QLabel(self.groupBox_2)
        self.is_fixed_duty.setObjectName("is_fixed_duty")
        self.gridLayout_4.addWidget(self.is_fixed_duty, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.fixed_duty_value = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.fixed_duty_value.setMaximum(100.0)
        self.fixed_duty_value.setObjectName("fixed_duty_value")
        self.gridLayout_4.addWidget(self.fixed_duty_value, 3, 1, 1, 1)
        self.enable_fixed_duty = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enable_fixed_duty.sizePolicy().hasHeightForWidth())
        self.enable_fixed_duty.setSizePolicy(sizePolicy)
        self.enable_fixed_duty.setObjectName("enable_fixed_duty")
        self.gridLayout_4.addWidget(self.enable_fixed_duty, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 13, 0, 1, 1)
        self.enable_pid = QtWidgets.QPushButton(self.widget_2)
        self.enable_pid.setObjectName("enable_pid")
        self.gridLayout_2.addWidget(self.enable_pid, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.widget_2, 0, 0, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "PID"))
        self.clear.setText(_translate("Frame", "CLEAR DATA"))
        self.groupBox.setTitle(_translate("Frame", "PID status (of last update)"))
        self.label_10.setText(_translate("Frame", "Output (%):"))
        self.percentage.setText(_translate("Frame", "0"))
        self.label_15.setText(_translate("Frame", "Error:"))
        self.error.setText(_translate("Frame", "0"))
        self.label_12.setText(_translate("Frame", "P value:"))
        self.p_val.setText(_translate("Frame", "0"))
        self.label_18.setText(_translate("Frame", "I value:"))
        self.i_val.setText(_translate("Frame", "0"))
        self.label_20.setText(_translate("Frame", "D value:"))
        self.d_val.setText(_translate("Frame", "0"))
        self.label_17.setText(_translate("Frame", "Temperature:"))
        self.last_temp.setText(_translate("Frame", "0"))
        self.label_8.setText(_translate("Frame", "Maximum duty cycle (%):"))
        self.label_5.setText(_translate("Frame", "Kp:"))
        self.label_9.setText(_translate("Frame", "Integral error limits (max, min):"))
        self.set.setText(_translate("Frame", "SET"))
        self.label_23.setText(_translate("Frame", "Duty cycle:"))
        self.label_22.setText(_translate("Frame", "PWM:"))
        self.duty_cycle.setText(_translate("Frame", "999999"))
        self.label_11.setText(_translate("Frame", "High clocks:"))
        self.high_clocks.setText(_translate("Frame", "99999"))
        self.label_16.setText(_translate("Frame", "Low Clocks:"))
        self.low_clocks.setText(_translate("Frame", "99999"))
        self.label_21.setText(_translate("Frame", "Frequency:"))
        self.frequency.setText(_translate("Frame", "999999"))
        self.label_14.setText(_translate("Frame", "Update period (s) 0=disabled:"))
        self.label_2.setText(_translate("Frame", "Enabled:"))
        self.label_4.setText(_translate("Frame", "Kd:"))
        self.label_3.setText(_translate("Frame", "Ki:"))
        self.label.setText(_translate("Frame", "Setpoint:"))
        self.get.setText(_translate("Frame", "GET"))
        self.enabled_label.setText(_translate("Frame", "FALSE"))
        self.groupBox_2.setTitle(_translate("Frame", "Fixed duty cycle"))
        self.label_7.setText(_translate("Frame", "Value (%):"))
        self.is_fixed_duty.setText(_translate("Frame", "FALSE"))
        self.label_6.setText(_translate("Frame", "Enabled:"))
        self.enable_fixed_duty.setText(_translate("Frame", "ENABLE"))
        self.enable_pid.setText(_translate("Frame", "ENABLE PID"))

