
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-28T12:41:25-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4825cacd743b49577f02a01fac6ce1d44db4f9a",
 "version": "0.8.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
