
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-22T18:41:27-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f2307c94a610f95c47639b8176b0a206ce0937cf",
 "version": "0.0.22"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
