#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

entry_points = \
{'console_scripts': ['b8 = b8:main']}

setup(name='b8',
      version='0.0.12',
      description='b8, Bominade Ultralight NeoVim-based IDE',
      author='Ali Afshar',
      author_email='aafshar@gmail.com',
      url='https://gitlab.com/afshar-oss/b8',
      py_modules=['b8'],
      entry_points=entry_points,
      python_requires='>=3.5',
     )
