# Generated by Django 3.1.2 on 2020-10-20 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ayewa', '0015_resource_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherIndexPage',
            fields=[
                ('indexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ayewa.indexpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('ayewa.indexpage',),
        ),
        migrations.CreateModel(
            name='ScienceIndexPage',
            fields=[
                ('indexpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ayewa.indexpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('ayewa.indexpage',),
        ),
    ]
