# Generated by Django 3.1.1 on 2020-09-29 17:51

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('ayewa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('summary', models.TextField(blank=True, default='', null=True, verbose_name='Summary')),
                ('description', wagtail.core.fields.RichTextField(blank=True, verbose_name='Description')),
                ('email_address', models.CharField(blank=True, default='', max_length=64, verbose_name='Email Address')),
                ('primary_phone', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Primary Phone')),
                ('address_1', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='Address 1')),
                ('address_2', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, default='', max_length=20, verbose_name='State')),
                ('postal_code', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Postal (Zip) Code')),
                ('country', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Country')),
                ('website', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Website')),
                ('solution', models.ManyToManyField(blank=True, related_name='solution', to='ayewa.Solution')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
