# Generated by Django 3.1.2 on 2020-10-17 19:06

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ayewa', '0009_auto_20201017_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='solution',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='ayewa.Solution'),
        ),
    ]
