
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-27T14:42:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "c96f8cafbc7904f5ca079957b820f7a3ad33eb00",
 "version": "0.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
