# coding: utf-8

"""
    MailMojo API

    v1 of the MailMojo API  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: hjelp@mailmojo.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TrackPageView(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'page_id': 'int',
        'user_agent': 'str',
        'visitor_id': 'str'
    }

    attribute_map = {
        'id': 'id',
        'page_id': 'page_id',
        'user_agent': 'user_agent',
        'visitor_id': 'visitor_id'
    }

    def __init__(self, id=None, page_id=None, user_agent=None, visitor_id=None):  # noqa: E501
        """TrackPageView - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._page_id = None
        self._user_agent = None
        self._visitor_id = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.page_id = page_id
        if user_agent is not None:
            self.user_agent = user_agent
        self.visitor_id = visitor_id

    @property
    def id(self):
        """Gets the id of this TrackPageView.  # noqa: E501


        :return: The id of this TrackPageView.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TrackPageView.


        :param id: The id of this TrackPageView.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def page_id(self):
        """Gets the page_id of this TrackPageView.  # noqa: E501


        :return: The page_id of this TrackPageView.  # noqa: E501
        :rtype: int
        """
        return self._page_id

    @page_id.setter
    def page_id(self, page_id):
        """Sets the page_id of this TrackPageView.


        :param page_id: The page_id of this TrackPageView.  # noqa: E501
        :type: int
        """
        if page_id is None:
            raise ValueError("Invalid value for `page_id`, must not be `None`")  # noqa: E501

        self._page_id = page_id

    @property
    def user_agent(self):
        """Gets the user_agent of this TrackPageView.  # noqa: E501


        :return: The user_agent of this TrackPageView.  # noqa: E501
        :rtype: str
        """
        return self._user_agent

    @user_agent.setter
    def user_agent(self, user_agent):
        """Sets the user_agent of this TrackPageView.


        :param user_agent: The user_agent of this TrackPageView.  # noqa: E501
        :type: str
        """

        self._user_agent = user_agent

    @property
    def visitor_id(self):
        """Gets the visitor_id of this TrackPageView.  # noqa: E501


        :return: The visitor_id of this TrackPageView.  # noqa: E501
        :rtype: str
        """
        return self._visitor_id

    @visitor_id.setter
    def visitor_id(self, visitor_id):
        """Sets the visitor_id of this TrackPageView.


        :param visitor_id: The visitor_id of this TrackPageView.  # noqa: E501
        :type: str
        """
        if visitor_id is None:
            raise ValueError("Invalid value for `visitor_id`, must not be `None`")  # noqa: E501

        self._visitor_id = visitor_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TrackPageView, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrackPageView):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
