# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_dilithium', [dirname(__file__)])
        except ImportError:
            import _dilithium
            return _dilithium
        if fp is not None:
            try:
                _mod = imp.load_module('_dilithium', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _dilithium = swig_import_helper()
    del swig_import_helper
else:
    import _dilithium
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def cdata(ptr, nelements=1):
    return _dilithium.cdata(ptr, nelements)
cdata = _dilithium.cdata

def memmove(data, indata):
    return _dilithium.memmove(data, indata)
memmove = _dilithium.memmove
class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _dilithium.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _dilithium.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _dilithium.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _dilithium.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _dilithium.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _dilithium.SwigPyIterator_equal(self, x)

    def copy(self):
        return _dilithium.SwigPyIterator_copy(self)

    def next(self):
        return _dilithium.SwigPyIterator_next(self)

    def __next__(self):
        return _dilithium.SwigPyIterator___next__(self)

    def previous(self):
        return _dilithium.SwigPyIterator_previous(self)

    def advance(self, n):
        return _dilithium.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _dilithium.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _dilithium.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _dilithium.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _dilithium.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _dilithium.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _dilithium.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _dilithium.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)


_dilithium.SHARED_PTR_DISOWN_swigconstant(_dilithium)
SHARED_PTR_DISOWN = _dilithium.SHARED_PTR_DISOWN
class ucharCArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ucharCArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ucharCArray, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _dilithium.new_ucharCArray(nelements)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _dilithium.delete_ucharCArray
    __del__ = lambda self: None

    def __getitem__(self, index):
        return _dilithium.ucharCArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _dilithium.ucharCArray___setitem__(self, index, value)

    def cast(self):
        return _dilithium.ucharCArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _dilithium.ucharCArray_frompointer
    if _newclass:
        frompointer = staticmethod(_dilithium.ucharCArray_frompointer)
ucharCArray_swigregister = _dilithium.ucharCArray_swigregister
ucharCArray_swigregister(ucharCArray)

def ucharCArray_frompointer(t):
    return _dilithium.ucharCArray_frompointer(t)
ucharCArray_frompointer = _dilithium.ucharCArray_frompointer

class uintCArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, uintCArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, uintCArray, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _dilithium.new_uintCArray(nelements)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _dilithium.delete_uintCArray
    __del__ = lambda self: None

    def __getitem__(self, index):
        return _dilithium.uintCArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _dilithium.uintCArray___setitem__(self, index, value)

    def cast(self):
        return _dilithium.uintCArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _dilithium.uintCArray_frompointer
    if _newclass:
        frompointer = staticmethod(_dilithium.uintCArray_frompointer)
uintCArray_swigregister = _dilithium.uintCArray_swigregister
uintCArray_swigregister(uintCArray)

def uintCArray_frompointer(t):
    return _dilithium.uintCArray_frompointer(t)
uintCArray_frompointer = _dilithium.uintCArray_frompointer

class uint32CArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, uint32CArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, uint32CArray, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _dilithium.new_uint32CArray(nelements)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _dilithium.delete_uint32CArray
    __del__ = lambda self: None

    def __getitem__(self, index):
        return _dilithium.uint32CArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _dilithium.uint32CArray___setitem__(self, index, value)

    def cast(self):
        return _dilithium.uint32CArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _dilithium.uint32CArray_frompointer
    if _newclass:
        frompointer = staticmethod(_dilithium.uint32CArray_frompointer)
uint32CArray_swigregister = _dilithium.uint32CArray_swigregister
uint32CArray_swigregister(uint32CArray)

def uint32CArray_frompointer(t):
    return _dilithium.uint32CArray_frompointer(t)
uint32CArray_frompointer = _dilithium.uint32CArray_frompointer

class intVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, intVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, intVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _dilithium.intVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _dilithium.intVector___nonzero__(self)

    def __bool__(self):
        return _dilithium.intVector___bool__(self)

    def __len__(self):
        return _dilithium.intVector___len__(self)

    def __getslice__(self, i, j):
        return _dilithium.intVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _dilithium.intVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _dilithium.intVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _dilithium.intVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _dilithium.intVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _dilithium.intVector___setitem__(self, *args)

    def pop(self):
        return _dilithium.intVector_pop(self)

    def append(self, x):
        return _dilithium.intVector_append(self, x)

    def empty(self):
        return _dilithium.intVector_empty(self)

    def size(self):
        return _dilithium.intVector_size(self)

    def swap(self, v):
        return _dilithium.intVector_swap(self, v)

    def begin(self):
        return _dilithium.intVector_begin(self)

    def end(self):
        return _dilithium.intVector_end(self)

    def rbegin(self):
        return _dilithium.intVector_rbegin(self)

    def rend(self):
        return _dilithium.intVector_rend(self)

    def clear(self):
        return _dilithium.intVector_clear(self)

    def get_allocator(self):
        return _dilithium.intVector_get_allocator(self)

    def pop_back(self):
        return _dilithium.intVector_pop_back(self)

    def erase(self, *args):
        return _dilithium.intVector_erase(self, *args)

    def __init__(self, *args):
        this = _dilithium.new_intVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _dilithium.intVector_push_back(self, x)

    def front(self):
        return _dilithium.intVector_front(self)

    def back(self):
        return _dilithium.intVector_back(self)

    def assign(self, n, x):
        return _dilithium.intVector_assign(self, n, x)

    def resize(self, *args):
        return _dilithium.intVector_resize(self, *args)

    def insert(self, *args):
        return _dilithium.intVector_insert(self, *args)

    def reserve(self, n):
        return _dilithium.intVector_reserve(self, n)

    def capacity(self):
        return _dilithium.intVector_capacity(self)
    __swig_destroy__ = _dilithium.delete_intVector
    __del__ = lambda self: None
intVector_swigregister = _dilithium.intVector_swigregister
intVector_swigregister(intVector)

class uintVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, uintVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, uintVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _dilithium.uintVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _dilithium.uintVector___nonzero__(self)

    def __bool__(self):
        return _dilithium.uintVector___bool__(self)

    def __len__(self):
        return _dilithium.uintVector___len__(self)

    def __getslice__(self, i, j):
        return _dilithium.uintVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _dilithium.uintVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _dilithium.uintVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _dilithium.uintVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _dilithium.uintVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _dilithium.uintVector___setitem__(self, *args)

    def pop(self):
        return _dilithium.uintVector_pop(self)

    def append(self, x):
        return _dilithium.uintVector_append(self, x)

    def empty(self):
        return _dilithium.uintVector_empty(self)

    def size(self):
        return _dilithium.uintVector_size(self)

    def swap(self, v):
        return _dilithium.uintVector_swap(self, v)

    def begin(self):
        return _dilithium.uintVector_begin(self)

    def end(self):
        return _dilithium.uintVector_end(self)

    def rbegin(self):
        return _dilithium.uintVector_rbegin(self)

    def rend(self):
        return _dilithium.uintVector_rend(self)

    def clear(self):
        return _dilithium.uintVector_clear(self)

    def get_allocator(self):
        return _dilithium.uintVector_get_allocator(self)

    def pop_back(self):
        return _dilithium.uintVector_pop_back(self)

    def erase(self, *args):
        return _dilithium.uintVector_erase(self, *args)

    def __init__(self, *args):
        this = _dilithium.new_uintVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _dilithium.uintVector_push_back(self, x)

    def front(self):
        return _dilithium.uintVector_front(self)

    def back(self):
        return _dilithium.uintVector_back(self)

    def assign(self, n, x):
        return _dilithium.uintVector_assign(self, n, x)

    def resize(self, *args):
        return _dilithium.uintVector_resize(self, *args)

    def insert(self, *args):
        return _dilithium.uintVector_insert(self, *args)

    def reserve(self, n):
        return _dilithium.uintVector_reserve(self, n)

    def capacity(self):
        return _dilithium.uintVector_capacity(self)
    __swig_destroy__ = _dilithium.delete_uintVector
    __del__ = lambda self: None
uintVector_swigregister = _dilithium.uintVector_swigregister
uintVector_swigregister(uintVector)

class ucharVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ucharVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ucharVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _dilithium.ucharVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _dilithium.ucharVector___nonzero__(self)

    def __bool__(self):
        return _dilithium.ucharVector___bool__(self)

    def __len__(self):
        return _dilithium.ucharVector___len__(self)

    def __getslice__(self, i, j):
        return _dilithium.ucharVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _dilithium.ucharVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _dilithium.ucharVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _dilithium.ucharVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _dilithium.ucharVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _dilithium.ucharVector___setitem__(self, *args)

    def pop(self):
        return _dilithium.ucharVector_pop(self)

    def append(self, x):
        return _dilithium.ucharVector_append(self, x)

    def empty(self):
        return _dilithium.ucharVector_empty(self)

    def size(self):
        return _dilithium.ucharVector_size(self)

    def swap(self, v):
        return _dilithium.ucharVector_swap(self, v)

    def begin(self):
        return _dilithium.ucharVector_begin(self)

    def end(self):
        return _dilithium.ucharVector_end(self)

    def rbegin(self):
        return _dilithium.ucharVector_rbegin(self)

    def rend(self):
        return _dilithium.ucharVector_rend(self)

    def clear(self):
        return _dilithium.ucharVector_clear(self)

    def get_allocator(self):
        return _dilithium.ucharVector_get_allocator(self)

    def pop_back(self):
        return _dilithium.ucharVector_pop_back(self)

    def erase(self, *args):
        return _dilithium.ucharVector_erase(self, *args)

    def __init__(self, *args):
        this = _dilithium.new_ucharVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _dilithium.ucharVector_push_back(self, x)

    def front(self):
        return _dilithium.ucharVector_front(self)

    def back(self):
        return _dilithium.ucharVector_back(self)

    def assign(self, n, x):
        return _dilithium.ucharVector_assign(self, n, x)

    def resize(self, *args):
        return _dilithium.ucharVector_resize(self, *args)

    def insert(self, *args):
        return _dilithium.ucharVector_insert(self, *args)

    def reserve(self, n):
        return _dilithium.ucharVector_reserve(self, n)

    def capacity(self):
        return _dilithium.ucharVector_capacity(self)
    __swig_destroy__ = _dilithium.delete_ucharVector
    __del__ = lambda self: None
ucharVector_swigregister = _dilithium.ucharVector_swigregister
ucharVector_swigregister(ucharVector)

class charVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, charVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, charVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _dilithium.charVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _dilithium.charVector___nonzero__(self)

    def __bool__(self):
        return _dilithium.charVector___bool__(self)

    def __len__(self):
        return _dilithium.charVector___len__(self)

    def __getslice__(self, i, j):
        return _dilithium.charVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _dilithium.charVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _dilithium.charVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _dilithium.charVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _dilithium.charVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _dilithium.charVector___setitem__(self, *args)

    def pop(self):
        return _dilithium.charVector_pop(self)

    def append(self, x):
        return _dilithium.charVector_append(self, x)

    def empty(self):
        return _dilithium.charVector_empty(self)

    def size(self):
        return _dilithium.charVector_size(self)

    def swap(self, v):
        return _dilithium.charVector_swap(self, v)

    def begin(self):
        return _dilithium.charVector_begin(self)

    def end(self):
        return _dilithium.charVector_end(self)

    def rbegin(self):
        return _dilithium.charVector_rbegin(self)

    def rend(self):
        return _dilithium.charVector_rend(self)

    def clear(self):
        return _dilithium.charVector_clear(self)

    def get_allocator(self):
        return _dilithium.charVector_get_allocator(self)

    def pop_back(self):
        return _dilithium.charVector_pop_back(self)

    def erase(self, *args):
        return _dilithium.charVector_erase(self, *args)

    def __init__(self, *args):
        this = _dilithium.new_charVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _dilithium.charVector_push_back(self, x)

    def front(self):
        return _dilithium.charVector_front(self)

    def back(self):
        return _dilithium.charVector_back(self)

    def assign(self, n, x):
        return _dilithium.charVector_assign(self, n, x)

    def resize(self, *args):
        return _dilithium.charVector_resize(self, *args)

    def insert(self, *args):
        return _dilithium.charVector_insert(self, *args)

    def reserve(self, n):
        return _dilithium.charVector_reserve(self, n)

    def capacity(self):
        return _dilithium.charVector_capacity(self)
    __swig_destroy__ = _dilithium.delete_charVector
    __del__ = lambda self: None
charVector_swigregister = _dilithium.charVector_swigregister
charVector_swigregister(charVector)

class doubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, doubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, doubleVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _dilithium.doubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _dilithium.doubleVector___nonzero__(self)

    def __bool__(self):
        return _dilithium.doubleVector___bool__(self)

    def __len__(self):
        return _dilithium.doubleVector___len__(self)

    def __getslice__(self, i, j):
        return _dilithium.doubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _dilithium.doubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _dilithium.doubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _dilithium.doubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _dilithium.doubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _dilithium.doubleVector___setitem__(self, *args)

    def pop(self):
        return _dilithium.doubleVector_pop(self)

    def append(self, x):
        return _dilithium.doubleVector_append(self, x)

    def empty(self):
        return _dilithium.doubleVector_empty(self)

    def size(self):
        return _dilithium.doubleVector_size(self)

    def swap(self, v):
        return _dilithium.doubleVector_swap(self, v)

    def begin(self):
        return _dilithium.doubleVector_begin(self)

    def end(self):
        return _dilithium.doubleVector_end(self)

    def rbegin(self):
        return _dilithium.doubleVector_rbegin(self)

    def rend(self):
        return _dilithium.doubleVector_rend(self)

    def clear(self):
        return _dilithium.doubleVector_clear(self)

    def get_allocator(self):
        return _dilithium.doubleVector_get_allocator(self)

    def pop_back(self):
        return _dilithium.doubleVector_pop_back(self)

    def erase(self, *args):
        return _dilithium.doubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _dilithium.new_doubleVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _dilithium.doubleVector_push_back(self, x)

    def front(self):
        return _dilithium.doubleVector_front(self)

    def back(self):
        return _dilithium.doubleVector_back(self)

    def assign(self, n, x):
        return _dilithium.doubleVector_assign(self, n, x)

    def resize(self, *args):
        return _dilithium.doubleVector_resize(self, *args)

    def insert(self, *args):
        return _dilithium.doubleVector_insert(self, *args)

    def reserve(self, n):
        return _dilithium.doubleVector_reserve(self, n)

    def capacity(self):
        return _dilithium.doubleVector_capacity(self)
    __swig_destroy__ = _dilithium.delete_doubleVector
    __del__ = lambda self: None
doubleVector_swigregister = _dilithium.doubleVector_swigregister
doubleVector_swigregister(doubleVector)

class _string_list(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, _string_list, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, _string_list, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _dilithium._string_list_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _dilithium._string_list___nonzero__(self)

    def __bool__(self):
        return _dilithium._string_list___bool__(self)

    def __len__(self):
        return _dilithium._string_list___len__(self)

    def __getslice__(self, i, j):
        return _dilithium._string_list___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _dilithium._string_list___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _dilithium._string_list___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _dilithium._string_list___delitem__(self, *args)

    def __getitem__(self, *args):
        return _dilithium._string_list___getitem__(self, *args)

    def __setitem__(self, *args):
        return _dilithium._string_list___setitem__(self, *args)

    def pop(self):
        return _dilithium._string_list_pop(self)

    def append(self, x):
        return _dilithium._string_list_append(self, x)

    def empty(self):
        return _dilithium._string_list_empty(self)

    def size(self):
        return _dilithium._string_list_size(self)

    def swap(self, v):
        return _dilithium._string_list_swap(self, v)

    def begin(self):
        return _dilithium._string_list_begin(self)

    def end(self):
        return _dilithium._string_list_end(self)

    def rbegin(self):
        return _dilithium._string_list_rbegin(self)

    def rend(self):
        return _dilithium._string_list_rend(self)

    def clear(self):
        return _dilithium._string_list_clear(self)

    def get_allocator(self):
        return _dilithium._string_list_get_allocator(self)

    def pop_back(self):
        return _dilithium._string_list_pop_back(self)

    def erase(self, *args):
        return _dilithium._string_list_erase(self, *args)

    def __init__(self, *args):
        this = _dilithium.new__string_list(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _dilithium._string_list_push_back(self, x)

    def front(self):
        return _dilithium._string_list_front(self)

    def back(self):
        return _dilithium._string_list_back(self)

    def assign(self, n, x):
        return _dilithium._string_list_assign(self, n, x)

    def resize(self, *args):
        return _dilithium._string_list_resize(self, *args)

    def insert(self, *args):
        return _dilithium._string_list_insert(self, *args)

    def reserve(self, n):
        return _dilithium._string_list_reserve(self, n)

    def capacity(self):
        return _dilithium._string_list_capacity(self)
    __swig_destroy__ = _dilithium.delete__string_list
    __del__ = lambda self: None
_string_list_swigregister = _dilithium._string_list_swigregister
_string_list_swigregister(_string_list)

class _string_list_list(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, _string_list_list, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, _string_list_list, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _dilithium._string_list_list_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _dilithium._string_list_list___nonzero__(self)

    def __bool__(self):
        return _dilithium._string_list_list___bool__(self)

    def __len__(self):
        return _dilithium._string_list_list___len__(self)

    def __getslice__(self, i, j):
        return _dilithium._string_list_list___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _dilithium._string_list_list___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _dilithium._string_list_list___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _dilithium._string_list_list___delitem__(self, *args)

    def __getitem__(self, *args):
        return _dilithium._string_list_list___getitem__(self, *args)

    def __setitem__(self, *args):
        return _dilithium._string_list_list___setitem__(self, *args)

    def pop(self):
        return _dilithium._string_list_list_pop(self)

    def append(self, x):
        return _dilithium._string_list_list_append(self, x)

    def empty(self):
        return _dilithium._string_list_list_empty(self)

    def size(self):
        return _dilithium._string_list_list_size(self)

    def swap(self, v):
        return _dilithium._string_list_list_swap(self, v)

    def begin(self):
        return _dilithium._string_list_list_begin(self)

    def end(self):
        return _dilithium._string_list_list_end(self)

    def rbegin(self):
        return _dilithium._string_list_list_rbegin(self)

    def rend(self):
        return _dilithium._string_list_list_rend(self)

    def clear(self):
        return _dilithium._string_list_list_clear(self)

    def get_allocator(self):
        return _dilithium._string_list_list_get_allocator(self)

    def pop_back(self):
        return _dilithium._string_list_list_pop_back(self)

    def erase(self, *args):
        return _dilithium._string_list_list_erase(self, *args)

    def __init__(self, *args):
        this = _dilithium.new__string_list_list(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _dilithium._string_list_list_push_back(self, x)

    def front(self):
        return _dilithium._string_list_list_front(self)

    def back(self):
        return _dilithium._string_list_list_back(self)

    def assign(self, n, x):
        return _dilithium._string_list_list_assign(self, n, x)

    def resize(self, *args):
        return _dilithium._string_list_list_resize(self, *args)

    def insert(self, *args):
        return _dilithium._string_list_list_insert(self, *args)

    def reserve(self, n):
        return _dilithium._string_list_list_reserve(self, n)

    def capacity(self):
        return _dilithium._string_list_list_capacity(self)
    __swig_destroy__ = _dilithium.delete__string_list_list
    __del__ = lambda self: None
_string_list_list_swigregister = _dilithium._string_list_list_swigregister
_string_list_list_swigregister(_string_list_list)


_dilithium.MODE_swigconstant(_dilithium)
MODE = _dilithium.MODE

_dilithium.CRYPTO_PUBLICKEYBYTES_swigconstant(_dilithium)
CRYPTO_PUBLICKEYBYTES = _dilithium.CRYPTO_PUBLICKEYBYTES

_dilithium.CRYPTO_SECRETKEYBYTES_swigconstant(_dilithium)
CRYPTO_SECRETKEYBYTES = _dilithium.CRYPTO_SECRETKEYBYTES

_dilithium.CRYPTO_BYTES_swigconstant(_dilithium)
CRYPTO_BYTES = _dilithium.CRYPTO_BYTES

_dilithium.CRYPTO_ALGNAME_swigconstant(_dilithium)
CRYPTO_ALGNAME = _dilithium.CRYPTO_ALGNAME

def crypto_sign_keypair(pk, sk):
    return _dilithium.crypto_sign_keypair(pk, sk)
crypto_sign_keypair = _dilithium.crypto_sign_keypair

def crypto_sign(sm, smlen, msg, len, sk):
    return _dilithium.crypto_sign(sm, smlen, msg, len, sk)
crypto_sign = _dilithium.crypto_sign

def crypto_sign_open(m, mlen, sm, smlen, pk):
    return _dilithium.crypto_sign_open(m, mlen, sm, smlen, pk)
crypto_sign_open = _dilithium.crypto_sign_open

def randombytes(x, xlen):
    return _dilithium.randombytes(x, xlen)
randombytes = _dilithium.randombytes
class Dilithium(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Dilithium, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Dilithium, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _dilithium.new_Dilithium(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _dilithium.delete_Dilithium
    __del__ = lambda self: None

    def sign(self, message):
        return _dilithium.Dilithium_sign(self, message)

    def getSK(self):
        return _dilithium.Dilithium_getSK(self)

    def getPK(self):
        return _dilithium.Dilithium_getPK(self)

    def getSecretKeySize(self):
        return _dilithium.Dilithium_getSecretKeySize(self)

    def getPublicKeySize(self):
        return _dilithium.Dilithium_getPublicKeySize(self)
    __swig_getmethods__["sign_open"] = lambda x: _dilithium.Dilithium_sign_open
    if _newclass:
        sign_open = staticmethod(_dilithium.Dilithium_sign_open)
    __swig_getmethods__["extract_message"] = lambda x: _dilithium.Dilithium_extract_message
    if _newclass:
        extract_message = staticmethod(_dilithium.Dilithium_extract_message)
    __swig_getmethods__["extract_signature"] = lambda x: _dilithium.Dilithium_extract_signature
    if _newclass:
        extract_signature = staticmethod(_dilithium.Dilithium_extract_signature)
Dilithium_swigregister = _dilithium.Dilithium_swigregister
Dilithium_swigregister(Dilithium)

def Dilithium_sign_open(message_output, message_signed, pk):
    return _dilithium.Dilithium_sign_open(message_output, message_signed, pk)
Dilithium_sign_open = _dilithium.Dilithium_sign_open

def Dilithium_extract_message(message_output):
    return _dilithium.Dilithium_extract_message(message_output)
Dilithium_extract_message = _dilithium.Dilithium_extract_message

def Dilithium_extract_signature(message_output):
    return _dilithium.Dilithium_extract_signature(message_output)
Dilithium_extract_signature = _dilithium.Dilithium_extract_signature

# This file is compatible with both classic and new-style classes.


