# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import docifier-test
from docifier-test.models.company_executive import CompanyExecutive  # noqa: E501
from docifier-test.rest import ApiException

class TestCompanyExecutive(unittest.TestCase):
    """CompanyExecutive unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CompanyExecutive
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = docifier-test.models.company_executive.CompanyExecutive()  # noqa: E501
        if include_optional :
            return CompanyExecutive(
                symbol = '0', 
                executive = [
                    docifier-test.models.company.Company(
                        name = '0', 
                        age = 56, 
                        title = '0', 
                        since = '0', 
                        sex = '0', 
                        compensation = 56, 
                        currency = '0', )
                    ]
            )
        else :
            return CompanyExecutive(
        )

    def testCompanyExecutive(self):
        """Test CompanyExecutive"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
