# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import docifier-test
from docifier-test.models.earning_estimate import EarningEstimate  # noqa: E501
from docifier-test.rest import ApiException

class TestEarningEstimate(unittest.TestCase):
    """EarningEstimate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EarningEstimate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = docifier-test.models.earning_estimate.EarningEstimate()  # noqa: E501
        if include_optional :
            return EarningEstimate(
                eps_avg = 1.337, 
                eps_high = 1.337, 
                eps_low = 1.337, 
                number_analysts = 56, 
                period = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else :
            return EarningEstimate(
        )

    def testEarningEstimate(self):
        """Test EarningEstimate"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
