# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import docifier-test
from docifier-test.models.indices_historical_constituents import IndicesHistoricalConstituents  # noqa: E501
from docifier-test.rest import ApiException

class TestIndicesHistoricalConstituents(unittest.TestCase):
    """IndicesHistoricalConstituents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IndicesHistoricalConstituents
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = docifier-test.models.indices_historical_constituents.IndicesHistoricalConstituents()  # noqa: E501
        if include_optional :
            return IndicesHistoricalConstituents(
                symbol = '0', 
                historical_constituents = [
                    docifier-test.models.index_historical_constituent.IndexHistoricalConstituent(
                        symbol = '0', 
                        action = '0', 
                        date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ]
            )
        else :
            return IndicesHistoricalConstituents(
        )

    def testIndicesHistoricalConstituents(self):
        """Test IndicesHistoricalConstituents"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
