# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import docifier-test
from docifier-test.models.indices_constituents import IndicesConstituents  # noqa: E501
from docifier-test.rest import ApiException

class TestIndicesConstituents(unittest.TestCase):
    """IndicesConstituents unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test IndicesConstituents
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = docifier-test.models.indices_constituents.IndicesConstituents()  # noqa: E501
        if include_optional :
            return IndicesConstituents(
                symbol = '0', 
                constituents = [
                    '0'
                    ]
            )
        else :
            return IndicesConstituents(
        )

    def testIndicesConstituents(self):
        """Test IndicesConstituents"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
