
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "4e1999d465ff73286dca9cc1b427c8bb401f0fb0",
 "version": "1.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
