
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-26T12:09:49+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "3413dc96cbe1bdf8ff27118bf0e8c4e2be7c7c02",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
