
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-27T08:29:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "03dd8b3895afcc195603205eaae632eed61f114d",
 "version": "v0.0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
