
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-28T20:52:37-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "3cc7c08698ab9e486cbc4f9ac225608135a0c9c1",
 "version": "0.0.105"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
