
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-27T17:41:31-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2c79472f0e10f3a6914f6088cf012f72d628cb2a",
 "version": "0.8.217"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
