
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-28T18:09:49-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "60f63295d28a5baeb8398ceb1510fdb53388a3a8",
 "version": "0.0.99"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
