
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-26T16:06:05+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "89d68a16b46cebc6e7a00257dd85bd59eeba7785",
 "version": "1.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
