
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-28T20:57:06-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "637bd291ac2b10f25b1a5670b6d244bbb24d17dc",
 "version": "0.0.106"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
