# Generated by Django 2.1.15 on 2020-04-08 12:26

from django.db import migrations, models

from opening_hours_management.conf import settings as local_settings


class Migration(migrations.Migration):

    dependencies = [("opening_hours_management", "0003_auto_20200408_1214")]

    operations = [
        migrations.AddField(
            model_name="specificperiodhours",
            name="closure_reason",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=local_settings.CLOSURE_CAUSE_CHOICES,
                null=True,
                verbose_name="Closure reason",
            ),
        )
    ]
