# Generated by Django 3.1.1 on 2020-09-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayewa', '0002_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='name',
        ),
    ]
