# Generated by Django 3.1.2 on 2020-10-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayewa', '0006_resourceclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_class',
            field=models.ManyToManyField(blank=True, related_name='resource_class', to='ayewa.ResourceClass'),
        ),
    ]
