# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from zepben.protobuf.dc import dc_requests_pb2 as zepben_dot_protobuf_dot_dc_dot_dc__requests__pb2
from zepben.protobuf.dc import dc_responses_pb2 as zepben_dot_protobuf_dot_dc_dot_dc__responses__pb2


class DiagramConsumerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDiagram = channel.unary_unary(
                '/zepben.protobuf.dc.DiagramConsumer/GetDiagram',
                request_serializer=zepben_dot_protobuf_dot_dc_dot_dc__requests__pb2.GetDiagramRequest.SerializeToString,
                response_deserializer=zepben_dot_protobuf_dot_dc_dot_dc__responses__pb2.GetDiagramResponse.FromString,
                )


class DiagramConsumerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDiagram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiagramConsumerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDiagram': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDiagram,
                    request_deserializer=zepben_dot_protobuf_dot_dc_dot_dc__requests__pb2.GetDiagramRequest.FromString,
                    response_serializer=zepben_dot_protobuf_dot_dc_dot_dc__responses__pb2.GetDiagramResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zepben.protobuf.dc.DiagramConsumer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiagramConsumer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDiagram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zepben.protobuf.dc.DiagramConsumer/GetDiagram',
            zepben_dot_protobuf_dot_dc_dot_dc__requests__pb2.GetDiagramRequest.SerializeToString,
            zepben_dot_protobuf_dot_dc_dot_dc__responses__pb2.GetDiagramResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
