
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-23T16:28:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "60b93ffc29921767a8ea1a3f18881af2010ee1b1",
 "version": "0.20.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
