# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: zepben/protobuf/cc/cc-requests.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='zepben/protobuf/cc/cc-requests.proto',
  package='zepben.protobuf.cc',
  syntax='proto3',
  serialized_options=b'\n\026com.zepben.protobuf.ccP\001\252\002\022Zepben.Protobuf.CC',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$zepben/protobuf/cc/cc-requests.proto\x12\x12zepben.protobuf.cc\"\x14\n\x12GetCustomerRequestB/\n\x16\x63om.zepben.protobuf.ccP\x01\xaa\x02\x12Zepben.Protobuf.CCb\x06proto3'
)




_GETCUSTOMERREQUEST = _descriptor.Descriptor(
  name='GetCustomerRequest',
  full_name='zepben.protobuf.cc.GetCustomerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['GetCustomerRequest'] = _GETCUSTOMERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetCustomerRequest = _reflection.GeneratedProtocolMessageType('GetCustomerRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCUSTOMERREQUEST,
  '__module__' : 'zepben.protobuf.cc.cc_requests_pb2'
  # @@protoc_insertion_point(class_scope:zepben.protobuf.cc.GetCustomerRequest)
  })
_sym_db.RegisterMessage(GetCustomerRequest)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
