# coding: utf-8

# flake8: noqa
"""
    MailMojo API

    v1 of the MailMojo API  # noqa: E501

    OpenAPI spec version: 1.1.0
    Contact: hjelp@mailmojo.no
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from mailmojo_sdk.models.add_form_subscriber import AddFormSubscriber
from mailmojo_sdk.models.base_contact import BaseContact
from mailmojo_sdk.models.campaign_detail import CampaignDetail
from mailmojo_sdk.models.campaign_statistics import CampaignStatistics
from mailmojo_sdk.models.category import Category
from mailmojo_sdk.models.contact import Contact
from mailmojo_sdk.models.contact_list import ContactList
from mailmojo_sdk.models.contacts import Contacts
from mailmojo_sdk.models.domain import Domain
from mailmojo_sdk.models.embed import Embed
from mailmojo_sdk.models.embed_options import EmbedOptions
from mailmojo_sdk.models.form import Form
from mailmojo_sdk.models.form_conversion import FormConversion
from mailmojo_sdk.models.historical_contacts_stats import HistoricalContactsStats
from mailmojo_sdk.models.import_result import ImportResult
from mailmojo_sdk.models.inline_response200 import InlineResponse200
from mailmojo_sdk.models.list import List
from mailmojo_sdk.models.list_detail import ListDetail
from mailmojo_sdk.models.minimal_segment import MinimalSegment
from mailmojo_sdk.models.newsletter_creation import NewsletterCreation
from mailmojo_sdk.models.newsletter_detail import NewsletterDetail
from mailmojo_sdk.models.newsletter_send import NewsletterSend
from mailmojo_sdk.models.newsletter_send_test import NewsletterSendTest
from mailmojo_sdk.models.newsletter_update import NewsletterUpdate
from mailmojo_sdk.models.page import Page
from mailmojo_sdk.models.page_meta import PageMeta
from mailmojo_sdk.models.schema import Schema
from mailmojo_sdk.models.segment import Segment
from mailmojo_sdk.models.segment_creation import SegmentCreation
from mailmojo_sdk.models.segment_tag_predicate import SegmentTagPredicate
from mailmojo_sdk.models.statistics import Statistics
from mailmojo_sdk.models.subscriber import Subscriber
from mailmojo_sdk.models.template import Template
from mailmojo_sdk.models.track_form_view import TrackFormView
from mailmojo_sdk.models.track_page_view import TrackPageView
from mailmojo_sdk.models.user import User
from mailmojo_sdk.models.user_creation import UserCreation
from mailmojo_sdk.models.webhook_creation import WebhookCreation
