
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-21T03:28:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8d76dedd2b0c71e5b291f4a42fee920cf343c224",
 "version": "1.13.0.post.dev207"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
