DEFAULT_SERVER_HOST = 'localhost'
DEFAULT_SERVER_PORT = 11211
DEFAULT_POOL_MINSIZE = 2
DEFAULT_POOL_MAXSIZE = 5
DEFAULT_TIMEOUT = 1
DEFAULT_MAX_KEY_LENGTH = 250
DEFAULT_MAX_VALUE_LENGTH = 1024 * 1024  # 1 megabyte

STORED = b'STORED\r\n'
NOT_STORED = b'NOT_STORED\r\n'
EXISTS = b'EXISTS\r\n'
NOT_FOUND = b'NOT_FOUND\r\n'
DELETED = b'DELETED\r\n'
TOUCHED = b'TOUCHED\r\n'

END = b'END\r\n'
VERSION = b'VERSION'
OK = b'OK\r\n'
