-- -*- coding: utf-8 -*- äöü
BEGIN TRANSACTION;
-- neue Version mit finaler Liste: --> update-0064.sql
INSERT INTO witrabau.p2_committee
   (committee_acronym,     --  'Kurztitel Gremium'
    committee_label,       --  'Langtitel Gremium'
    committee_description, --  'Beschreibung Gremium'
    institution_acronym,   --  'Kurztitel Träger'
    institution_label)     --  'Langtitel Träger'
VALUES
('Geschäftsführerkreis Düsseldorf /  Mitgliederversammlung', 'Geschäftsführerkreis Düsseldorf /  Mitgliederversammlung', NULL, 'AiF', 'AiF - Arbeitsgemeinschaft industrieller Forschungsvereinigungen'),
('Gutachtergruppe 1 + 2', 'Gutachtergruppe 1 + 2 Forschungsanträge', NULL, 'AiF', 'AiF - Arbeitsgemeinschaft industrieller Forschungsvereinigungen'),
('Arbeitgruppe "Forschungsdaten"', 'Arbeitgruppe "Forschungsdaten"', NULL, '<AddWO>', 'Allianz der deutschen Wissenschaftsorganisation'),
('Lenkungsausschuss zur Branchenregelung "Gefahrstoff-Kommunikation in der Lieferkette der Bauwirtschaft"', 'Lenkungsausschuss zur Branchenregelung "Gefahrstoff-Kommunikation in der Lieferkette der Bauwirtschaft"', NULL, 'BG Bau', 'Berufsgenossenschaft der Bauwirtschaft (BG Bau)'),
('Runder Tisch "Sozialer Dialog Quarz"', 'Runder Tisch "Sozialer Dialog Quarz"', NULL, '<BGkGI>', 'Berufsgenossenschaft der keramischen und Glas-Industrie'),
('BTB/DBV/VDZ-Gemeinschaftsarbeitskreis "Beton"', 'BTB/DBV/VDZ-Gemeinschaftsarbeitskreis "Beton"', NULL, 'BTB / DBV / VDZ', 'BTB / DBV / VDZ'),
('Technischer Kontaktarbeitskreis', 'Technischer Kontaktarbeitskreis', NULL, 'BTB / VDZ', 'BTB / VDZ'),
('Mitglied des Vorstands', 'Mitglied des Vorstands', NULL, '<BdI WAK-LV BaWü>', 'Bund der Ingenieure für Wasserwirtschaft, Abfallwirtschaft und Kulturbau - Landesverband Baden-Würtemberg'),
('AG 2.2 "Betonbautechnik"', 'Arbeitsgruppe 2.2 "Betonbautechnik"', NULL, 'BASt', 'Bundesanstalt für Strassenwesen (BASt)'),
('Betreuungsausschuss FE 06.0104/2013/CGB', 'Betreuungsausschuss FE 06.0104/2013/CGB', NULL, 'BASt', 'Bundesanstalt für Strassenwesen (BASt)'),
('FE 08.0218/2012/IGB "Instandsetzung von Betondecken mit dünnschichtigem Neubeton"', 'FE 08.0218/2012/IGB "Instandsetzung von Betondecken mit dünnschichtigem Neubeton"', NULL, 'BASt', 'Bundesanstalt für Strassenwesen (BASt)'),
('FE 08.0219/2012/IGB "Grindingtexturierte Waschbetondecken"', 'FE 08.0219/2012/IGB "Grindingtexturierte Waschbetondecken"', NULL, 'BASt', 'Bundesanstalt für Strassenwesen (BASt)'),
('FE 09.0170/2011/ARB "Integrale Betrachtung der Eigenschaften von Fahrbahnoberflächen"', 'FE 09.0170/2011/ARB "Integrale Betrachtung der Eigenschaften von Fahrbahnoberflächen"', NULL, 'BASt', 'Bundesanstalt für Strassenwesen (BASt)'),
('FE 15.0604/2014/DRB', 'FE 15.0604/2014/DRB', NULL, 'BASt', 'Bundesanstalt für Strassenwesen (BASt)'),
('FE "Drainbeton"', 'FE "Drainbeton"', NULL, 'BASt', 'Bundesanstalt für Strassenwesen (BASt)'),
('Runder Tisch Ressourceneffizienz im Bauwesen', 'Runder Tisch Ressourceneffizienz im Bauwesen', NULL, '<BIfBSR>', 'Bundesinstitut für Bau-, Stadt- und Raumforschung'),
('EG-Harmonisierung im Bauwesen', 'EG-Harmonisierung im Bauwesen', NULL, 'BMUB', 'Bundesministerium für Umwelt, Natur, Bau und Reaktorsicherheit (BMUB)'),
('Vorbereitender Ausschuss', 'Vorbereitender Ausschuss', NULL, 'BMUB', 'Bundesministerium für Umwelt, Natur, Bau und Reaktorsicherheit (BMUB)'),
('Bauproduktenrecht', 'Bauproduktenrecht', NULL, 'BMVBS', 'Bundesministerium für Verkehr, Bau und Stadtentwicklung (BMVBS)'),
('Lenkungsausschuss "PPP im öffentlichen Hochbau"', 'Lenkungsausschuss "PPP im öffentlichen Hochbau"', NULL, 'BMVBS', 'Bundesministerium für Verkehr, Bau und Stadtentwicklung (BMVBS)'),
('Runder Tisch "Nachhaltiges Bauen"', 'Runder Tisch "Nachhaltiges Bauen"', NULL, 'BMVBS', 'Bundesministerium für Verkehr, Bau und Stadtentwicklung (BMVBS)'),
('Forschungsnetzwerk Energie in Gebäuden und Quartieren', 'Forschungsnetzwerk Energie in Gebäuden und Quartieren ', NULL, 'BMWI', 'Bundesministerium für Wirtschaft und Energie'),
('Projektgruppe Marketing- und Kommunikationskreis MKK', 'Projektgruppe Marketing- und Kommunikationskreis MKK', NULL, 'BAKA', 'Bundesverband Altbauerneuerung e.V. BAKA'),
('AA Marktforschung und Statistik', 'Arbeitsausschuss "Marktforschung und Statistik"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('AA Öffentlichkeitsarbeit', 'Arbeitsausschuss "Öffentlichkeitsarbeit"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('AA Verkehr und Logistik', 'Arbeitsausschuss "Verkehr und Logistik"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('Ausschuss "Bauwirtschaft und Logistik"', 'Ausschuss "Bauwirtschaft und Logistik"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('Ausschuss "Energie"', 'Ausschuss "Energie"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('Ausschuss "Recht"', 'Ausschuss "Recht"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('Ausschuss "Rohstoffe"', 'Ausschuss "Rohstoffe"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('Ausschuss "Steuern"', 'Ausschuss "Steuern"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('Ausschuss "Technik und Normung"', 'Ausschuss "Technik und Normung"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('Ausschuss "Umwelt"', 'Ausschuss "Umwelt"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('Geschäftsführerkreis', 'Geschäftsführerkreis', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('PG" Arbeitsschutz Gefahrstoffe"', 'Projektgruppe "Arbeitsschutz Gefahrstoffe"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('PG "Energieeffiziente Gebäude"', 'Projektgruppe "Energieeffiziente Gebäude"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('PG "Nachhaltigkeit / EPD / Dauerhaftigkeit"', 'Projektgruppe "Nachhaltigkeit / EPD / Dauerhaftigkeit"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('PG "Nachhaltigkeit"', 'Projektgruppe "Nachhaltigkeit"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('PG "Radioaktivität aus Bauprodukten"', 'Projektgruppe "Radioaktivität aus Bauprodukten"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('PG "REACH / Bauproduktenrichtlinie"', 'Projektgruppe "REACH / Bauproduktenrichtlinie"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('PG "Ressourceneffizienz"', 'Projektgruppe "Ressourceneffizienz"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('PG "Wasser / Boden / Abfall"', 'Projektgruppe "Wasser / Boden / Abfall"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('PG "Wasser, Boden, Abfall"', 'Projektgruppe "Wasser, Boden, Abfall"', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)'),
('AK "Energiesteuern"', 'Arbeitskreis "Energiesteuern"', NULL, 'BDI', 'Bundesverband der Deutschen Industrie e.V. (BDI)'),
('AK "Immissionsschutz"', 'Arbeitskreis "Immissionsschutz"', NULL, 'BDI', 'Bundesverband der Deutschen Industrie e.V. (BDI)'),
('AK "Stoffpolitik"', 'Arbeitskreis "Stoffpolitik"', NULL, 'BDI', 'Bundesverband der Deutschen Industrie e.V. (BDI)'),
('Ausschuss "Energie- und Klimapolitik"', 'Ausschuss "Energie- und Klimapolitik"', NULL, 'BDI', 'Bundesverband der Deutschen Industrie e.V. (BDI)'),
('PG "ETS-post-2020"', 'Projektgruppe "ETS-post-2020"', NULL, 'BDI', 'Bundesverband der Deutschen Industrie e.V. (BDI)'),
('PG "Kreislaufwirtschaft" einschl. AK Wertstoffgesetz', 'Projektgruppe "Kreislaufwirtschaft" einschl. AK Wertstoffgesetz', NULL, 'BDI', 'Bundesverband der Deutschen Industrie e.V. (BDI)'),
('UA 1 "Betrieblicher Umweltschutz"', 'Unterausschuss 1 "Betrieblicher Umweltschutz"', NULL, 'BDI', 'Bundesverband der Deutschen Industrie e.V. (BDI)'),
('UA "Klimapolitik"', 'Unterausschuss "Klimapolitik"', NULL, 'BDI', 'Bundesverband der Deutschen Industrie e.V. (BDI)'),
('Ausschuss "Klima und Energie"', 'Ausschuss "Klima und Energie"', NULL, 'BV Kalk', 'Bundesverband der Deutschen Kalkindustrie e.V. (BV Kalk)'),
('AK "Betonböden"', 'Arbeitskreis "Betonböden"', NULL, 'BEB', 'Bundesverband Estrich und Belag e.V. (BEB)'),
('AK "CEM II in Estrichen"', 'Arbeitskreis "CEM II in Estrichen"', NULL, 'BEB', 'Bundesverband Estrich und Belag e.V. (BEB)'),
('AK "Zementgebundene Industrie-Estriche"', 'Arbeitskreis "Zementgebundene Industrie-Estriche"', NULL, 'BEB', 'Bundesverband Estrich und Belag e.V. (BEB)'),
('AG "Quarz"', 'Arbeitsgruppe "Quarz"', NULL, 'MIRO', 'Bundesverband Mineralische Rohstoffe e.V. (MIRO)'),
('Industrieller Kontaktausschuss AKR', 'Industrieller Kontaktausschuss AKR', NULL, 'MIRO', 'Bundesverband Mineralische Rohstoffe e.V. (MIRO)'),
('Wissenschaftlicher Beirat', 'Wissenschaftlicher Beirat', NULL, '<BV Schimmelpilz-Sanierung>', 'Bundesverband Schimmelpilz-Sanierung e.V.'),
('C³ Konsortium', 'C³ Konsortium', NULL, 'C³ e.V.', 'C³ - Carbon Concrete Composite e.V.'),
('Sektorkomitee Emissionshandel', 'Sektorkomitee Emissionshandel', NULL, 'Dakks', 'DakkS -  Deutsche Akkreditierungsstelle GmbH'),
('AK 2.1 "Beton- und Mörtelzusatzmittel und Umwelt"', 'Arbeitskreis 2.1 "Beton- und Mörtelzusatzmittel und Umwelt"', NULL, 'DBC', 'Deutsche Bauchemie e.V.'),
('Koordinierungsausschuss', 'Koordinierungsausschuss', NULL, 'VDZ-DBC', 'Deutsche Bauchemie e.V. / VDZ'),
('PK "W347: Hygienische Anforderungen an zementgebundene Werkstoffe im Trinkwasserbereich"', 'PK "W347: Hygienische Anforderungen an zementgebundene Werkstoffe im Trinkwasserbereich"', NULL, 'DVGW', 'Deutsche Gesellschaft des Gas- und Wasserfaches (DVGW)'),
('Bauproduktebeirat', 'Bauproduktebeirat', NULL, 'DGNB', 'Deutsche gesellschaft für Nachhaltiges Bauen e.V. (DGNB)'),
('DGNB-Fachausschuss', 'DGNB-Fachausschuss', NULL, 'DGNB', 'Deutsche Gesellschaft für Nachhaltiges Bauen e.V. (DGNB)'),
('Expertengruppe Ökobilanzierung', 'Expertengruppe Ökobilanzierung', NULL, 'DGNB', 'Deutsche Gesellschaft für Nachhaltiges Bauen e.V. (DGNB)'),
('UA Feuchte', 'Fachausschuss Bauwesen / Unterausschuss Feuchte', NULL, 'DGZfP', '﻿Deutsche Gesellschaft für zerstörungsfreie Prüfungen e.V. (DGZfP)'),
('UA Korrosionsnachweis', 'Fachausschuss Bauwesen / Unterausschuss Korrosionsnachweis', NULL, 'DGZfP', 'Deutsche Gesellschaft für zerstörungsfreie Prüfungen e.V. (DGZfP)'),
('UA LIBS', 'Fachausschuss Bauwesen / Unterausschuss LIBS', NULL, 'DGZfP', 'Deutsche Gesellschaft für zerstörungsfreie Prüfungen e.V. (DGZfP)'),
('AHG Parkdecks', 'Ad-hoc-Gruppe Dauerhaftigkeit von befahrenen Parkdecks', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('AG Dauerhaftigkeit', 'Arbeitsgruppe  Dauerhaftigkeitsbemessung (TA BT)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('AG Ermüdung', 'Arbeitsgruppe Ermüdung (TA BEW)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('AG Sulfatwiderstand', 'Arbeitsgruppe Sulfatwiderstand (TA BT)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('AG Praxisfrost', 'Arbeitsgruppe Übertragbarkeit von Frost-Laborversuchen auf Praxisverhältnisse (TA BT)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('AG Verbund', 'Arbeitsgruppe Verbundprüfung (TA BEW)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('AG VB/VM', 'Arbeitsgruppe Vergussbeton/Vergussmörtel (TA BT)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('AK Ausführung', 'Arbeitskreis Ausführung (TA SIB)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('AK Belastungsversuche', 'Arbeitskreis Belastungsversuche an Betonbauwerken (TA BK)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('AK KKS', 'Arbeitskreis Kathodischer Korrosionsschutz (TA SIB)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('AK Mörtel', 'Arbeitskreis Mörtel (TA SIB)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('AK Oberflächenschutzsysteme', 'Arbeitskreis Oberflächenschutzsysteme (TA SIB)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('AK Planung', 'Arbeitskreis Planung (TA SIB)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('AK Rissfüllstoffe', 'Arbeitskreis Rissfüllstoffe (TA SIB)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('Forschungsbeirat', 'Forschungsbeirat', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('TA BAU', 'Technischer Ausschuss Bauausführung', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('TA BK', 'Technischer Ausschuss Bemessung und Konstruktion', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('TA BBR', 'Technischer Ausschuss Betonbrücken', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('TA BT', 'Technischer Ausschuss Betontechnik', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('TA BEW', 'Technischer Ausschuss Bewehrung', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('TA SIB', 'Technischer Ausschuss Schutz und Instandsetzung von Betonbauteilen', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('TA Umwelt', 'Technischer Ausschuss Umwelt', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('UA AKR', 'Unterausschuss  Alkalikieselsäurereaktion (AKR1: Prüfverfahren; AKR2: Instandsetzung; AKR3: Richtlinie, TA BT)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('UA Befestigungstechnik', 'Unterausschuss Befestigungstechnik (TA BK, TA BEW)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('UA BBUmwS', 'Unterausschuss Betonbau beim Umgang mit wassergefährdenden Stoffen', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('UA Bewertung von Bestandsbauwerken', 'Unterausschuss Bewertung von Bestandsbauwerken (TA BK)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('UA Brand', 'Unterausschuss Heißbemessung im Betonbau (TA BK)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('UA Herstellung von Beton unter Verwendung von rezyklierten Gesteinskörnungen', 'Unterausschuss Herstellung von Beton unter Verwendung von rezyklierten Gesteinskörnungen', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('UA MB', 'Unterausschuss Massige Bauteile aus Beton (TA BT)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('UA NB', 'Unterausschuss Nachbehandlung von Beton (TA BAU)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('UA NBB', 'Unterausschuss Nachhaltig Bauen mit Beton (AG 0 NBB Arbeitsgruppe Grundsätze des nachhaltigen Bauens mit Beton, TA Umwelt)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('UA SVB', 'Unterausschuss Selbstverdichtender Beton (TA BK)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('UA SFB', 'Unterausschuss Stahlfaserbeton (TA BK)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('UA Trockenbeton', 'Unterausschuss Trockenbeton (TA BT)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('UA UHFB', 'Unterausschuss  Ultrahochfester Beton (AG 1: Betontechnik und Ausführung; AG 2: Bemessung und Konstruktion, TA BT) ', 'Entwicklung einer Richtlinie; Beton- und ausführungstechnische Anforderungen an UHFB; Bemessungsverfahren und Konstruktionsregeln für UHFB', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('UA Verstärken ', 'Unterausschuss Verstärken von Betonbauteilen (TA BK)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('UA VZ', 'Unterausschuss Verzögerter Beton (TA BT)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('UA WU', 'Unterausschuss Wasserundurchlässige Bauwerke aus Beton (TA BT)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)'),
('AK Betonieren im Winter', 'AK Betonieren im Winter', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('Ausbildungsbeirat Beton', 'Ausbildungsbeirat Beton', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('Ausbildungsbeirat Schutz und Instandsetzung im Betonbau', 'Ausbildungsbeirat Schutz und Instandsetzung im Betonbau', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HABA-AK Anwendung zerstörungsfreier Prüfverfahren im Bauwesen', 'HABA-Arbeitskreis Anwendung zerstörungsfreier Prüfverfahren im Bauwesen ', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HABA-AK Betonkosmetik', 'HABA-Arbeitskreis Betonkosmetik', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HABA-AK Industrieböden', 'HABA-Arbeitskreis Industrieböden', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HABA-AK Instandsetzung', 'HABA-Arbeitskreis Instandsetzung', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HABA-AK Qualität der Planung', 'HABA-Arbeitskreis Qualität der Planung', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HABA-AK WU-Dächer', 'HABA-Arbeitskreis WU-Dächer', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HAB-AK Brückenbau', 'HAB-Arbeitskreis Brückenbau (Gruppe 1: Monitoring; Gruppe 2: Verfahren, Gruppe 3: Konstruktionen) ', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HAB-AK Parkhäuser und Tiefgaragen', 'HAB-Arbeitskreis Parkhäuser und Tiefgaragen', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HAB-AK Pflichtenheft Tragwerksplanung', 'HAB-Arbeitskreis Pflichtenheft Tragwerksplanung', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HAB-AK Rissbildung', 'HAB-Arbeitskreis Rissbildung', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HAB-AK Software für Baustatik', 'HAB-Arbeitskreis Software für Baustatik', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HAB-AK Teilsicherheitsbeiwerte beim Bauen im Bestand', 'HAB-Arbeitskreis Teilsicherheitsbeiwerte beim Bauen im Bestand', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HABT-AK Bewertung der In-situ-Druckfestigkeit von Beton', 'HABT-Arbeitskreis Bewertung der In-situ-Druckfestigkeit von Beton', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HABT-AK Brückenkappen', 'HABT-Arbeitskreis Brückenkappen', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HABT-AK Chemischer Angriff', 'HABT-Arbeitskreis Chemischer Angriff', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HABT-AK Sichtbeton', 'HABT-Arbeitskreis Sichtbeton', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HABT-AK Stahlfaserbeton', 'HABT-Arbeitskreis Stahlfaserbeton', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HABT-AK Überarbeitung EN 206', 'HABT-Arbeitskreis Überarbeitung EN 206', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HABT-AK Zukünftige Qualitätssicherung im Betonbau', 'HABT-Arbeitskreis Zukünftige Qualitätssicherung im Betonbau', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HABA', 'Hauptausschuss Bauausführung', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HABT', 'Hauptausschuss Baustofftechnik', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HAB', 'Hauptausschuss Bautechnik ', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('HAF', 'Hauptausschuss Forschung', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)'),
('Verbandsrat', 'Verbandsrat', NULL, 'DV', 'Deutscher Verband für Wohnungswesen, Städtebau und Raumordnung e.V. (DV)'),
('Ad-hoc-Ausschuss Lastabtragende Wärmedämmung größerer Dicke unter Gründungsplatten', 'Ad-hoc-Ausschuss Lastabtragende Wärmedämmung größerer Dicke unter Gründungsplatten', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('Ad-hoc-Ausschuss Nachhaltigkeit von Bauprodukten im Zulassungsbereich', 'Ad-hoc-Ausschuss Nachhaltigkeit von Bauprodukten im Zulassungsbereich', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('SVA-AG Modellierung Dach und Fassade', 'Arbeitsgruppe Modellierung Dach und Fassade', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-PG Analytik', 'DIBt-Projektgruppe Analytik', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA-PG "Beregnete Bauteile"', 'DIBt-Projektgruppe "Beregnete Bauteile"', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-PG "Beton und zementgebundene Baustoffe"', 'DIBt-Projektgruppe "Beton und zementgebundene Baustoffe"', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA-PG "Boden- und Grundwassergefährdung durch Baustoffe"', 'DIBt-Projektgruppe "Boden- und Grundwassergefährdung durch Baustoffe"', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-PG "Instandsetzungssysteme für Beton" (Obmann)', 'DIBt-Projektgruppe "Instandsetzungssysteme für Beton" (Obmann)', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-PG "Prüf- und Messverfahren zur gesundheitlichen Bewertung von Bauprodukten, Sportbodenbeläge"', 'DIBt-Projektgruppe "Prüf- und Messverfahren zur gesundheitlichen Bewertung von Bauprodukten, Sportbodenbeläge"', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-PG "Reaktive Brandschutzbeschichtungen aus Sicht des Gesundheitsschutzes"', 'DIBt-Projektgruppe "Reaktive Brandschutzbeschichtungen aus Sicht des Gesundheitsschutzes"', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-PG "Sulfatwiderstandsprüfung"', 'DIBt-Projektgruppe "Sulfatwiderstandsprüfung"', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-PG "Verstärken von Betonbauteilen mit Textilbeton"', 'DIBt-Projektgruppe "Verstärken von Betonbauteilen mit Textilbeton"', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Abgasanlagen"', 'DIBt-Sachverständigenausschuss "Abgasanlagen"', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Außenliegende Wärmedämmung"', 'DIBt-Sachverständigenausschuss "Außenliegende Wärmedämmung"', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Baustoffe und Bauarten für Wärme- und Schallschutz"', 'DIBt-Sachverständigenausschuss "Baustoffe und Bauarten für Wärme- und Schallschutz"', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Beton, Stahlbeton und Spannbetonbauteile" A und B1', 'DIBt-Sachverständigenausschuss "Beton, Stahlbeton und Spannbetonbauteile" A und B1', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Betonstähle" A und B1', 'DIBt-Sachverständigenausschuss "Betonstähle" A und B1', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Betontechnologie" A - Grundsatzfragen', 'DIBt-Sachverständigenausschuss "Betontechnologie" A - Grundsatzfragen', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Betontechnologie" B1 - Bindemittel', 'DIBt-Sachverständigenausschuss "Betontechnologie" B1 - Bindemittel', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Betontechnologie" B3 - Betonzusatzstoffe', 'DIBt-Sachverständigenausschuss "Betontechnologie" B3 - Betonzusatzstoffe', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Betontechnologie" B4 - Betonzuschläge', 'DIBt-Sachverständigenausschuss "Betontechnologie" B4 - Betonzuschläge', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Betontechnologie" B5 - Sonderbetone und Sondermörtel', 'DIBt-Sachverständigenausschuss "Betontechnologie" B5 -  Sonderbetone und Sondermörtel', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Bewehrungselemente" B3', 'DIBt-Sachverständigenausschuss "Bewehrungselemente" B3', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Feuerungsanlagen"', 'DIBt-Sachverständigenausschuss "Feuerungsanlagen"', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Gesundheits- und Umweltschutz"', 'DIBt-Sachverständigenausschuss "Gesundheits- und Umweltschutz"', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Platten und Querkraftanschlüsse" A und B', 'DIBt-Sachverständigenausschuss "Platten und Querkraftanschlüsse" A und B', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA Schalldämmung und Schalldämmstoffe', 'DIBt-Sachverständigenausschuss "Schalldämmung und Schalldämmstoffe"', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Spannbetonhohlplatten" B2', 'DIBt-Sachverständigenausschuss "Spannbetonhohlplatten" B2', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Spannstähle" A und B1', 'DIBt-Sachverständigenausschuss "Spannstähle" A und B1', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Spannverfahren" A und B1', 'DIBt-Sachverständigenausschuss "Spannverfahren" A und B1', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Stahlfaserbeton" A und B', 'DIBt-Sachverständigenausschuss "Stahlfaserbeton" A und B', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA Umwelt A', 'DIBt-Sachverständigenausschuss "Umwelt A"', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Verbundbau" B2', 'DIBt-Sachverständigenausschuss "Verbundbau" B2', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('DIBt-SVA "Verstärken von Betonbauteilen" A und B1', 'DIBt-Sachverständigenausschuss "Verstärken von Betonbauteilen" A und B1', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('Niederschlagsabflüsse A', 'Niederschlagsabflüsse A', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)'),
('AA Werkstoffe und Bauteile im Kontakt mit Trinkwasser', 'AA Werkstoffe und Bauteile im Kontakt mit Trinkwasser', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau-STLB-Bau (LB 013)', 'Betonarbeiten', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NAB (NA 002-00-15-01 AK)', 'NA 002-00-15-01 Arbeitskreis "Auswaschung von Substanzen aus Beschichtungen"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NAB (NA 002-00-15 AA)', 'NA 002-00-15 Arbeitsausschuss "Bautenbeschichtungen"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-01-31 AA)', 'NA 005-01-31 Arbeitsausschuss "Nachhaltiges Bauen"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA005-51 FBR)', 'NA 005-01 Fachbereichsbeirat KOA 01 "Mechanische Festigkeit und Standsicherheit"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-02-96 AA)', 'NA 005-02-96 Arbeitsausschuss "Abdichtungssysteme auf Beton für Brücken und andere Verkehrsflächen"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-05-07 AA)', 'NA 005-05-07 Arbeitsausschuss "Baugrund, Pfähle"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-01-01 AK)', 'NA 005-07-01-01 Arbeitskreis "Befestigungsmittel"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-01-02 AK)', 'NA 005-07-01-02 Arbeitskreis "Stahlfaserbeton"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-01-03 AK)', 'NA 005-07-01-03 Arbeitskreis "Bauen im Bestand"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-01-04 AK)', 'NA 005-07-01-04 Arbeitskreis "Querkraft, Durchstanzen, Torsion"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-01-05 AK)', 'NA 005-07-01-05 Arbeitskreis "Heißbemessung"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-01-06 AK)', 'NA 005-07-01-06 Arbeitskreis "Schnittgrößen"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-01-07 AK)', 'NA 005-07-01-07 Arbeitskreis "Zeitabhängiges Materialverhalten"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-01-08 AK)', 'NA 005-07-01-08 Arbeitskreis "Ermüdung"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-01-09 AK)', 'NA 005-07-01-09 Arbeitskreis "Brücken"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-01-10 AK)', 'NA 005-07-01-10 Arbeitskreis "Verstärken und Bewehren mit FRP"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-01-11AK)', 'NA 005-07-01-11 Arbeitskreis "Dauerhaftigkeit, Lebensdauerbemessung"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-01 AA)', 'NA 005-07-01 Arbeitsausschuss "Bemessung und Konstruktion"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-02-01 AK)', 'NA 005-07-02-01 Arbeitskreis "Beton"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-02-02 AK)', 'NA 005-07-02-02 Arbeitskreis "Zugabewasser"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-02 AA)', 'NA 005-07-02 Arbeitsausschuss "Betontechnik"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-05 AA)', 'NA 005-07-05 Arbeitsausschuss "Prüfverfahren für Beton"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-06 AA)', 'NA 005-07-06 Arbeitsausschuss "Schutz, Instandsetzung und Verstärkung"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-08 AA)', 'NA 005-07-08 Arbeitsausschuss "Betonfertigteile"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-09 AA)', 'NA 005-07-09 Arbeitsausschuss "Porenbeton und haufwerksporiger Leichtbeton', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-10 AA)', 'NA 005-07-10 Arbeitsausschuss "Spritzbeton"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-11 AA)', 'NA 005-07-11 Arbeitsausschuss "Bauausführungen"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-13 AA)', 'NA 005-07-13 Arbeitsausschuss "Zement"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-15 AA)', 'NA 005-07-15 Arbeitsausschuss "Gesteinskörnungen"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-17 AA)', 'NA 005-07-17 Arbeitsausschuss "Fasern für Beton"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-18 AA)', 'NA 005-07-18 Arbeitsausschuss "Tragschichtbinder"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-20 AA)', 'NA 005-07-20 Arbeitsausschuss "Betonbrücken"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-23 AA)', 'NA 005-07-23 Arbeitsausschuss "Betonzusatzmittel"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-24 AA)', 'NA 005-07-24 Arbeitsausschuss "Betonzusatzstoffe"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-27 AA)', 'NA 005-07-27 Arbeitsausschuss "Betonangreifende Stoffe (DIN 4030)"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07 FBR)', 'NA 005-07 Lenkungsgremium Fachbereich 07 - Beton- und Stahlbetonbau', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-08-99 AA)', 'NA 005-08-99 Arbeitsausschuss "Verbundbau"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-11-17 AA)', 'NA 005-11-17 Arbeitsausschuss "Abgasanlagen - Metall"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-11-39 AA)', 'NA 005-11-36 Arbeitsausschuss "Abgasanlagen aus Keramik und Beton"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-11-36 AA)', 'NA 005-11-39 Arbeitsausschuss "Abgasanlagen"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-11-95 AA)', 'NA 005-11-95 Arbeitsausschuss "Gärfuttersilos und Güllebehälter"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-51-01 AA)', 'NA 005-51-01 Arbeitsausschuss "Grundlagen für Entwurf, Berechnung und Bemessung von Tragwerken"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-51-02 AA)', 'NA 005-51-02 Arbeitsausschuss "Einwirkungen auf Bauten"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-51-07 AA)', 'NA 005-51-07 Arbeitsausschuss "Windenergieanlagen"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-52-22 AA)', 'NA 005-52-22 Arbeitsausschuss "Konstruktiver baulicher Brandschutz"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-53-01 GA)', 'NA 005-53-01 Gemeinschaftsarbeitsausschuss NABau/NAW "Boden und Grundwasser"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-53-02 GA)', 'NA 005-53-02 Gemeinschaftsarbeitsausschuss NABau/KRdL "Innenraumluft"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-53 FBR KOA 03)', 'NA 005-53 Fachbereichsbeirat KOA 03 "Hygiene, Gesundheit und Umweltschutz"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-55-71 AA)', 'NA 005-55-71 Arbeitsausschuss "Schallschutz im Hochbau"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-56-60 AA)', 'NA 005-56-60 Arbeitsausschuss "Wärmedämmstoffe"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-56-90 AA)', 'NA 005-56-90 Arbeitsausschuss "Baulicher Wärmeschutz im Hochbau"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-56-91 AA)', 'NA 005-56-91 Arbeitsausschuss "Wärmetransport"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-56-97 AA)', 'NA 005-56-97 Arbeitsausschuss "Transparente Bauteile"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-56-98 AA)', 'NA 005-56-98 Arbeitsausschuss "Wärmetechnisches Messen" (Obmann)', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-56-99 AA)', 'NA 005-56-99 Arbeitsausschuss "Feuchte"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-56 KOA06 GA)', 'NA 005-56 KOA06 Gemeinschaftsausschuss NABau/NHRs "Energetische Bewertung von Gebäuden" (Obmann)', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005 BR)', 'NA 005 Beirat des DIN-Normenausschusses Bauwesen', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('FES-AA (NA 021-00-03 AA)', 'NA 021-00-03 Arbeitsausschuss "Betonstahl und Spannstahl"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NAM (NA 060-13-07 AA)', 'NA 060-13-07 Arbeitsausschuss "Betontechnik"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NAM (NA 060-13-08 AA)', 'NA 060-13-08 Arbeitsausschuss "Betonpumpen"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NAM (NA 060-13-30 AA)', 'NA 060-13-30 Arbeitsausschuss "Bau- und Baustoffmaschinen"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NAM (NA 060-13-41 AA)', 'NA 060-13-41 Arbeitsausschuss "Maschinen und Ausrüstungen für Betonarbeiten"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NMP (NA 062-02-32 AA)', 'NA 062-02-31 Arbeitsausschus "Bauakustische Installationsmessungen"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NMP (NA 062-02-31 AA)', 'NA 062-02-31 Arbeitsausschuss "Schalldämmung und Schallabsorption, Messung und Bewertung"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NMP 062 AA (321 AA)', 'NA 062- Arbeitsausschuss "Prüfung der Zusammensetzung von erhärtetem Beton', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NAW (NA 110-01-02-05 UA)', 'NA 119-01-02-05 Unterausschuss "Elutionsverfahren"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NAGUS (NA 172-00-08 AA)', 'NA 172-00-08 Arbeitsausschuss "Management von Treibhausgasemissionen"', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau 005 Normenausschuss Bauwesen', 'NABau 005 Normenausschuss Bauwesen', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NMP 062', 'Normenausschuss Materialprüfung', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('NABau (NA 005-07-16 AA)', 'Umweltverträglichkeit von Beton', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)'),
('Lenkungskreis Infrastruktur', 'Lenkungskreis Infrastruktur', NULL, '<DVF>', 'Deutsches Verkehrsforum'),
('Beirat / Vorstand', 'Beirat / Vorstand', NULL, 'DVV', 'Deutsche Vereinigung für Verbrennungsforschung e.V. (DVV)'),
('Fachausschuss "Grundlagen und Anwendung"', 'Fachausschuss "Grundlagen und Anwendung"', NULL, 'DVV', 'Deutsche Vereinigung für Verbrennungsforschung e.V. (DVV)'),
('DWA AG IG-1.13 2 Abwasser aus Betrieben der Steine- und Erdenindustrie"', 'DWA AG IG-1.13 2 Abwasser aus Betrieben der Steine- und Erdenindustrie"', NULL, 'DWA', 'Deutsche Vereinigung für Wasserwirtschaft, Abwasser und Abfall e.V. (DWA)'),
('Referentenkreis', 'Referentenkreis', NULL, 'EID', 'Energieintensive Industrien in Deutschland (EID)'),
('AA Aus- und Weiterbildung', 'Arbeitsausschuss Aus- und Weiterbildung', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)'),
('AA Betonpumpen', 'Arbeitsausschuss Betonpumpen', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)'),
('AA Betontechnologie und Umwelt', 'Arbeitsausschuss Betontechnologie und Umwelt', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)'),
('AA Marketing', 'Arbeitsausschuss Marketing', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)'),
('AA Wirtschaftspolitik', 'Arbeitsausschuss Wirtschaftspolitik', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)'),
('AG Arbeitssicherheit', 'Arbeitsgruppe Arbeitssicherheit', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)'),
('AG Bauprodukte und Umwelt', 'Arbeitsgruppe Bauprodukte und Umwelt', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)'),
('AG Flüssigböden', 'Arbeitsgruppe Flüssigböden', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)'),
('AG Regelwerk für Beton', 'Arbeitsgruppe Regelwerk für Beton', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)'),
('Bearbeitergruppe "Drainbeton"', 'Bearbeitergruppe "Drainbeton"', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)'),
('Forschungsbeirat', 'Forschungsbeirat', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)'),
('7 LA', 'Asphaltbauweisen', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('7.01 GA', 'Asphalt, SpA TC 227/WG 1', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('8.2 AA', 'Baustoffe', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('7.4 AA', 'Bautechnologie', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('7.3 AA', 'Bauweisen', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('8 LA', 'Betonbauweisen', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('7.2 AA', 'Bindemittel', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('5.3 AA', 'Bodenbehandlung', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('5.5 AA', 'Boden- und Gewässerschutz', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('7.7 AA', 'Brückenbeläge', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('4.5 AA', 'Dimensionierung', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('5.2 AA', 'Entwässerung', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('5.01 GA', 'Erdarbeiten, SpA TC 396', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('5.1 AA', 'Erd- und Felsarbeiten', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('5 LA', 'Erd- und Grundbau', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('7.5 AA', 'Erhaltungstechnologie', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('8.5 AA', 'Erhaltungstechnologie', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('4.9 AA', 'Flugbetriebsflächen', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('5.4 AA', 'Geokunststoffe', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('6.1 AA', 'Gesteinskörnungen', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('6.01 GA', 'Gesteinskörnungen, SpA TC 154, SC 1 bis SC 5, WG 11, SpA TC 227/WG 4', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('6 LA', 'Gesteinskörnungen, Ungebundene Bauweisen', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('5.6 AA', 'Grundbau', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('4.01 ad', 'Hybridbauweisen', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('4 LA', 'Infrastrukturmanagement', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('8.3 AA', 'Konstruktion', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('LA 8.0 Betonstraßen', 'LA 8.0 Betonstraßen', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('6.5 AA', 'Ländliche Wege', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('4.1 AA', 'Management der Straßenerhaltung', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('8.01 GA', 'Materialien für Betonstraßen, SpA TC 227/WG 3', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('8.4 AA', 'Oberflächen', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('4.3 AA', 'Oberflächeneigenschaften', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('7.02 ad', 'Performance Asphalt', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('6.6 AA', 'Pflasterdecken und Plattenbeläge', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('5.7 AA', 'Prüftechnik', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('7.6 AA', 'Prüfverfahren', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('6.3 AA', 'Schichten ohne Bindemittel', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('5.8 AA', 'Straßenbau auf wenig tragfähigem Untergrund', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('4.4 AA', 'Substanzbewertung', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('7.1 AA', 'Technische Vertragsbedingungen', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('8.1 AA', 'Technische Vertragsbedingungen', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('6.2 AA', 'Umweltverträglichkeit, Industrielle Nebenprodukte und RC-Baustoffe', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('7.8 AA', 'Wiederverwertung von Asphalt', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('4.6 AA', 'Wirtschaftlichkeit von Bauweisen', NULL, 'FGSV', 'Forschungsgesellschaft für Strassen- und Verkehrswesen (FGSV)'),
('Fraunhofer-Allianz Bau', 'Fraunhofer-Allianz Bau', NULL, 'Fhg', 'Fraunhofer'),
('Fraunhofer-Zentrum "Bautechnik"', 'Fraunhofer-Zentrum "Bautechnik"', NULL, 'Fhg', 'Fraunhofer'),
('Fachausschuss "Zerkleinern und Klassieren"', 'Fachausschuss "Zerkleinern und Klassieren"', NULL, '<GesVT+CIW>', 'Gesellschaft für Verfahrenstechnik und Chemieingenieurwesen'),
('Hochtemperaturausschuss', 'Hochtemperaturausschuss', NULL, '<GesVT+CIW>', 'Gesellschaft für Verfahrenstechnik und Chemieingenieurwesen'),
('AK "ÖPP"', 'AK "ÖPP"', NULL, 'HDB', 'Hauptverband der deutschen Bauindustrie e.V. (HDB)'),
('Ausbildungsbeirat Beton-Straßenbau (B-StB)', 'Ausbildungsbeirat Beton-Straßenbau (B-StB)', NULL, 'HDB', 'Hauptverband der deutschen Bauindustrie e.V. (HDB)'),
('Bildungsbeirat B-StB-Schein', 'Bildungsbeirat B-StB-Schein', NULL, 'HDB', 'Hauptverband der deutschen Bauindustrie e.V. (HDB)'),
('IWM "Umwelteigenschaften mineralischer Mörtel"', 'IWM "Umwelteigenschaften mineralischer Mörtel"', NULL, 'IWM', 'Industrieverband WerkMörtel e.V. (IWM)'),
('AG "Hochbau"', 'AG "Hochbau"', NULL, 'IZB', 'Informationszentrum Beton GmbH'),
('AG "Technische Information"', 'AG "Technische Information"', NULL, 'IZB', 'Informationszentrum Beton GmbH'),
('AK Hochbau', 'AK Hochbau', NULL, 'IZB', 'InformationsZentrum Beton GmbH'),
('AK Infrastruktur', 'AK Infrastruktur', NULL, 'IZB', 'InformationsZentrum Beton GmbH'),
('AK "Marketing"', 'AK "Marketing"', NULL, 'IZB', 'Informationszentrum Beton GmbH'),
('AK Marktforschung', 'AK Marktforschung', NULL, 'IZB', 'InformationsZentrum Beton GmbH'),
('AK Technische Informationen', 'AK Technische Informationen', NULL, 'IZB', 'InformationsZentrum Beton GmbH'),
('Kuratorium', 'Kuratorium', NULL, 'IFB', 'Institut für Bauforschung e.V. (IFB)'),
('AK "Baustoffe"', 'AK "Baustoffe"', NULL, 'FEhS', 'Institut für Baustoff-Forschung e.V. (FEhS)'),
('Redaktionsbeirat der Zeitschrift "Straße und Autobahn"', 'Redaktionsbeirat der Zeitschrift "Straße und Autobahn"', NULL, '<Kirschbaum>', 'Kirschbaum Verlag'),
('Kuratorium BAU', 'Kuratorium BAU', NULL, '<MeMü>', 'Messe München'),
('Landesbeirat Immissionsschutz', 'Landesbeirat Immissionsschutz', NULL, '<MKlULNV NRW>', 'Ministerium für Klimaschutz, Umwelt, Landwirtschaft, Natur- und Verbraucherschutz NRW'),
('AG 2 "Produzierendes Gewerbe"', 'AG 2 "Produzierendes Gewerbe"', NULL, '<KSP-NRW>', 'NRW-Klimaschutzplan'),
('Beirat', 'RG Bau', NULL, 'RKW', 'RKW Kompetenzzentrum'),
('Weitere Gremien (Fachinstitut für Gebäude-klima e.V. (FGK)', 'Arbeitsgruppe Raumklima und Behaglichkeit', NULL, 'SONST', 'Sonstige'),
('bauforumstahl AA "Verbundbau"', 'bauforumstahl AA "Verbundbau"', NULL, 'SONST', 'Sonstige'),
('Weitere Gremien (Berufsgenossenschaft Rohstoffe und Chemische Industrie)', 'Beirat Steine und Erden', NULL, 'SONST', 'Sonstige'),
('Bildungsbeirat B-StB Schein', 'Bildungsbeirat B-StB Schein', NULL, 'SONST', 'Sonstige'),
('BTB/BÜV TB/DBV/GÜB-Gemeinschaftsarbeitskreis "Schnittstellenfragen", GÜB-Beirat', 'BTB/BÜV TB/DBV/GÜB-Gemeinschaftsarbeitskreis "Schnittstellenfragen", GÜB-Beirat', NULL, 'SONST', 'Sonstige'),
('BTB/DBV/BÜV TB/GÜB-Arbeitskreis Schnittstellenfragen', 'BTB/DBV/BÜV TB/GÜB-Arbeitskreis Schnittstellenfragen', NULL, 'SONST', 'Sonstige'),
('BTB/DBV/VDZ-Gemeinschaftsarbeitskreis "Beton"', 'BTB/DBV/VDZ-Gemeinschaftsarbeitskreis "Beton"', NULL, 'SONST', 'Sonstige'),
('BTB/GSV-Arbeitskreis Schnittstellenfragen', 'BTB/GSV-Arbeitskreis Schnittstellenfragen', NULL, 'SONST', 'Sonstige'),
-- ('Kurztitel Gremium', 'Langtitel Gremium', 'Beschreibung Gremium', 'Kurztitel Träger', 'Langtitel Träger'),
('Weitere Gremien', 'FDB/DBV-Gemeinschaftsarbeitskreis "Konstruktion"', NULL, 'SONST', 'Sonstige'),
-- ('Weitere Gremien', 'fib, TG 8.9 Sichtbeton', NULL, 'SONST', 'Sonstige'),
('FIEC-Tec 1 "Directives, Standards and Quality Assurance"', 'FIEC-Tec 1 "Directives, Standards and Quality Assurance"', NULL, 'SONST', 'Sonstige'),
('PRB-Lenkungsausschuss', 'PRB-Lenkungsausschuss', NULL, 'SONST', 'Sonstige'),
('Technischer Ausschuss des Hauptverbandes der Deutschen Bauindustrie e.V. (vormals HATECH)', 'Technischer Ausschuss des Hauptverbandes der Deutschen Bauindustrie e.V. (vormals HATECH)', NULL, 'SONST', 'Sonstige'),
('Technischer Kontaktausschuss BTB/VDZ', 'Technischer Kontaktausschuss BTB/VDZ', NULL, 'SONST', 'Sonstige'),
('VFBau "Verein zur Förderung der Normung im Bereich Bauwesen e.V.', 'VFBau "Verein zur Förderung der Normung im Bereich Bauwesen e.V.', NULL, 'SONST', 'Sonstige'),
-- ('Weitere Gremien (Berufsgenossenschaft Rohstoffe und Chemische Industrie)', 'Vorstand (Stellv.)', NULL, 'SONST', 'Sonstige'),
('Beirat im Lenkungsgremium', 'Beirat im Lenkungsgremium', NULL, '<SG UVA>', 'Studiengesellschaft für Unterirdische Verkehrsanlagen e.V.'),
('Beirat Stiftungsprofessur Clausthal', 'Beirat Stiftungsprofessur Clausthal', NULL, 'TUC', 'TU Clausthal'),
('Ausschuss zur gesundheitlichen Bewertung von Bauprodukten', 'AG Sensorik', NULL, 'UBA', 'Umweltbundesamt'),
('Kommission Innenraumluft-Hygiene', 'Unter-AK Schimmel', NULL, 'UBA', 'Umweltbundesamt'),
('Umweltausschuss ', 'Umweltausschuss ', NULL, '<U-NRW>', 'Unternehmer NRW'),
('AG "Messen von CO- und KW-Konzentrationen"', 'AG "Messen von CO- und KW-Konzentrationen"', NULL, 'VDI / DIN ', 'VDI / DIN '),
('AG "Messung von SO3 (E) / NH3 (E)', 'AG "Messung von SO3 (E) / NH3 (E)', NULL, 'VDI / DIN ', 'VDI / DIN '),
('Fachbeirat des Fachbereichs I "Umweltschutztechnik"', 'Fachbeirat des Fachbereichs I "Umweltschutztechnik"', NULL, 'VDI / DIN ', 'VDI / DIN '),
('Fachbeirat des Fachbereichs IV "Umweltmesstechnik"', 'Fachbeirat des Fachbereichs IV "Umweltmesstechnik"', NULL, 'VDI / DIN ', 'VDI / DIN '),
('Gesprächskreis "Qualität von Betonwaren"', 'Gesprächskreis "Qualität von Betonwaren"', NULL, 'VDZ-SLG', 'VDZ / SLG'),
('AK "Energieeffizienz"', 'AK "Energieeffizienz"', NULL, 'VIk', 'Verband der Industriellen Energie- und Kraftwirtschaft e.V. (VIK)'),
('Ausschuss "Klima"', 'Ausschuss "Klima"', NULL, 'VIk', 'Verband der Industriellen Energie- und Kraftwirtschaft e.V. (VIK)'),
('Normenausschuss, Kommission Reinhaltung der Luft (KRdL) im VDI und DIN', 'AG T35 "Olfaktorische Bewertung von Bauprodukten und Innenraumluft"', NULL, 'VDI', 'Verein Deutscher Ingenieure (VDI)'),
('Redaktionsbeirat "beton"', 'Redaktionsbeirat "beton"', NULL, 'VBT', 'Verlag Bau und Technik GmbH'),
('Bundesfachkomission Verkehr, Logistik, Infrastruktur', 'Bundesfachkomission Verkehr, Logistik, Infrastruktur', NULL, '<WR-CDU>', 'Wirtschaftsrat der CDU'),
('Referat 4 "Mauerwerk / Bauwerksabdichtng"', 'AG 4.12 "beseitigung von Schimmelpilzbefall in Innenräumen"', NULL, 'WTA', 'Wissenschaftlich-Technische Arbeitsgemeinschaft für Bauwerkserhaltung und Denkmalpflege e. V. (WTA)'),
-- ('Kurztitel Gremium', 'Langtitel Gremium', 'Beschreibung Gremium', 'Kurztitel Träger', 'Langtitel Träger'),
('Referat 6 "Bauphysik / Bauchemie"', 'AG 6.12 "Innendämmung im Bestand"', NULL, 'WTA', 'Wissenschaftlich-Technische Arbeitsgemeinschaft für Bauwerkserhaltung und Denkmalpflege e. V. (WTA)'),
-- ('Referat 6 "Bauphysik / Bauchemie"', 'AG "Fachwerkinstandsetzung nach WTA-Innendämmung"', NULL, 'WTA', 'Wissenschaftlich-Technische Arbeitsgemeinschaft für Bauwerkserhaltung und Denkmalpflege e. V. (WTA)'),
('Referat 8 "Fachwerk"', 'AG "Hydrophobierende Imprägnierung von Naturstein"', NULL, 'WTA', 'Wissenschaftlich-Technische Arbeitsgemeinschaft für Bauwerkserhaltung und Denkmalpflege e. V. (WTA)'),
-- ('Referat 6 "Bauphysik / Bauchemie"', 'AG "Hygrothermische Bemessung von Holzbaukonstruktionen"', NULL, 'WTA', 'Wissenschaftlich-Technische Arbeitsgemeinschaft für Bauwerkserhaltung und Denkmalpflege e. V. (WTA)'),
-- ('Referat 6 "Bauphysik / Bauchemie"', 'AG "Klima und Klimastabilität in historischen Räumen"', NULL, 'WTA', 'Wissenschaftlich-Technische Arbeitsgemeinschaft für Bauwerkserhaltung und Denkmalpflege e. V. (WTA)'),
-- ('Referat 8 "Fachwerk"', 'AG "Rechnerische Prognose des Schimmelpilzwachstumsrisikos"', NULL, 'WTA', 'Wissenschaftlich-Technische Arbeitsgemeinschaft für Bauwerkserhaltung und Denkmalpflege e. V. (WTA)'),
('Mitarbeit', 'Mitarbeit ', NULL, 'WTA', 'Wissenschaftlich-Technische Arbeitsgemeinschaft für Bauwerkserhaltung und Denkmalpflege e. V. (WTA)');
END;
