-- -*- coding: utf-8 -*- äöü
BEGIN TRANSACTION;
DELETE FROM witrabau.p2_committee;
INSERT INTO witrabau.p2_committee
   (committee_acronym,     --  'Kurztitel Gremium'
    committee_label,       --  'Langtitel Gremium'
    committee_description, --  'Beschreibung Gremium'
    institution_acronym,   --  'Kurztitel Träger'
    institution_label,     --  'Langtitel Träger'
    created_by)            --  nicht „- anonymous -“
VALUES
('AiF Gutachtergruppe 1 + 2', 'Gutachtergruppe 1 + 2 Forschungsanträge', 'Begutachtung von Forschungsanträgen', 'AiF', 'AiF - Arbeitsgemeinschaft industrieller Forschungsvereinigungen', '- setup -'),
('BAKA MKK', 'Projektgruppe Marketing- und Kommunikationskreis MKK', NULL, 'BAKA', 'Bundesverband Altbauerneuerung e.V. BAKA', '- setup -'),
('BASt AG 2.2', 'Arbeitsgruppe 2.2 „Betonbautechnik“', 'Betontechnische Fragestellungen der ZTV-ING', 'BASt', 'Bundesanstalt für Straßenwesen (BASt)', '- setup -'),
('BASt FE 06.0104/2013/CGB', 'Betreuungsausschuss FE 06.0104/2013/CGB', 'Vergleichbarkeit der Auslaugarten von Materialien im Originalzustand bzw. mit Sandzumischung nach dem Säulenkurzverfahren (DIN 19529)', 'BASt', 'Bundesanstalt für Straßenwesen (BASt)', '- setup -'),
('BASt FE 08.0218/2012/IGB', 'FE 08.0218/2012/IGB „Instandsetzung von Betondecken mit dünnschichtigem Neubeton“', 'Forschungsvorhaben: Instandsetzung von Betondecken mit dünnschichtigem Neubeton', 'BASt', 'Bundesanstalt für Straßenwesen (BASt)', '- setup -'),
('BASt FE 08.0219/2012/IGB', 'FE 08.0219/2012/IGB „Grindingtexturierte Waschbetondecken“', 'Forschungsvorhaben: Grindingtexturierte Waschbetondecken (Beurteilung vorhandener Betonoberflächenauf ihre Dauerhaftigkeit)', 'BASt', 'Bundesanstalt für Straßenwesen (BASt)', '- setup -'),
('BASt FE 09.0170/2011/ARB', 'FE 09.0170/2011/ARB „Integrale Betrachtung der Eigenschaften von Fahrbahnoberflächen“', 'Forschungsvorhaben: Integrale Betrachtung der Eigenschaften von Fahrbahnoberflächen sowie Beurteilung vorhandener Betonoberflächen', 'BASt', 'Bundesanstalt für Straßenwesen (BASt)', '- setup -'),
('BASt FE 15.0604/2014/DRB', 'FE 15.0604/2014/DRB', 'Frost-Tausalz-Widerstand mit dem CDF-Verfahren XF2 nach BASt-Prüfvorschriften', 'BASt', 'Bundesanstalt für Straßenwesen (BASt)', '- setup -'),
('BASt FE „Drainbeton“', 'FE „Drainbeton“', 'Versuchsprogramm BASt zur Lärmminderung Betonfahrbahndecken (OPB)', 'BASt', 'Bundesanstalt für Straßenwesen (BASt)', '- setup -'),
('bauforumstahl AA „Verbundbau“', 'bauforumstahl AA „Verbundbau“', NULL, 'SONST', 'Sonstige', '- setup -'),
('BBS AA Marktforschung und Statistik', 'Arbeitsausschuss „Marktforschung und Statistik“', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS AA Öffentlichkeitsarbeit', 'Arbeitsausschuss „Öffentlichkeitsarbeit“', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS AA Verkehr und Logistik', 'Arbeitsausschuss „Verkehr und Logistik“', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS Ausschuss „Bauwirtschaft und Logistik“', 'Ausschuss „Bauwirtschaft und Logistik“', 'Baustoffübergreifende Positionsentwicklung zu nachfragerelevanten Themen und Logistikfragen', 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS Ausschuss „Energie“', 'Ausschuss „Energie“', 'Baustoffübergreifende Fragen im Energiebereich', 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS Ausschuss „Recht“', 'Ausschuss „Recht“', 'Baustoffübergreifende Fragen zur aktuellen rechtslage mit dem Ziel der Rechtssicherheit', 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS Ausschuss „Rohstoffe“', 'Ausschuss „Rohstoffe“', 'Rohstoffsicherung, Rohstoffpolitik, Ressourceneffizienz', 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS Ausschuss „Steuern“', 'Ausschuss „Steuern“', 'Baustoffübergreifende Fragen zur aktuellen Steuerpolitik', 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS Ausschuss „Technik und Normung“', 'Ausschuss „Technik und Normung“', 'Baustoffübergreifende Fragen CPD/CPR, Akkreditierung, Umweltverträglichkeit, Radioaktivität, Ersatzbaustoffverordnung', 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS Ausschuss „Umwelt“', 'Ausschuss „Umwelt“', 'Baustoffübergreifende umweltpolitische Aktivitäten', 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS GF', 'Geschäftsführerkreis', 'Baustoffübergreifende Fragestellungen', 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS PG „Arbeitsschutz Gefahrstoffe“', 'Projektgruppe „Arbeitsschutz Gefahrstoffe“', 'Chemikalien und Gefahrstoffrecht', 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS PG „Energieeffiziente Gebäude“', 'Projektgruppe „Energieeffiziente Gebäude“', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS PG „Nachhaltigkeit / EPD / Dauerhaftigkeit“', 'Projektgruppe „Nachhaltigkeit / EPD / Dauerhaftigkeit“', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS PG „Nachhaltigkeit“', 'Projektgruppe „Nachhaltigkeit“', 'Nachhaltigkeit und mögliche Auswirkungen auf die Bauwirtschaft', 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS PG „Radioaktivität aus Bauprodukten“', 'Projektgruppe „Radioaktivität aus Bauprodukten“', 'Messung der Radioaktivität von Baustoffen durch das Bundesamt für Strahlenschutz, Vorarbeiten für eine europäische WT/WTF Einstufung', 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS PG „REACH / Bauproduktenrichtlinie“', 'Projektgruppe „REACH / Bauproduktenrichtlinie“', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS PG „Ressourceneffizienz“', 'Projektgruppe „Ressourceneffizienz“', 'Begleitung der Diskussion zur Steigerung der Ressourceneffizienz (ProgRess)', 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS PG „Wasser, Boden, Abfall“', 'Projektgruppe „Wasser, Boden, Abfall“', 'Ersatzbaustoffverordnung, Grundwasserverordnung, Bodenschutzverordnung, TC 351 „Dangerous Substances“', 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBS PG „Wasser / Boden / Abfall“', 'Projektgruppe „Wasser / Boden / Abfall“', NULL, 'BBS', 'Bundesverband Baustoffe -  Steine und Erden e.V. (BBS)', '- setup -'),
('BBSR Ressourceneffizienz im Bauwesen', 'Runder Tisch Ressourceneffizienz im Bauwesen', 'Entwicklung von Ressourceneffizienzindikatoren', 'bbsr', 'Bundesinstitut für Bau-, Stadt- und Raumforschung', '- setup -'),
('BDI AK „Energiesteuern“', 'Arbeitskreis „Energiesteuern“', 'Energie- und Stromsteuerrecht; Fortsetzung Ökosteuer-Spitzenausgleich ab 2013', 'BDI', 'Bundesverband der Deutschen Industrie e.V. (BDI)', '- setup -'),
('BDI AK „Immissionsschutz“', 'Arbeitskreis „Immissionsschutz“', 'Immissionsschutz, TA-Luft-Novelierung, Auswirkungender IED im deutschen Recht', 'BDI', 'Bundesverband der Deutschen Industrie e.V. (BDI)', '- setup -'),
('BDI AK „Stoffpolitik“', 'Arbeitskreis „Stoffpolitik“', 'Chemikalien und Gefahrstoffrecht', 'BDI', 'Bundesverband der Deutschen Industrie e.V. (BDI)', '- setup -'),
('BDI Ausschuss „Energie- und Klimapolitik“', 'Ausschuss „Energie- und Klimapolitik“', 'Gemeinsame Aktivitäten innerhalb der deutschen Industrie; u.a. Erneuerbare-Energien-Gesetz (EEG)', 'BDI', 'Bundesverband der Deutschen Industrie e.V. (BDI)', '- setup -'),
('BDI PG „ETS-post-2020“', 'Projektgruppe „ETS-post-2020“', 'Diskussion zur Gestaltung des EU Emissionshandels nach 2020', 'BDI', 'Bundesverband der Deutschen Industrie e.V. (BDI)', '- setup -'),
('BDI PG „Kreislaufwirtschaft“ einschl. AK Wertstoffgesetz', 'Projektgruppe „Kreislaufwirtschaft“ einschl. AK Wertstoffgesetz', 'Industriepolitische Fragen im Bereich Abfallwirtschaft', 'BDI', 'Bundesverband der Deutschen Industrie e.V. (BDI)', '- setup -'),
('BDI UA 1 „Betrieblicher Umweltschutz“', 'Unterausschuss 1 „Betrieblicher Umweltschutz“', 'Nationale Umweltpolitik, Umsetzung IED in deutsches Recht', 'BDI', 'Bundesverband der Deutschen Industrie e.V. (BDI)', '- setup -'),
('BDI UA „Klimapolitik“', 'Unterausschuss „Klimapolitik“', 'Gemeinsame Aktivitäten innerhalb der deutschen Industrie; u.a. EU-Emissionshandel, Strompreiskompensation', 'BDI', 'Bundesverband der Deutschen Industrie e.V. (BDI)', '- setup -'),
('BEB AK „Betonböden“', 'Arbeitskreis „Betonböden“', 'Forschungsvorhaben / Merkblätter zu Bauweisen von Industrieböden', 'BEB', 'Bundesverband Estrich und Belag e.V. (BEB)', '- setup -'),
('BEB AK „CEM II in Estrichen“', 'Arbeitskreis „CEM II in Estrichen“', 'Leitfaden und Forschung zu Trockenestrichen; Anwendung von CEM II im Estrichbereich', 'BEB', 'Bundesverband Estrich und Belag e.V. (BEB)', '- setup -'),
('BEB AK „Zementgebundene Industrie-Estriche“', 'Arbeitskreis „Zementgebundene Industrie-Estriche“', 'Forschungsvorhaben / Merkblätter zu Bauweisen von Estrichen', 'BEB', 'Bundesverband Estrich und Belag e.V. (BEB)', '- setup -'),
('Beirat Steine und Erden', 'Beirat Steine und Erden', 'Weitere Gremien (Berufsgenossenschaft Rohstoffe und Chemische Industrie)', 'SONST', 'Sonstige', '- setup -'),
('BG Bau „Gefahrstoff-Kommunikation“', 'Lenkungsausschuss zur Branchenregelung „Gefahrstoff-Kommunikation in der Lieferkette der Bauwirtschaft“', 'Kommunikation von Sicherheitsdatenblättern in der Bauwirtschaft', 'BG Bau', 'Berufsgenossenschaft der Bauwirtschaft (BG Bau)', '- setup -'),
('Bildungsbeirat B-StB Schein', 'Bildungsbeirat B-StB Schein', NULL, 'SONST', 'Sonstige', '- setup -'),
('BMUB EG-Harmonisierung im Bauwesen', 'EG-Harmonisierung im Bauwesen', NULL, 'BMUB', 'Bundesministerium für Umwelt, Natur, Bau und Reaktorsicherheit (BMUB)', '- setup -'),
('BMUB Vorbereitender Ausschuss', 'Vorbereitender Ausschuss', NULL, 'BMUB', 'Bundesministerium für Umwelt, Natur, Bau und Reaktorsicherheit (BMUB)', '- setup -'),
('BMVBS Bauproduktenrecht', 'Bauproduktenrecht', 'Vorbereitung der Sitzungen des Ständigen Ausschusses, zuletzt der Bauproduktenverordnung', 'BMVBS', 'Bundesministerium für Verkehr, Bau und Stadtentwicklung (BMVBS)', '- setup -'),
('BMVBS LA „PPP im öffentlichen Hochbau“', 'Lenkungsausschuss „PPP im öffentlichen Hochbau“', 'Positionierung der Zementindustrie zu verkehrspolitischen Fragestellungen', 'BMVBS', 'Bundesministerium für Verkehr, Bau und Stadtentwicklung (BMVBS)', '- setup -'),
('BMVBS „Nachhaltiges Bauen“', 'Runder Tisch „Nachhaltiges Bauen“', 'Positionierung der Zementindustrie bei der politischen und normativen Entwicklung im Bereich Nachhaltiges Bauen', 'BMVBS', 'Bundesministerium für Verkehr, Bau und Stadtentwicklung (BMVBS)', '- setup -'),
('BMWI Energie in Gebäuden und Quartieren ', 'Forschungsnetzwerk Energie in Gebäuden und Quartieren ', NULL, 'BMWI', 'Bundesministerium für Wirtschaft und Energie', '- setup -'),
('BSS Wissenschaftlicher Beirat', 'Wissenschaftlicher Beirat', NULL, 'BSS e.V.', 'Bundesverband Schimmelpilz-Sanierung e.V.', '- setup -'),
('BTB/GSV-AK Schnittstellenfragen', 'BTB/GSV-Arbeitskreis Schnittstellenfragen', NULL, 'SONST', 'Sonstige', '- setup -'),
('BTB/VDZ Technischer Kontaktarbeitskreis', 'Technischer Kontaktarbeitskreis', 'Schnittstellenfragen Baustoff (Zement, Transportbeton)', 'BTB / VDZ', 'BTB / VDZ', '- setup -'),
('BV Kalk „Klima und Energie“', 'Ausschuss „Klima und Energie“', 'Energie- und Klimapolitik, CO2-Emissionshandel', 'BV Kalk', 'Bundesverband der Deutschen Kalkindustrie e.V. (BV Kalk)', '- setup -'),
('BWK BW Vorstand', 'Mitglied des Vorstands', NULL, 'BWK BW', 'Bund der Ingenieure für Wasserwirtschaft, Abfallwirtschaft und Kulturbau- Landesverband Baden-Würtemberg', '- setup -'),
('C³ Konsortium', 'C³ Konsortium', 'Erforschung des Verbundbaustoffes Carbonbeton', 'C³ e. V.', 'C³ - Carbon Concrete Composite e.V.', '- setup -'),
('CDU Verkehr, Logistik, Infrastruktur', 'Bundesfachkomission Verkehr, Logistik, Infrastruktur', 'Positionsentwicklung zu aktuellen verkehrspolitischen Schwerpunktthemen', 'WR CDU', 'Wirtschaftsrat der CDU', '- setup -'),
('DAfStb AG Dauerhaftigkeit', 'Arbeitsgruppe  Dauerhaftigkeitsbemessung (TA BT)', 'Spiegelung CEN/TC 104/SC 1  Dauerhaftigkeitsbemessung', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb AG Ermüdung', 'Arbeitsgruppe Ermüdung (TA BEW)', 'Ableitung von Werkstoffkenngrößen für die Ermüdungsfestigkeit', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb AG Praxisfrost', 'Arbeitsgruppe Übertragbarkeit von Frost-Laborversuchen auf Praxisverhältnisse (TA BT)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb AG Sulfatwiderstand', 'Arbeitsgruppe Sulfatwiderstand (TA BT)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb AG VB/VM', 'Arbeitsgruppe Vergussbeton/Vergussmörtel (TA BT)', 'Richtlinie Vergussbeton/ Vergussmörtel', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb AG Verbund', 'Arbeitsgruppe Verbundprüfung (TA BEW)', 'Prüfverfahren zur Verbundprüfung von Betonstahl', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb AHG Parkdecks', 'Ad-hoc-Gruppe Dauerhaftigkeit von befahrenen Parkdecks', 'Entwicklung eines geschlossenen Regelungsrahmens', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb AK Ausführung', 'Arbeitskreis Ausführung (TA SIB)', 'Überarbeitung Teil 3 der RL-SIB', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb AK Belastungsversuche', 'Arbeitskreis Belastungsversuche an Betonbauwerken (TA BK)', 'Überarbeitung der RL „Belastungsversuche an Betonbauwerken“', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb AK KKS', 'Arbeitskreis Kathodischer Korrosionsschutz (TA SIB)', 'Regelungen für KKS in der neuen Instandhaltungsrichtlinie (RL-SIB)', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb AK Mörtel', 'Arbeitskreis Mörtel (TA SIB)', 'Überarbeitung Teile 2 und 4 der RL-SIB', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb AK Oberflächenschutzsysteme', 'Arbeitskreis Oberflächenschutzsysteme (TA SIB)', 'Überarbeitung Teile 2 und 4 der RL-SIB', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb AK Planung', 'Arbeitskreis Planung (TA SIB)', 'Überarbeitung Teil 1 der RL-SIB', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb AK Rissfüllstoffe', 'Arbeitskreis Rissfüllstoffe (TA SIB)', 'Überarbeitung Teile 2 und 4 der RL-SIB', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb Forschungsbeirat', 'Forschungsbeirat', 'Beratung über Forschungsprojekten im Betonbau', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb TA BAU', 'Technischer Ausschuss Bauausführung', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb TA BBR', 'Technischer Ausschuss Betonbrücken', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb TA BEW', 'Technischer Ausschuss Bewehrung', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb TA BK', 'Technischer Ausschuss Bemessung und Konstruktion', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb TA BT', 'Technischer Ausschuss Betontechnik', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb TA SIB', 'Technischer Ausschuss Schutz und Instandsetzung von Betonbauteilen', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb TA Umwelt', 'Technischer Ausschuss Umwelt', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb UA AKR', 'Unterausschuss  Alkalikieselsäurereaktion (AKR1: Prüfverfahren; AKR2: Instandsetzung; AKR3: Richtlinie, TA BT)', 'Beurteilung von Schäden  durch AKR; RL Alkalireaktion in Beton', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb UA BBUmwS', 'Unterausschuss Betonbau beim Umgang mit wassergefährdenden Stoffen', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb UA Befestigungstechnik', 'Unterausschuss Befestigungstechnik (TA BK, TA BEW)', 'Anwendungshilfen;  Überarbeitung CEN/TS 1992-4', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb UA Bewertung von Bestandsbauwerken', 'Unterausschuss Bewertung von Bestandsbauwerken (TA BK)', 'Sachstandbericht „Mechanische Kennwerte historischer Betone, Betonstähle und Spannstähle“; Spiegelung von CEN/TC 250/SC2/ WG1/TG3 „Existing concrete structures“', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb UA Brand', 'Unterausschuss Heißbemessung im Betonbau (TA BK)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb UA MB', 'Unterausschuss Massige Bauteile aus Beton (TA BT)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb UA NBB', 'Unterausschuss Nachhaltig Bauen mit Beton (AG 0 NBB Arbeitsgruppe Grundsätze des nachhaltigen Bauens mit Beton, TA Umwelt)', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb UA NB', 'Unterausschuss Nachbehandlung von Beton (TA BAU)', 'Entwicklung von Nachbehandlungsregeln für Beton', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb UA Rezyklierte Gesteinskörnungen', 'Unterausschuss Herstellung von Beton unter Verwendung von rezyklierten Gesteinskörnungen', NULL, 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb UA SFB', 'Unterausschuss Stahlfaserbeton (TA BK)', 'Richtlinie Stahlfaserbeton; Spiegelung von CEN/TC250/SC2/WG1/TG2 „Fibre concrete“', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb UA SVB', 'Unterausschuss Selbstverdichtender Beton (TA BK)', 'Richtlinie Selbstverdichtender Beton', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb UA Trockenbeton', 'Unterausschuss Trockenbeton (TA BT)', 'Richtlinie Trockenbeton', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb UA UHFB', 'Unterausschuss  Ultrahochfester Beton (AG 1: Betontechnik und Ausführung; AG 2: Bemessung und Konstruktion, TA BT) ', 'Entwicklung einer Richtlinie; Beton- und ausführungstechnische Anforderungen an UHFB; Bemessungsverfahren und Konstruktionsregeln für UHFB', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb UA Verstärken ', 'Unterausschuss Verstärken von Betonbauteilen (TA BK)', 'Richtlinie Verstärken von Betonbauteilen mit geklebter Bewehrung; Spiegelung von CEN/TC250/SC2/TG1/WG1 „Strenthening of concrete structures“', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb UA VZ', 'Unterausschuss Verzögerter Beton (TA BT)', 'Richtlinie Verzögerter Beton', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DAfStb UA WU', 'Unterausschuss Wasserundurchlässige Bauwerke aus Beton (TA BT)', 'Überarbeitung Richtlinie Wasserundurchlässige Bauwerke aus Beton; Erläuterungen', 'DAfStb', 'Deutscher Ausschuss für Stahlbeton e.V. (DAfStb)', '- setup -'),
('DakkS Sektorkomitee Emissionshandel', 'Sektorkomitee Emissionshandel', 'Relevante Regeln für Prüfstellen und Verifizierungsstellen für den gesetzlich geregelten und nicht geregelten, freiwilligen Bereich', 'Dakks', 'DakkS -  Deutsche Akkreditierungsstelle GmbH', '- setup -'),
('DBC AK 2.1 „Beton- und Mörtelzusatzmittel und Umwelt“', 'Arbeitskreis 2.1 „Beton- und Mörtelzusatzmittel und Umwelt“', 'Ausarbeitung und Überarbeitung von Sachstandberichten zu Betonzusatzmitteln', 'DBC', 'Deutsche Bauchemie e.V.', '- setup -'),
('DBV AK Betonieren im Winter', 'AK Betonieren im Winter', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV Ausbildungsbeirat Beton', 'Ausbildungsbeirat Beton', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV Ausbildungsbeirat SIB', 'Ausbildungsbeirat Schutz und Instandsetzung im Betonbau', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HABA-AK Anwendung zfP im Bauwesen ', 'HABA-Arbeitskreis Anwendung zerstörungsfreier Prüfverfahren im Bauwesen ', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HABA-AK Betonkosmetik', 'HABA-Arbeitskreis Betonkosmetik', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HABA-AK Industrieböden', 'HABA-Arbeitskreis Industrieböden', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HABA-AK Instandsetzung', 'HABA-Arbeitskreis Instandsetzung', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HABA-AK Qualität der Planung', 'HABA-Arbeitskreis Qualität der Planung', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HABA-AK WU-Dächer', 'HABA-Arbeitskreis WU-Dächer', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HABA', 'Hauptausschuss Bauausführung', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HAB-AK Brückenbau', 'HAB-Arbeitskreis Brückenbau (Gruppe 1: Monitoring; Gruppe 2: Verfahren, Gruppe 3: Konstruktionen) ', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HAB-AK Parkhäuser und Tiefgaragen', 'HAB-Arbeitskreis Parkhäuser und Tiefgaragen', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HAB-AK Pflichtenheft Tragwerksplanung', 'HAB-Arbeitskreis Pflichtenheft Tragwerksplanung', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HAB-AK Rissbildung', 'HAB-Arbeitskreis Rissbildung', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HAB-AK Software für Baustatik', 'HAB-Arbeitskreis Software für Baustatik', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HAB-AK Teilsicherheitsbeiwerte beim Bauen im Bestand', 'HAB-Arbeitskreis Teilsicherheitsbeiwerte beim Bauen im Bestand', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HAB', 'Hauptausschuss Bautechnik ', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HABT-AK Bewertung der In-situ-Druckfestigkeit von Beton', 'HABT-Arbeitskreis Bewertung der In-situ-Druckfestigkeit von Beton', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HABT-AK Brückenkappen', 'HABT-Arbeitskreis Brückenkappen', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HABT-AK Chemischer Angriff', 'HABT-Arbeitskreis Chemischer Angriff', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HABT-AK Sichtbeton', 'HABT-Arbeitskreis Sichtbeton', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HABT-AK Stahlfaserbeton', 'HABT-Arbeitskreis Stahlfaserbeton', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HABT-AK Überarbeitung EN 206', 'HABT-Arbeitskreis Überarbeitung EN 206', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HABT-AK Zukünftige Qualitätssicherung im Betonbau', 'HABT-Arbeitskreis Zukünftige Qualitätssicherung im Betonbau', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HABT', 'Hauptausschuss Baustofftechnik', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DBV HAF', 'Hauptausschuss Forschung', NULL, 'DBV', 'Deutscher Beton- und Bautechnik-Verein e.V. (DBV)', '- setup -'),
('DGNB Bauproduktebeirat', 'Bauproduktebeirat', 'Einfluss von Bauprodukten auf die Nachhaltigkeitsbewertung', 'DGNB', 'Deutsche gesellschaft für Nachhaltiges Bauen e.V. (DGNB)', '- setup -'),
('DGNB Expertengruppe Ökobilanzierung', 'Expertengruppe Ökobilanzierung', NULL, 'DGNB', 'Deutsche Gesellschaft für Nachhaltiges Bauen e.V. (DGNB)', '- setup -'),
('DGNB-Fachausschuss', 'DGNB-Fachausschuss', NULL, 'DGNB', 'Deutsche Gesellschaft für Nachhaltiges Bauen e.V. (DGNB)', '- setup -'),
('DGZfP UA Feuchte', 'Fachausschuss Bauwesen / Unterausschuss Feuchte', 'Erstellung von Merkblättern zur Feuchtemessung im Bauwesen', 'DGZfP', 'Deutsche Gesellschaft für zerstörungsfreie Prüfungen e.V. (DGZfP)', '- setup -'),
('DGZfP UA Korrosionsnachweis', 'Fachausschuss Bauwesen / Unterausschuss Korrosionsnachweis', 'Erstellung von Merkblättern zum Nachweis von Korrosion an Betonstahl', 'DGZfP', 'Deutsche Gesellschaft für zerstörungsfreie Prüfungen e.V. (DGZfP)', '- setup -'),
('DGZfP UA LIBS', 'Fachausschuss Bauwesen / Unterausschuss LIBS', 'Erstellung von Merkblättern und Prüfbeschreibungen zu LIBS', 'DGZfP', 'Deutsche Gesellschaft für zerstörungsfreie Prüfungen e.V. (DGZfP)', '- setup -'),
('DIBt Ad-hoc-Ausschuss Lastabtragende Wärmedämmung', 'Ad-hoc-Ausschuss Lastabtragende Wärmedämmung größerer Dicke unter Gründungsplatten', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt Ad-hoc-Ausschuss Nachhaltigkeit', 'Ad-hoc-Ausschuss Nachhaltigkeit von Bauprodukten im Zulassungsbereich', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt Niederschlagsabflüsse A', 'Niederschlagsabflüsse A', 'Zulassung der Produkte', 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-PG Analytik', 'DIBt-Projektgruppe Analytik', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-PG „Beton und zementgebundene Baustoffe“', 'DIBt-Projektgruppe „Beton und zementgebundene Baustoffe“', 'Bearbeitung des speziellen Teils der DIBt-Grundsätze für Beton', 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-PG „Instandsetzungssysteme für Beton“ (Obmann)', 'DIBt-Projektgruppe „Instandsetzungssysteme für Beton“ (Obmann)', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-PG „Prüf- und Messverfahren“', 'DIBt-Projektgruppe „Prüf- und Messverfahren zur gesundheitlichen Bewertung von Bauprodukten, Sportbodenbeläge“', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-PG „Reaktive Brandschutzbeschichtungen“', 'DIBt-Projektgruppe „Reaktive Brandschutzbeschichtungen aus Sicht des Gesundheitsschutzes“', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-PG „Sulfatwiderstandsprüfung“', 'DIBt-Projektgruppe „Sulfatwiderstandsprüfung“', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-PG „Verstärken von Betonbauteilen mit Textilbeton“', 'DIBt-Projektgruppe „Verstärken von Betonbauteilen mit Textilbeton“', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Abgasanlagen“', 'DIBt-Sachverständigenausschuss „Abgasanlagen“', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt SVA-AG Modellierung Dach und Fassade', 'Arbeitsgruppe Modellierung Dach und Fassade', 'Bewertung der Auslaugung aus beregneten Bauteilen', 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Außenliegende Wärmedämmung“', 'DIBt-Sachverständigenausschuss „Außenliegende Wärmedämmung“', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Beton, Stahlbeton und Spannbetonbauteile“ A und B1', 'DIBt-Sachverständigenausschuss „Beton, Stahlbeton und Spannbetonbauteile“ A und B1', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Betonstähle“ A und B1', 'DIBt-Sachverständigenausschuss „Betonstähle“ A und B1', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Betontechnologie“ A', 'DIBt-Sachverständigenausschuss „Betontechnologie“ A - Grundsatzfragen', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Betontechnologie“ B1', 'DIBt-Sachverständigenausschuss „Betontechnologie“ B1 - Bindemittel', 'Zulassungen Zemente', 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Betontechnologie“ B3', 'DIBt-Sachverständigenausschuss „Betontechnologie“ B3 - Betonzusatzstoffe', 'Zulassungen Betonzusatzstoffe', 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Betontechnologie“ B4 - Betonzuschläge', 'DIBt-Sachverständigenausschuss „Betontechnologie“ B4 - Betonzuschläge', 'Zulassungen Beton', 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Betontechnologie“ B5', 'DIBt-Sachverständigenausschuss „Betontechnologie“ B5 -  Sonderbetone und Sondermörtel', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Bewehrungselemente“ B3', 'DIBt-Sachverständigenausschuss „Bewehrungselemente“ B3', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Feuerungsanlagen“', 'DIBt-Sachverständigenausschuss „Feuerungsanlagen“', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Gesundheits- und Umweltschutz“', 'DIBt-Sachverständigenausschuss „Gesundheits- und Umweltschutz“', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA-PG „Beregnete Bauteile“', 'DIBt-Projektgruppe „Beregnete Bauteile“', 'Prüfverfahren für beregnete Bauteile', 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA-PG „Boden- und Grundwassergefährdung durch Baustoffe“', 'DIBt-Projektgruppe „Boden- und Grundwassergefährdung durch Baustoffe“', 'Bearbeitung der DIBt-Grundsätze', 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Platten und Querkraftanschlüsse“ A und B', 'DIBt-Sachverständigenausschuss „Platten und Querkraftanschlüsse“ A und B', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA Schalldämmung und Schalldämmstoffe', 'DIBt-Sachverständigenausschuss „Schalldämmung und Schalldämmstoffe“', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Spannbetonhohlplatten“ B2', 'DIBt-Sachverständigenausschuss „Spannbetonhohlplatten“ B2', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Spannstähle“ A und B1', 'DIBt-Sachverständigenausschuss „Spannstähle“ A und B1', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Spannverfahren“ A und B1', 'DIBt-Sachverständigenausschuss „Spannverfahren“ A und B1', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Stahlfaserbeton“ A und B', 'DIBt-Sachverständigenausschuss „Stahlfaserbeton“ A und B', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA Umwelt A', 'DIBt-Sachverständigenausschuss „Umwelt A“', 'Übergeordnete Fragen zur Umweltverträglichkeit von Bauprodukten', 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Verbundbau“ B2', 'DIBt-Sachverständigenausschuss „Verbundbau“ B2', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Verstärken“ A und B1', 'DIBt-Sachverständigenausschuss „Verstärken von Betonbauteilen“ A und B1', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIBt-SVA „Wärme- und Schallschutz“', 'DIBt-Sachverständigenausschuss „Baustoffe und Bauarten für Wärme- und Schallschutz“', NULL, 'DIBt', 'Deutsches Institut für Bautechnik (DIBt)', '- setup -'),
('DIN AA Werkstoffe und Bauteile im Kontakt mit Trinkwasser', 'AA Werkstoffe und Bauteile im Kontakt mit Trinkwasser', 'Spiegelgremium zur CEN/TC 164/WG3 „Materials and products in contact with drinking water“', 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('DVF Lenkungskreis Infrastruktur', 'Lenkungskreis Infrastruktur', 'Positionierung der Zementindustrie zu verkehrspolitischen Fragestellungen', 'Verkehrsforum', 'Deutsches Verkehrsforum', '- setup -'),
('DVV Beirat / Vorstand', 'Beirat / Vorstand', 'Forschungssteuerung und -mittelakquisition im Bereich Feuerungstechnik/Verbrennung', 'DVV', 'Deutsche Vereinigung für Verbrennungsforschung e.V. (DVV)', '- setup -'),
('DVV FA „Grundlagen und Anwendung“', 'Fachausschuss „Grundlagen und Anwendung“', 'Informationsaustausch mit anderen Branchen/Wissenschaft zu Feuerungstechnik/Verbrennung', 'DVV', 'Deutsche Vereinigung für Verbrennungsforschung e.V. (DVV)', '- setup -'),
('DWA AG IG-1.13 2 „Abwasser der Steine- und Erdenindustrie“', 'DWA AG IG-1.13 2 „Abwasser aus Betrieben der Steine- und Erdenindustrie“', 'DWA-Merkblätter zur Behandlung von Abfall und Abwasser in Zement- und Betonwerken', 'DWA', 'Deutsche Vereinigung für Wasserwirtschaft, Abwasser und Abfall e.V. (DWA)', '- setup -'),
('EID Referentenkreis', 'Referentenkreis', 'Positionen und Aktivitäten der energieintensiven Industrien in den Bereichen Energie und Klimapolitik', 'EID', 'Energieintensive Industrien in Deutschland (EID)', '- setup -'),
('FEhS AK „Baustoffe“', 'AK „Baustoffe“', 'Themen zur Verwendung von Hüttensand', 'FEhS', 'Institut für Baustoff-Forschung e.V. (FEhS)', '- setup -'),
('FES-AA (NA 021-00-03 AA)', 'NA 021-00-03 Arbeitsausschuss „Betonstahl und Spannstahl“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('FGSV 4.01 ad', 'Hybridbauweisen', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 4.1 AA', 'Management der Straßenerhaltung', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 4.3 AA', 'Oberflächeneigenschaften', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 4.4 AA', 'Substanzbewertung', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 4.5 AA', 'Dimensionierung', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 4.6 AA', 'Wirtschaftlichkeit von Bauweisen', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 4 LA', 'Infrastrukturmanagement', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 5.4 AA ', 'Geokunststoffe', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 5.8 AA ', 'Straßenbau auf wenig tragfähigem Untergrund', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 5 LA', 'Erd- und Grundbau', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 6.01 GA', 'Gesteinskörnungen, SpA TC 154, SC 1 bis SC 5, WG 11, SpA TC 227/WG 4', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 6.1 AA', 'Gesteinskörnungen', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 6.2 AA', 'Umweltverträglichkeit, Industrielle Nebenprodukte und RC-Baustoffe', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 6.3 AA', 'Schichten ohne Bindemittel', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 6.6 AA', 'Pflasterdecken und Plattenbeläge', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 6 LA', 'Gesteinskörnungen, Ungebundene Bauweisen', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 7.01 GA', 'Asphalt, SpA TC 227/WG 1', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 7.02 ad', 'Performance Asphalt', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 7.1 AA', 'Technische Vertragsbedingungen', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 7.2 AA', 'Bindemittel', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 7.3 AA', 'Bauweisen', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 7.4 AA', 'Bautechnologie', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 7.5 AA', 'Erhaltungstechnologie', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 7.6 AA', 'Prüfverfahren', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 7.7 AA', 'Brückenbeläge', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 7.8 AA', 'Wiederverwertung von Asphalt', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 7 LA', 'Asphaltbauweisen', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 8.01 GA', 'Materialien für Betonstraßen, SpA TC 227/WG 3', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 8.1 AA', 'Technische Vertragsbedingungen', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 8.2 AA', 'Baustoffe', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 8.3 AA', 'Konstruktion', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 8.4 AA', 'Oberflächen', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 8.5 AA', 'Erhaltungstechnologie', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV 8 LA', 'Betonbauweisen', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('FGSV LA 8.0 Betonstraßen', 'LA 8.0 Betonstraßen', NULL, 'FGSV', 'Forschungsgesellschaft für Straßen- und Verkehrswesen (FGSV)', '- setup -'),
('Fhg-Allianz Bau', 'Fraunhofer-Allianz Bau', NULL, 'Fhg', 'Fraunhofer', '- setup -'),
('Fhg-Zentrum „Bautechnik“', 'Fraunhofer-Zentrum „Bautechnik“', NULL, 'Fhg', 'Fraunhofer', '- setup -'),
('fib, TG 8.9 Sichtbeton', 'fib, TG 8.9 Sichtbeton', NULL, 'SONST', 'Sonstige', '- setup -'),
('FIEC-Tec 1 „Directives, Standards and Quality Assurance“', 'FIEC-Tec 1 „Directives, Standards and Quality Assurance“', NULL, 'SONST', 'Sonstige', '- setup -'),
('FTB AA Aus- und Weiterbildung', 'Arbeitsausschuss Aus- und Weiterbildung', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)', '- setup -'),
('FTB AA Betonpumpen', 'Arbeitsausschuss Betonpumpen', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)', '- setup -'),
('FTB AA Betontechnologie und Umwelt', 'Arbeitsausschuss Betontechnologie und Umwelt', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)', '- setup -'),
('FTB AA Marketing', 'Arbeitsausschuss Marketing', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)', '- setup -'),
('FTB AA Wirtschaftspolitik', 'Arbeitsausschuss Wirtschaftspolitik', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)', '- setup -'),
('FTB AG Arbeitssicherheit', 'Arbeitsgruppe Arbeitssicherheit', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)', '- setup -'),
('FTB AG Bauprodukte und Umwelt', 'Arbeitsgruppe Bauprodukte und Umwelt', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)', '- setup -'),
('FTB AG Flüssigböden', 'Arbeitsgruppe Flüssigböden', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)', '- setup -'),
('FTB AG Regelwerk für Beton', 'Arbeitsgruppe Regelwerk für Beton', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)', '- setup -'),
('FTB Bearbeitergruppe „Drainbeton“', 'Bearbeitergruppe „Drainbeton“', 'Wasserdurchlässige Verkehrsflächen; Entsiegelung Verkehrsflächen', 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)', '- setup -'),
('FTB Forschungsbeirat', 'Forschungsbeirat', NULL, 'FTB', 'Forschungsgemeinschaft Transportbeton e.V. (FTB)', '- setup -'),
('FTB Vorstand (Stellv.)', 'Vorstand (Stellv.)', 'Weitere Gremien (Berufsgenossenschaft Rohstoffe und Chemische Industrie)', 'SONST', 'Sonstige', '- setup -'),
('GAK AK „Konstruktion“', 'FDB/DBV-Gemeinschaftsarbeitskreis „Konstruktion“', NULL, 'SONST', 'Sonstige', '- setup -'),
('GAK „Beton“', 'BTB/DBV/VDZ-Gemeinschaftsarbeitskreis „Beton“', 'Schnittstellenfragen Baustoff und Bauausführung', 'BTB / DBV / VDZ', 'BTB / DBV / VDZ', '- setup -'),
('GAK „Schnittstellenfragen“, GÜB-Beirat', 'BTB/BÜV TB/DBV/GÜB-Gemeinschaftsarbeitskreis „Schnittstellenfragen“, GÜB-Beirat', NULL, 'SONST', 'Sonstige', '- setup -'),
('HDB AAB B-StB', 'Ausbildungsbeirat Beton-Straßenbau (B-StB)', NULL, 'HDB', 'Hauptverband der deutschen Bauindustrie e.V. (HDB)', '- setup -'),
('HDB AK „ÖPP“', 'AK „ÖPP“', 'Positionierung der Zementindustrie zu verkehrspolitischen Fragestellungen mit dem Schwerpunkt ÖPP', 'HDB', 'Hauptverband der deutschen Bauindustrie e.V. (HDB)', '- setup -'),
('HDB BB B-StB-Schein', 'Bildungsbeirat B-StB-Schein', 'Lehrpläne für B-StB-Schein', 'HDB', 'Hauptverband der deutschen Bauindustrie e.V. (HDB)', '- setup -'),
('IBP AG Behaglichkeit', 'Arbeitsgruppe Raumklima und Behaglichkeit', 'Weitere Gremien (Fachinstitut für Gebäude-klima e.V. (FGK)', 'SONST', 'Sonstige', '- setup -'),
('IFB Kuratorium', 'Kuratorium', NULL, 'IFB', 'Institut für Bauforschung e.V. (IFB)', '- setup -'),
('IRB AG „Forschungsdaten“', 'Arbeitgruppe „Forschungsdaten“', NULL, 'ADW', 'Allianz der deutschen Wissenschaftsorganisation', '- setup -'),
('IWM „Umwelteigenschaften“', 'IWM „Umwelteigenschaften mineralischer Mörtel“', 'Freisetzung gefährlicher Substanzen aus Mörtel, Vorarbeiten für ein WT/WFT Dossier für Mörtel', 'IWM', 'Industrieverband WerkMörtel e.V. (IWM)', '- setup -'),
('IZB AG „Hochbau“', 'AG „Hochbau“', 'Technisches Marketing (Publikationen, Planungsatlas) zum Wohnungs- und Wirtschaftsbau', 'IZB', 'Informationszentrum Beton GmbH', '- setup -'),
('IZB AG „Technische Information“', 'AG „Technische Information“', 'Entwicklung von VDZ-Merkblättern und marktübergreifenden Publikationen "Schrifttum der Zement- und Betonindustrie)', 'IZB', 'Informationszentrum Beton GmbH', '- setup -'),
('IZB AK Hochbau', 'AK Hochbau', NULL, 'IZB', 'InformationsZentrum Beton GmbH', '- setup -'),
('IZB AK Infrastruktur', 'AK Infrastruktur', NULL, 'IZB', 'InformationsZentrum Beton GmbH', '- setup -'),
('IZB AK „Marketing“', 'AK „Marketing“', 'Entwicklung von Medien für die Zielgruppen der Betonanwendung', 'IZB', 'Informationszentrum Beton GmbH', '- setup -'),
('IZB AK Marktforschung', 'AK Marktforschung', NULL, 'IZB', 'InformationsZentrum Beton GmbH', '- setup -'),
('IZB AK Technische Informationen', 'AK Technische Informationen', NULL, 'IZB', 'InformationsZentrum Beton GmbH', '- setup -'),
('KB Redaktionsbeirat', 'Redaktionsbeirat der Zeitschrift „Straße und Autobahn“', 'Veröffentlichungen zum Betonstraßenbau', 'Kirschbaum Vlg.', 'Kirschbaum Verlag', '- setup -'),
('Kuratorium BAU Messe', 'Kuratorium BAU', NULL, 'Messe München', 'Messe München', '- setup -'),
('MIRO AG „Quarz“', 'Arbeitsgruppe „Quarz“', 'Beobachtung und aktuelle Diskussion zu Quarzfeinstaub und Arbeitssicherheit', 'MIRO', 'Bundesverband Mineralische Rohstoffe e.V. (MIRO)', '- setup -'),
('MIRO  AKR', 'Industrieller Kontaktausschuss AKR', 'Gemeinsames Forschungsprojekt „E II-Gesteinskörnungen“ zur Vermeidung einer schädigenden AKR', 'MIRO', 'Bundesverband Mineralische Rohstoffe e.V. (MIRO)', '- setup -'),
('MUNLV NRW Immissionsschutz', 'Landesbeirat Immissionsschutz', 'Immissionsschutzrechtliche Fragestellungen', 'MUNLV NRW', 'Ministerium für Klimaschutz, Umwelt, Landwirtschaft, Natur- und Verbraucherschutz NRW', '- setup -'),
('NABau 005 Normenausschuss Bauwesen', 'NABau 005 Normenausschuss Bauwesen', 'NABau Beirat und Fachbereich 07: Koordinierung NaBau und FB07 (Beton- und Stahlbetonbau)', 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-01-31 AA)', 'NA 005-01-31 Arbeitsausschuss „Nachhaltiges Bauen“', 'Spiegelausschuss CEN/TC 350', 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-02-96 AA)', 'NA 005-02-96 Arbeitsausschuss „Abdichtungssysteme auf Beton für Brücken und andere Verkehrsflächen“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-05-07 AA)', 'NA 005-05-07 Arbeitsausschuss „Baugrund, Pfähle“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-01-01 AK)', 'NA 005-07-01-01 Arbeitskreis „Befestigungsmittel“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-01-02 AK)', 'NA 005-07-01-02 Arbeitskreis „Stahlfaserbeton“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-01-03 AK)', 'NA 005-07-01-03 Arbeitskreis „Bauen im Bestand“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-01-04 AK)', 'NA 005-07-01-04 Arbeitskreis „Querkraft, Durchstanzen, Torsion“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-01-05 AK)', 'NA 005-07-01-05 Arbeitskreis „Heißbemessung“', 'Spiegelung der europäischen Brandschutznormung für Beton', 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-01-06 AK)', 'NA 005-07-01-06 Arbeitskreis „Schnittgrößen“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-01-07 AK)', 'NA 005-07-01-07 Arbeitskreis „Zeitabhängiges Materialverhalten“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-01-08 AK)', 'NA 005-07-01-08 Arbeitskreis „Ermüdung“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-01-09 AK)', 'NA 005-07-01-09 Arbeitskreis „Brücken“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-01-10 AK)', 'NA 005-07-01-10 Arbeitskreis „Verstärken und Bewehren mit FRP“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-01-11AK)', 'NA 005-07-01-11 Arbeitskreis „Dauerhaftigkeit, Lebensdauerbemessung“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-01 AA)', 'NA 005-07-01 Arbeitsausschuss „Bemessung und Konstruktion“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-02-01 AK)', 'NA 005-07-02-01 Arbeitskreis „Beton“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-02-02 AK)', 'NA 005-07-02-02 Arbeitskreis „Zugabewasser“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-02 AA)', 'NA 005-07-02 Arbeitsausschuss „Betontechnik“', 'Normung Beton (EN 206-1 / DIN 045-2) - Spiegelgremium zu CEN/TC 104', 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-05 AA)', 'NA 005-07-05 Arbeitsausschuss „Prüfverfahren für Beton“', 'Spiegelausschuss CEN/TC 104/TG8 und CEN/TC 104)', 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-06 AA)', 'NA 005-07-06 Arbeitsausschuss „Schutz, Instandsetzung und Verstärkung“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-08 AA)', 'NA 005-07-08 Arbeitsausschuss „Betonfertigteile“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-09 AA)', 'NA 005-07-09 Arbeitsausschuss „Porenbeton und haufwerksporiger Leichtbeton“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-10 AA)', 'NA 005-07-10 Arbeitsausschuss „Spritzbeton“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-11 AA)', 'NA 005-07-11 Arbeitsausschuss „Bauausführungen“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-13 AA)', 'NA 005-07-13 Arbeitsausschuss „Zement“', 'Spiegelausschuss CEN/TC 51 und ISO/TC 74', 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-15 AA)', 'NA 005-07-15 Arbeitsausschuss „Gesteinskörnungen“', 'Normung Gesteinskörnungen für Beton - Spiegelgremium zu CEN/TC 154', 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-16 AA)', 'Umweltverträglichkeit von Beton', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-17 AA)', 'NA 005-07-17 Arbeitsausschuss „Fasern für Beton“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-18 AA)', 'NA 005-07-18 Arbeitsausschuss „Tragschichtbinder“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-20 AA)', 'NA 005-07-20 Arbeitsausschuss „Betonbrücken“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-23 AA)', 'NA 005-07-23 Arbeitsausschuss „Betonzusatzmittel“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-24 AA)', 'NA 005-07-24 Arbeitsausschuss „Betonzusatzstoffe“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07-27 AA)', 'NA 005-07-27 Arbeitsausschuss „Betonangreifende Stoffe (DIN 4030)“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-07 FBR)', 'NA 005-07 Lenkungsgremium Fachbereich 07 - Beton- und Stahlbetonbau', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-08-99 AA)', 'NA 005-08-99 Arbeitsausschuss „Verbundbau“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-11-17 AA)', 'NA 005-11-17 Arbeitsausschuss „Abgasanlagen - Metall“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-11-36 AA)', 'NA 005-11-39 Arbeitsausschuss „Abgasanlagen“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-11-39 AA)', 'NA 005-11-36 Arbeitsausschuss „Abgasanlagen aus Keramik und Beton“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-11-95 AA)', 'NA 005-11-95 Arbeitsausschuss „Gärfuttersilos und Güllebehälter“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-51-01 AA)', 'NA 005-51-01 Arbeitsausschuss „Grundlagen für Entwurf, Berechnung und Bemessung von Tragwerken“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-51-02 AA)', 'NA 005-51-02 Arbeitsausschuss „Einwirkungen auf Bauten“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-51-07 AA)', 'NA 005-51-07 Arbeitsausschuss „Windenergieanlagen“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA005-51 FBR)', 'NA 005-01 Fachbereichsbeirat KOA 01 „Mechanische Festigkeit und Standsicherheit“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-52-22 AA)', 'NA 005-52-22 Arbeitsausschuss „Konstruktiver baulicher Brandschutz“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-53-01 GA)', 'NA 005-53-01 Gemeinschaftsarbeitsausschuss NABau/NAW „Boden und Grundwasser“', 'Spiegelgremium zur CEN/TC 351/WG 1 „Ground water and soil“', 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-53-02 GA)', 'NA 005-53-02 Gemeinschaftsarbeitsausschuss NABau/KRdL „Innenraumluft“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-53 FBR KOA 03)', 'NA 005-53 Fachbereichsbeirat KOA 03 „Hygiene, Gesundheit und Umweltschutz“', 'Spiegelgremium zur CEN/TC 351 „Dangerous Substances“', 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-55-71 AA)', 'NA 005-55-71 Arbeitsausschuss „Schallschutz im Hochbau“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-56-60 AA)', 'NA 005-56-60 Arbeitsausschuss „Wärmedämmstoffe“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-56-90 AA)', 'NA 005-56-90 Arbeitsausschuss „Baulicher Wärmeschutz im Hochbau“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-56-91 AA)', 'NA 005-56-91 Arbeitsausschuss „Wärmetransport“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-56-97 AA)', 'NA 005-56-97 Arbeitsausschuss „Transparente Bauteile“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-56-98 AA)', 'NA 005-56-98 Arbeitsausschuss „Wärmetechnisches Messen“ (Obmann)', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-56-99 AA)', 'NA 005-56-99 Arbeitsausschuss „Feuchte“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005-56 KOA06 GA)', 'NA 005-56 KOA06 Gemeinschaftsausschuss NABau/NHRs „Energetische Bewertung von Gebäuden“ (Obmann)', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau (NA 005 BR)', 'NA 005 Beirat des DIN-Normenausschusses Bauwesen', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NABau-STLB-Bau (LB 013)', 'Betonarbeiten', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NAB (NA 002-00-15-01 AK)', 'NA 002-00-15-01 Arbeitskreis „Auswaschung von Substanzen aus Beschichtungen“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NAB (NA 002-00-15 AA)', 'NA 002-00-15 Arbeitsausschuss „Bautenbeschichtungen“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NAGUS (NA 172-00-08 AA)', 'NA 172-00-08 Arbeitsausschuss „Management von Treibhausgasemissionen“', 'Quantifizierung, Berichterstattung und Verifizierung von Treibhausgasemissionen auf Organisationsebene', 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NAM (NA 060-13-07 AA)', 'NA 060-13-07 Arbeitsausschuss „Betontechnik“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NAM (NA 060-13-08 AA)', 'NA 060-13-08 Arbeitsausschuss „Betonpumpen“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NAM (NA 060-13-30 AA)', 'NA 060-13-30 Arbeitsausschuss „Bau- und Baustoffmaschinen“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NAM (NA 060-13-41 AA)', 'NA 060-13-41 Arbeitsausschuss „Maschinen und Ausrüstungen für Betonarbeiten“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NAW (NA 110-01-02-05 UA)', 'NA 119-01-02-05 Unterausschuss „Elutionsverfahren“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NMP 062 AA (321 AA)', 'NA 062- Arbeitsausschuss „Prüfung der Zusammensetzung von erhärtetem Beton“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NMP 062', 'Normenausschuss Materialprüfung', 'Norm zur Beschreibung von Ersatzbrennstoffen, Diskussionen zum Normenentwurf DIN EN 15359', 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NMP (NA 062-02-31 AA)', 'NA 062-02-31 Arbeitsausschuss „Schalldämmung und Schallabsorption, Messung und Bewertung“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NMP (NA 062-02-32 AA)', 'NA 062-02-31 Arbeitsausschus „Bauakustische Installationsmessungen“', NULL, 'DIN', 'Deutsches Institut für Normung e.V. (DIN)', '- setup -'),
('NRW AG 2 „Produzierendes Gewerbe“', 'AG 2 „Produzierendes Gewerbe“', 'Klimaschutz', 'NRW-Klimaschutzplan', 'NRW-Klimaschutzplan', '- setup -'),
('NRW Umweltausschuss ', 'Umweltausschuss ', 'Industriepolitische Fragen aus Bundes- und Landesebene', 'Untern. NRW', 'Unternehmer NRW', '- setup -'),
('PK „W347: Trinkwasser“', 'PK „W347: Hygienische Anforderungen an zementgebundene Werkstoffe im Trinkwasserbereich“', 'DVGW-Arbeitsblatt W 347, Spiegelung der europäischen Aktivitäten im Trinkwasserbereich', 'DVGW', 'Deutsche Gesellschaft des Gas- und Wasserfaches (DVGW)', '- setup -'),
('PRB-Lenkungsausschuss', 'PRB-Lenkungsausschuss', NULL, 'SONST', 'Sonstige', '- setup -'),
('RKW Beirat', 'RG Bau', NULL, 'RKW', 'RKW Kompetenzzentrum', '- setup -'),
('STUVA Beirat im Lenkungsgremium', 'Beirat im Lenkungsgremium', NULL, 'STUVA', 'Studiengesellschaft für Unterirdische Verkehrsanlagen e.V.', '- setup -'),
('TA des HDB', 'Technischer Ausschuss des Hauptverbandes der Deutschen Bauindustrie e.V. (vormals HATECH)', NULL, 'SONST', 'Sonstige', '- setup -'),
('Technischer Kontaktausschuss BTB/VDZ', 'Technischer Kontaktausschuss BTB/VDZ', NULL, 'SONST', 'Sonstige', '- setup -'),
('TUC Beirat Stiftungsprofessur Clausthal', 'Beirat Stiftungsprofessur Clausthal', 'Unterstützung der Forschungs- und Lehrtätigkeit am Lehrstuhl für Nichtmetallische Werkstoffe, Abteilung Bindemittel und Baustoffe', 'TUC', 'TU Clausthal', '- setup -'),
('UBA AG Sensorik', 'Ausschuss zur gesundheitlichen Bewertung von Bauprodukten', NULL, 'UBA', 'Umweltbundesamt', '- setup -'),
('UBA Unter-AK Schimmel', 'Kommission Innenraumluft-Hygiene', NULL, 'UBA', 'Umweltbundesamt', '- setup -'),
('VBG Runder Tisch „Sozialer Dialog Quarz“', 'Runder Tisch „Sozialer Dialog Quarz“', 'Quarzfeinstaub aus Sicht des Arbeitsschutzes', 'VBG', 'Berufsgenossenschaft der keramischen und Glas-Industrie', '- setup -'),
('VBT Redaktionsbeirat „beton“', 'Redaktionsbeirat „beton“', 'Veröffentlichungen zur Betontechnologie', 'VBT', 'Verlag Bau und Technik GmbH', '- setup -'),
('VDI AG „CO- und KW-Konzentrationen“', 'AG „Messen von CO- und KW-Konzentrationen“', 'allg. technische und normative Entwicklung im Bereich Umwelttechnik und Umweltmesstechnik', 'VDI / DIN ', 'VDI / DIN ', '- setup -'),
('VDI AG „SO3 (E) / NH3 (E)“', 'AG „Messung von SO3 (E) / NH3 (E)“', 'allg. technische und normative Entwicklung im Bereich Umwelttechnik und Umweltmesstechnik', 'VDI / DIN ', 'VDI / DIN ', '- setup -'),
('VDI Hochtemperaturausschuss', 'Hochtemperaturausschuss', 'Informationsaustausch mit anderen Branchen/Wissenschaft zu Forschung im Bereich Hochtemperatur-Verfahrenstechnik', 'VDI-GVC', 'Gesellschaft für Verfahrenstechnik und Chemieingenieurwesen', '- setup -'),
('VDI TG T35 Olfaktorische Bewertung', 'AG T35 „Olfaktorische Bewertung von Bauprodukten und Innenraumluft“', 'Normenausschuss, Kommission Reinhaltung der Luft (KRdL) im VDI und DIN', 'VDI', 'Verein Deutscher Ingenieure (VDI)', '- setup -'),
('VDI „Umweltmesstechnik“', 'Fachbeirat des Fachbereichs IV „Umweltmesstechnik“', 'allg. technische und normative Entwicklung im Bereich Umwelttechnik und Umweltmesstechnik', 'VDI / DIN ', 'VDI / DIN ', '- setup -'),
('VDI „Umweltschutztechnik“', 'Fachbeirat des Fachbereichs I „Umweltschutztechnik“', 'allg. technische und normative Entwicklung im Bereich Umwelttechnik und Umweltmesstechnik', 'VDI / DIN ', 'VDI / DIN ', '- setup -'),
('VDI „Zerkleinern und Klassieren“', 'Fachausschuss „Zerkleinern und Klassieren“', 'Aktuelle Forschungsthemen aus allen Bereichen der Zerkleinerungstechnik', 'VDI-GVC', 'Gesellschaft für Verfahrenstechnik und Chemieingenieurwesen', '- setup -'),
('VDZ Gesprächskreis „Qualität von Betonwaren“', 'Gesprächskreis „Qualität von Betonwaren“', 'Qualität und Dauerhaftigkeit von Betonwaren', 'VDZ-SLG', 'VDZ / SLG', '- setup -'),
('VDZ GF und MV', 'Geschäftsführerkreis Düsseldorf /  Mitgliederversammlung', 'Wahrnehmung der Mitgliedinteressen', 'AiF', 'AiF - Arbeitsgemeinschaft industrieller Forschungsvereinigungen', '- setup -'),
('VDZ Koordinierungsausschuss', 'Koordinierungsausschuss', 'Fragen der nationalen und europäischen Regelsetzung', 'VDZ-DBC', 'Deutsche Bauchemie e.V. / VDZ', '- setup -'),
('Verbandsrat', 'Verbandsrat', NULL, 'DV', 'Deutscher Verband für Wohnungswesen, Städtebau und Raumordnung e.V. (DV)', '- setup -'),
('VFBau', 'Verein zur Förderung der Normung im Bereich Bauwesen e.V.', NULL, 'SONST', 'Sonstige', '- setup -'),
('VIK AK „Energieeffizienz“', 'AK „Energieeffizienz“', 'Diskussion und Austausch Energieeffizienzpolitik', 'VIk', 'Verband der Industriellen Energie- und Kraftwirtschaft e.V. (VIK)', '- setup -'),
('VIK Ausschuss „Klima“', 'Ausschuss „Klima“', 'Branchenübergreifende Zusammenarbeit mit energieintensiven Industrien', 'VIk', 'Verband der Industriellen Energie- und Kraftwirtschaft e.V. (VIK)', '- setup -'),
('WTA R 4 „Schimmelpilzbeseitigung“', 'AG 4.12 „beseitigung von Schimmelpilzbefall in Innenräumen“', 'WTA Referat 4 „Mauerwerk / Bauwerksabdichtng“', 'WTA', '„Wissenschaftlich-Technische Arbeitsgemeinschaft für Bauwerkserhaltung und Denkmalpflege e. V. (WTA)“', '- setup -'),
('WTA R 6 „Fachinstandsetzung“', 'AG „Fachwerkinstandsetzung nach WTA-Innendämmung“', 'WTA Referat 6 „Bauphysik / Bauchemie“', 'WTA', '„Wissenschaftlich-Technische Arbeitsgemeinschaft für Bauwerkserhaltung und Denkmalpflege e. V. (WTA)“', '- setup -'),
('WTA R 6 „Hygrometrische Bemessung“', 'AG „Hygrothermische Bemessung von Holzbaukonstruktionen“', 'WTA Referat 6 „Bauphysik / Bauchemie“', 'WTA', '„Wissenschaftlich-Technische Arbeitsgemeinschaft für Bauwerkserhaltung und Denkmalpflege e. V. (WTA)“', '- setup -'),
('WTA R 6 „Innendämmung“', 'AG 6.12 „Innendämmung im Bestand“', 'Referat 6 „Bauphysik / Bauchemie“', 'WTA', '„Wissenschaftlich-Technische Arbeitsgemeinschaft für Bauwerkserhaltung und Denkmalpflege e. V. (WTA)“', '- setup -'),
('WTA R 6 „Klima“', 'AG „Klima und Klimastabilität in historischen Räumen“', 'WTA Referat 6 „Bauphysik / Bauchemie“', 'WTA', '„Wissenschaftlich-Technische Arbeitsgemeinschaft für Bauwerkserhaltung und Denkmalpflege e. V. (WTA)“', '- setup -'),
('WTA R 8 „Hydrophobierung“', 'AG „Hydrophobierende Imprägnierung von Naturstein“', 'WTA Referat 8 „Fachwerk“', 'WTA', '„Wissenschaftlich-Technische Arbeitsgemeinschaft für Bauwerkserhaltung und Denkmalpflege e. V. (WTA)“', '- setup -'),
('WTA R 8 „Schimmelpilzprognose“', 'AG „Rechnerische Prognose des Schimmelpilzwachstumsrisikos“', 'WTA Referat 8 „Fachwerk“', 'WTA', '„Wissenschaftlich-Technische Arbeitsgemeinschaft für Bauwerkserhaltung und Denkmalpflege e. V. (WTA)“', '- setup -');
SELECT COUNT(committee_id) || ' / 350 Datensätze eingefügt'
  FROM witrabau.p2_committee;
END;
