#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pybind11_mkdoc']

package_data = \
{'': ['*']}

install_requires = \
['clang']

extras_require = \
{'test': ['pytest', 'pybind11']}

entry_points = \
{'console_scripts': ['pybind11-mkdoc = pybind11_mkdoc:main']}

setup(name='pybind11_mkdoc',
      version='2.6.0',
      description='This is a package for building pybind11 docstrings from C++ header comments.',
      author='Wenzel Jakob',
      author_email='wenzel.jakob@epfl.ch',
      url='https://github.com/pybind/pybind11_mkdoc',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.5',
     )
