
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-28T00:17:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea55fb819d27467ea05f210717fc897b3a14fedd",
 "version": "0.15.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
