
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-22T16:37:02-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7cce6bffb4456d0200c8aa107f17026ca741e3f",
 "version": "v0.55"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
