
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-21T07:21:34+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ef6eefe15bb4b6cb0f61cba1d03cbfab8202e31",
 "version": "0.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
