ALL_GRANULARITIES = [
    "daily",
    "twodaily",
    "threedaily",
    "fourdaily",
    "fivedaily",
    "sixdaily",
    "weekly",
    "twoweekly",
    "threeweekly",
    "monthly",
    "twomonthly",
    "quarterly",
    "yearly",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    "weekends",
    "weekdays",
]

