# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './widgets/ui/dac.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(995, 661)
        self.verticalLayout = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_6 = QtWidgets.QWidget(Frame)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.get_button = QtWidgets.QPushButton(self.widget_6)
        self.get_button.setObjectName("get_button")
        self.horizontalLayout_26.addWidget(self.get_button)
        self.set_button = QtWidgets.QPushButton(self.widget_6)
        self.set_button.setObjectName("set_button")
        self.horizontalLayout_26.addWidget(self.set_button)
        self.verticalLayout.addWidget(self.widget_6)
        self.widget_2 = QtWidgets.QWidget(Frame)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rd_widget = QtWidgets.QWidget(self.widget_2)
        self.rd_widget.setStyleSheet("QWidget#rd_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.rd_widget.setObjectName("rd_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.rd_widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.rd_widget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(179, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.rd = QtWidgets.QDoubleSpinBox(self.rd_widget)
        self.rd.setObjectName("rd")
        self.horizontalLayout_3.addWidget(self.rd)
        self.label_2 = QtWidgets.QLabel(self.rd_widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.horizontalLayout.addWidget(self.rd_widget)
        self.dd_widget = QtWidgets.QWidget(self.widget_2)
        self.dd_widget.setStyleSheet("QWidget#dd_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.dd_widget.setObjectName("dd_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.dd_widget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.dd_widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.dd = QtWidgets.QDoubleSpinBox(self.dd_widget)
        self.dd.setObjectName("dd")
        self.horizontalLayout_4.addWidget(self.dd)
        self.label_4 = QtWidgets.QLabel(self.dd_widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.horizontalLayout.addWidget(self.dd_widget)
        self.vss_widget = QtWidgets.QWidget(self.widget_2)
        self.vss_widget.setStyleSheet("QWidget#vss_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.vss_widget.setObjectName("vss_widget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.vss_widget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.vss_widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        spacerItem2 = QtWidgets.QSpacerItem(173, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.vss = QtWidgets.QDoubleSpinBox(self.vss_widget)
        self.vss.setObjectName("vss")
        self.horizontalLayout_7.addWidget(self.vss)
        self.label_10 = QtWidgets.QLabel(self.vss_widget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.horizontalLayout.addWidget(self.vss_widget)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(Frame)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.og_widget = QtWidgets.QWidget(self.widget)
        self.og_widget.setStyleSheet("QWidget#og_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.og_widget.setObjectName("og_widget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.og_widget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(self.og_widget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        spacerItem3 = QtWidgets.QSpacerItem(178, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.og = QtWidgets.QDoubleSpinBox(self.og_widget)
        self.og.setObjectName("og")
        self.horizontalLayout_8.addWidget(self.og)
        self.label_12 = QtWidgets.QLabel(self.og_widget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.horizontalLayout_2.addWidget(self.og_widget)
        self.od_eh_widget = QtWidgets.QWidget(self.widget)
        self.od_eh_widget.setStyleSheet("QWidget#od_eh_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.od_eh_widget.setObjectName("od_eh_widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.od_eh_widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.od_eh_widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        spacerItem4 = QtWidgets.QSpacerItem(154, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.od_eh = QtWidgets.QDoubleSpinBox(self.od_eh_widget)
        self.od_eh.setObjectName("od_eh")
        self.horizontalLayout_5.addWidget(self.od_eh)
        self.label_5 = QtWidgets.QLabel(self.od_eh_widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_2.addWidget(self.od_eh_widget)
        self.od_fg_widget = QtWidgets.QWidget(self.widget)
        self.od_fg_widget.setStyleSheet("QWidget#od_fg_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.od_fg_widget.setObjectName("od_fg_widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.od_fg_widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.od_fg_widget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem5 = QtWidgets.QSpacerItem(156, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.od_fg = QtWidgets.QDoubleSpinBox(self.od_fg_widget)
        self.od_fg.setObjectName("od_fg")
        self.horizontalLayout_6.addWidget(self.od_fg)
        self.label_7 = QtWidgets.QLabel(self.od_fg_widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.horizontalLayout_2.addWidget(self.od_fg_widget)
        self.verticalLayout.addWidget(self.widget)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.widget_3 = QtWidgets.QWidget(Frame)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.rg_widget = QtWidgets.QWidget(self.widget_4)
        self.rg_widget.setStyleSheet("QWidget#rg_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.rg_widget.setObjectName("rg_widget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.rg_widget)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.widget_10 = QtWidgets.QWidget(self.rg_widget)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.widget_10)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.label_13 = QtWidgets.QLabel(self.widget_10)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.horizontalLayout_11.addWidget(self.widget_10)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem7)
        self.widget_11 = QtWidgets.QWidget(self.rg_widget)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout.setObjectName("gridLayout")
        self.label_15 = QtWidgets.QLabel(self.widget_11)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget_11)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 2, 1, 1, 1)
        self.rg_hi = QtWidgets.QDoubleSpinBox(self.widget_11)
        self.rg_hi.setObjectName("rg_hi")
        self.gridLayout.addWidget(self.rg_hi, 0, 0, 1, 1)
        self.rg_low = QtWidgets.QDoubleSpinBox(self.widget_11)
        self.rg_low.setObjectName("rg_low")
        self.gridLayout.addWidget(self.rg_low, 2, 0, 1, 1)
        self.horizontalLayout_11.addWidget(self.widget_11)
        self.horizontalLayout_9.addWidget(self.rg_widget)
        self.dg_widget = QtWidgets.QWidget(self.widget_4)
        self.dg_widget.setStyleSheet("QWidget#dg_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.dg_widget.setObjectName("dg_widget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.dg_widget)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.widget_12 = QtWidgets.QWidget(self.dg_widget)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtWidgets.QLabel(self.widget_12)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.widget_12)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.horizontalLayout_12.addWidget(self.widget_12)
        spacerItem8 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.widget_13 = QtWidgets.QWidget(self.dg_widget)
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_13)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_19 = QtWidgets.QLabel(self.widget_13)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget_13)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 2, 1, 1, 1)
        self.dg_low = QtWidgets.QDoubleSpinBox(self.widget_13)
        self.dg_low.setObjectName("dg_low")
        self.gridLayout_2.addWidget(self.dg_low, 2, 0, 1, 1)
        self.dg_hi = QtWidgets.QDoubleSpinBox(self.widget_13)
        self.dg_hi.setObjectName("dg_hi")
        self.gridLayout_2.addWidget(self.dg_hi, 0, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.widget_13)
        self.horizontalLayout_9.addWidget(self.dg_widget)
        self.r01_widget = QtWidgets.QWidget(self.widget_4)
        self.r01_widget.setStyleSheet("QWidget#r01_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.r01_widget.setObjectName("r01_widget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.r01_widget)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.widget_16 = QtWidgets.QWidget(self.r01_widget)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_23 = QtWidgets.QLabel(self.widget_16)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_5.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.widget_16)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_5.addWidget(self.label_24)
        self.horizontalLayout_13.addWidget(self.widget_16)
        spacerItem9 = QtWidgets.QSpacerItem(77, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem9)
        self.widget_15 = QtWidgets.QWidget(self.r01_widget)
        self.widget_15.setObjectName("widget_15")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_15)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_21 = QtWidgets.QLabel(self.widget_15)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget_15)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 2, 1, 1, 1)
        self.r01_hi = QtWidgets.QDoubleSpinBox(self.widget_15)
        self.r01_hi.setObjectName("r01_hi")
        self.gridLayout_3.addWidget(self.r01_hi, 0, 0, 1, 1)
        self.r01_low = QtWidgets.QDoubleSpinBox(self.widget_15)
        self.r01_low.setObjectName("r01_low")
        self.gridLayout_3.addWidget(self.r01_low, 2, 0, 1, 1)
        self.horizontalLayout_13.addWidget(self.widget_15)
        self.horizontalLayout_9.addWidget(self.r01_widget)
        self.r02_widget = QtWidgets.QWidget(self.widget_4)
        self.r02_widget.setStyleSheet("QWidget#r02_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.r02_widget.setObjectName("r02_widget")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.r02_widget)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.widget_18 = QtWidgets.QWidget(self.r02_widget)
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_25 = QtWidgets.QLabel(self.widget_18)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_6.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.widget_18)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_6.addWidget(self.label_26)
        self.horizontalLayout_14.addWidget(self.widget_18)
        spacerItem10 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem10)
        self.widget_19 = QtWidgets.QWidget(self.r02_widget)
        self.widget_19.setObjectName("widget_19")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_19)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_27 = QtWidgets.QLabel(self.widget_19)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.widget_19)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 2, 1, 1, 1)
        self.r02_hi = QtWidgets.QDoubleSpinBox(self.widget_19)
        self.r02_hi.setObjectName("r02_hi")
        self.gridLayout_4.addWidget(self.r02_hi, 0, 0, 1, 1)
        self.r02_low = QtWidgets.QDoubleSpinBox(self.widget_19)
        self.r02_low.setObjectName("r02_low")
        self.gridLayout_4.addWidget(self.r02_low, 2, 0, 1, 1)
        self.horizontalLayout_14.addWidget(self.widget_19)
        self.horizontalLayout_9.addWidget(self.r02_widget)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.r03_widget = QtWidgets.QWidget(self.widget_5)
        self.r03_widget.setStyleSheet("QWidget#r03_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.r03_widget.setObjectName("r03_widget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.r03_widget)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.widget_21 = QtWidgets.QWidget(self.r03_widget)
        self.widget_21.setObjectName("widget_21")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_21)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_31 = QtWidgets.QLabel(self.widget_21)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_7.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.widget_21)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_7.addWidget(self.label_32)
        self.horizontalLayout_15.addWidget(self.widget_21)
        spacerItem11 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem11)
        self.widget_20 = QtWidgets.QWidget(self.r03_widget)
        self.widget_20.setObjectName("widget_20")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_29 = QtWidgets.QLabel(self.widget_20)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.widget_20)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 2, 1, 1, 1)
        self.r03_hi = QtWidgets.QDoubleSpinBox(self.widget_20)
        self.r03_hi.setObjectName("r03_hi")
        self.gridLayout_5.addWidget(self.r03_hi, 0, 0, 1, 1)
        self.r03_low = QtWidgets.QDoubleSpinBox(self.widget_20)
        self.r03_low.setObjectName("r03_low")
        self.gridLayout_5.addWidget(self.r03_low, 2, 0, 1, 1)
        self.horizontalLayout_15.addWidget(self.widget_20)
        self.horizontalLayout_10.addWidget(self.r03_widget)
        self.i01_im_widget = QtWidgets.QWidget(self.widget_5)
        self.i01_im_widget.setStyleSheet("QWidget#i01_im_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.i01_im_widget.setObjectName("i01_im_widget")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.i01_im_widget)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.widget_23 = QtWidgets.QWidget(self.i01_im_widget)
        self.widget_23.setObjectName("widget_23")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_23)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_35 = QtWidgets.QLabel(self.widget_23)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_8.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.widget_23)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_8.addWidget(self.label_36)
        self.horizontalLayout_16.addWidget(self.widget_23)
        spacerItem12 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem12)
        self.widget_22 = QtWidgets.QWidget(self.i01_im_widget)
        self.widget_22.setObjectName("widget_22")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_22)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_33 = QtWidgets.QLabel(self.widget_22)
        self.label_33.setObjectName("label_33")
        self.gridLayout_6.addWidget(self.label_33, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.widget_22)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 2, 1, 1, 1)
        self.i01_im_hi = QtWidgets.QDoubleSpinBox(self.widget_22)
        self.i01_im_hi.setObjectName("i01_im_hi")
        self.gridLayout_6.addWidget(self.i01_im_hi, 0, 0, 1, 1)
        self.i01_im_low = QtWidgets.QDoubleSpinBox(self.widget_22)
        self.i01_im_low.setObjectName("i01_im_low")
        self.gridLayout_6.addWidget(self.i01_im_low, 2, 0, 1, 1)
        self.horizontalLayout_16.addWidget(self.widget_22)
        self.horizontalLayout_10.addWidget(self.i01_im_widget)
        self.i02_im_widget = QtWidgets.QWidget(self.widget_5)
        self.i02_im_widget.setStyleSheet("QWidget#i02_im_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.i02_im_widget.setObjectName("i02_im_widget")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.i02_im_widget)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.widget_26 = QtWidgets.QWidget(self.i02_im_widget)
        self.widget_26.setObjectName("widget_26")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_26)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_39 = QtWidgets.QLabel(self.widget_26)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_9.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.widget_26)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_9.addWidget(self.label_40)
        self.horizontalLayout_17.addWidget(self.widget_26)
        spacerItem13 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem13)
        self.widget_25 = QtWidgets.QWidget(self.i02_im_widget)
        self.widget_25.setObjectName("widget_25")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_25)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_37 = QtWidgets.QLabel(self.widget_25)
        self.label_37.setObjectName("label_37")
        self.gridLayout_7.addWidget(self.label_37, 0, 1, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.widget_25)
        self.label_38.setObjectName("label_38")
        self.gridLayout_7.addWidget(self.label_38, 2, 1, 1, 1)
        self.i02_im_low = QtWidgets.QDoubleSpinBox(self.widget_25)
        self.i02_im_low.setObjectName("i02_im_low")
        self.gridLayout_7.addWidget(self.i02_im_low, 2, 0, 1, 1)
        self.i02_im_hi = QtWidgets.QDoubleSpinBox(self.widget_25)
        self.i02_im_hi.setObjectName("i02_im_hi")
        self.gridLayout_7.addWidget(self.i02_im_hi, 0, 0, 1, 1)
        self.horizontalLayout_17.addWidget(self.widget_25)
        self.horizontalLayout_10.addWidget(self.i02_im_widget)
        self.i03_im_widget = QtWidgets.QWidget(self.widget_5)
        self.i03_im_widget.setStyleSheet("QWidget#i03_im_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.i03_im_widget.setObjectName("i03_im_widget")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.i03_im_widget)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.widget_28 = QtWidgets.QWidget(self.i03_im_widget)
        self.widget_28.setObjectName("widget_28")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_28)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_41 = QtWidgets.QLabel(self.widget_28)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_10.addWidget(self.label_41)
        self.label_42 = QtWidgets.QLabel(self.widget_28)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_10.addWidget(self.label_42)
        self.horizontalLayout_18.addWidget(self.widget_28)
        spacerItem14 = QtWidgets.QSpacerItem(46, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem14)
        self.widget_29 = QtWidgets.QWidget(self.i03_im_widget)
        self.widget_29.setObjectName("widget_29")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.widget_29)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_43 = QtWidgets.QLabel(self.widget_29)
        self.label_43.setObjectName("label_43")
        self.gridLayout_8.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.widget_29)
        self.label_44.setObjectName("label_44")
        self.gridLayout_8.addWidget(self.label_44, 2, 1, 1, 1)
        self.i03_im_low = QtWidgets.QDoubleSpinBox(self.widget_29)
        self.i03_im_low.setObjectName("i03_im_low")
        self.gridLayout_8.addWidget(self.i03_im_low, 2, 0, 1, 1)
        self.i03_im_hi = QtWidgets.QDoubleSpinBox(self.widget_29)
        self.i03_im_hi.setObjectName("i03_im_hi")
        self.gridLayout_8.addWidget(self.i03_im_hi, 0, 0, 1, 1)
        self.horizontalLayout_18.addWidget(self.widget_29)
        self.horizontalLayout_10.addWidget(self.i03_im_widget)
        self.verticalLayout_2.addWidget(self.widget_5)
        self.widget_30 = QtWidgets.QWidget(self.widget_3)
        self.widget_30.setObjectName("widget_30")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_30)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.i04_im_widget = QtWidgets.QWidget(self.widget_30)
        self.i04_im_widget.setStyleSheet("QWidget#i04_im_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.i04_im_widget.setObjectName("i04_im_widget")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.i04_im_widget)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.widget_32 = QtWidgets.QWidget(self.i04_im_widget)
        self.widget_32.setObjectName("widget_32")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_32)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_45 = QtWidgets.QLabel(self.widget_32)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_11.addWidget(self.label_45)
        self.label_46 = QtWidgets.QLabel(self.widget_32)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_11.addWidget(self.label_46)
        self.horizontalLayout_20.addWidget(self.widget_32)
        spacerItem15 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem15)
        self.widget_33 = QtWidgets.QWidget(self.i04_im_widget)
        self.widget_33.setObjectName("widget_33")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_33)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_47 = QtWidgets.QLabel(self.widget_33)
        self.label_47.setObjectName("label_47")
        self.gridLayout_9.addWidget(self.label_47, 0, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.widget_33)
        self.label_48.setObjectName("label_48")
        self.gridLayout_9.addWidget(self.label_48, 2, 1, 1, 1)
        self.i04_im_low = QtWidgets.QDoubleSpinBox(self.widget_33)
        self.i04_im_low.setObjectName("i04_im_low")
        self.gridLayout_9.addWidget(self.i04_im_low, 2, 0, 1, 1)
        self.i04_im_hi = QtWidgets.QDoubleSpinBox(self.widget_33)
        self.i04_im_hi.setObjectName("i04_im_hi")
        self.gridLayout_9.addWidget(self.i04_im_hi, 0, 0, 1, 1)
        self.horizontalLayout_20.addWidget(self.widget_33)
        self.horizontalLayout_19.addWidget(self.i04_im_widget)
        self.i01_st_widget = QtWidgets.QWidget(self.widget_30)
        self.i01_st_widget.setStyleSheet("QWidget#i01_st_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.i01_st_widget.setObjectName("i01_st_widget")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.i01_st_widget)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.widget_35 = QtWidgets.QWidget(self.i01_st_widget)
        self.widget_35.setObjectName("widget_35")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_35)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_49 = QtWidgets.QLabel(self.widget_35)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_12.addWidget(self.label_49)
        self.label_50 = QtWidgets.QLabel(self.widget_35)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_12.addWidget(self.label_50)
        self.horizontalLayout_21.addWidget(self.widget_35)
        spacerItem16 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem16)
        self.widget_36 = QtWidgets.QWidget(self.i01_st_widget)
        self.widget_36.setObjectName("widget_36")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.widget_36)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_52 = QtWidgets.QLabel(self.widget_36)
        self.label_52.setObjectName("label_52")
        self.gridLayout_10.addWidget(self.label_52, 2, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.widget_36)
        self.label_51.setObjectName("label_51")
        self.gridLayout_10.addWidget(self.label_51, 0, 1, 1, 1)
        self.i01_st_low = QtWidgets.QDoubleSpinBox(self.widget_36)
        self.i01_st_low.setObjectName("i01_st_low")
        self.gridLayout_10.addWidget(self.i01_st_low, 2, 0, 1, 1)
        self.i01_st_hi = QtWidgets.QDoubleSpinBox(self.widget_36)
        self.i01_st_hi.setObjectName("i01_st_hi")
        self.gridLayout_10.addWidget(self.i01_st_hi, 0, 0, 1, 1)
        self.horizontalLayout_21.addWidget(self.widget_36)
        self.horizontalLayout_19.addWidget(self.i01_st_widget)
        self.i02_st_widget = QtWidgets.QWidget(self.widget_30)
        self.i02_st_widget.setStyleSheet("QWidget#i02_st_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.i02_st_widget.setObjectName("i02_st_widget")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.i02_st_widget)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.widget_38 = QtWidgets.QWidget(self.i02_st_widget)
        self.widget_38.setObjectName("widget_38")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_38)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_53 = QtWidgets.QLabel(self.widget_38)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_13.addWidget(self.label_53)
        self.label_54 = QtWidgets.QLabel(self.widget_38)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_13.addWidget(self.label_54)
        self.horizontalLayout_22.addWidget(self.widget_38)
        spacerItem17 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem17)
        self.widget_39 = QtWidgets.QWidget(self.i02_st_widget)
        self.widget_39.setObjectName("widget_39")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget_39)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_55 = QtWidgets.QLabel(self.widget_39)
        self.label_55.setObjectName("label_55")
        self.gridLayout_11.addWidget(self.label_55, 0, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.widget_39)
        self.label_56.setObjectName("label_56")
        self.gridLayout_11.addWidget(self.label_56, 2, 1, 1, 1)
        self.i02_st_low = QtWidgets.QDoubleSpinBox(self.widget_39)
        self.i02_st_low.setObjectName("i02_st_low")
        self.gridLayout_11.addWidget(self.i02_st_low, 2, 0, 1, 1)
        self.i02_st_hi = QtWidgets.QDoubleSpinBox(self.widget_39)
        self.i02_st_hi.setObjectName("i02_st_hi")
        self.gridLayout_11.addWidget(self.i02_st_hi, 0, 0, 1, 1)
        self.horizontalLayout_22.addWidget(self.widget_39)
        self.horizontalLayout_19.addWidget(self.i02_st_widget)
        self.i03_st_widget = QtWidgets.QWidget(self.widget_30)
        self.i03_st_widget.setStyleSheet("QWidget#i03_st_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.i03_st_widget.setObjectName("i03_st_widget")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.i03_st_widget)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.widget_41 = QtWidgets.QWidget(self.i03_st_widget)
        self.widget_41.setObjectName("widget_41")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_41)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_57 = QtWidgets.QLabel(self.widget_41)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_14.addWidget(self.label_57)
        self.label_58 = QtWidgets.QLabel(self.widget_41)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_14.addWidget(self.label_58)
        self.horizontalLayout_23.addWidget(self.widget_41)
        spacerItem18 = QtWidgets.QSpacerItem(7, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem18)
        self.widget_42 = QtWidgets.QWidget(self.i03_st_widget)
        self.widget_42.setObjectName("widget_42")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget_42)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_59 = QtWidgets.QLabel(self.widget_42)
        self.label_59.setObjectName("label_59")
        self.gridLayout_12.addWidget(self.label_59, 0, 1, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.widget_42)
        self.label_60.setObjectName("label_60")
        self.gridLayout_12.addWidget(self.label_60, 2, 1, 1, 1)
        self.i03_st_low = QtWidgets.QDoubleSpinBox(self.widget_42)
        self.i03_st_low.setObjectName("i03_st_low")
        self.gridLayout_12.addWidget(self.i03_st_low, 2, 0, 1, 1)
        self.i03_st_hi = QtWidgets.QDoubleSpinBox(self.widget_42)
        self.i03_st_hi.setObjectName("i03_st_hi")
        self.gridLayout_12.addWidget(self.i03_st_hi, 0, 0, 1, 1)
        self.horizontalLayout_23.addWidget(self.widget_42)
        self.horizontalLayout_19.addWidget(self.i03_st_widget)
        self.verticalLayout_2.addWidget(self.widget_30)
        self.widget_43 = QtWidgets.QWidget(self.widget_3)
        self.widget_43.setObjectName("widget_43")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.widget_43)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.i04_st_widget = QtWidgets.QWidget(self.widget_43)
        self.i04_st_widget.setStyleSheet("QWidget#i04_st_widget {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}")
        self.i04_st_widget.setObjectName("i04_st_widget")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.i04_st_widget)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.widget_45 = QtWidgets.QWidget(self.i04_st_widget)
        self.widget_45.setObjectName("widget_45")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_45)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_61 = QtWidgets.QLabel(self.widget_45)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_15.addWidget(self.label_61)
        self.label_62 = QtWidgets.QLabel(self.widget_45)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_15.addWidget(self.label_62)
        self.horizontalLayout_25.addWidget(self.widget_45)
        spacerItem19 = QtWidgets.QSpacerItem(323, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem19)
        self.widget_46 = QtWidgets.QWidget(self.i04_st_widget)
        self.widget_46.setObjectName("widget_46")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widget_46)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_63 = QtWidgets.QLabel(self.widget_46)
        self.label_63.setObjectName("label_63")
        self.gridLayout_13.addWidget(self.label_63, 0, 1, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.widget_46)
        self.label_64.setObjectName("label_64")
        self.gridLayout_13.addWidget(self.label_64, 2, 1, 1, 1)
        self.i04_st_low = QtWidgets.QDoubleSpinBox(self.widget_46)
        self.i04_st_low.setObjectName("i04_st_low")
        self.gridLayout_13.addWidget(self.i04_st_low, 2, 0, 1, 1)
        self.i04_st_hi = QtWidgets.QDoubleSpinBox(self.widget_46)
        self.i04_st_hi.setObjectName("i04_st_hi")
        self.gridLayout_13.addWidget(self.i04_st_hi, 0, 0, 1, 1)
        self.horizontalLayout_25.addWidget(self.widget_46)
        self.horizontalLayout_24.addWidget(self.i04_st_widget)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem20)
        self.verticalLayout_2.addWidget(self.widget_43)
        self.verticalLayout.addWidget(self.widget_3)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.get_button.setText(_translate("Frame", "GET"))
        self.set_button.setText(_translate("Frame", "SET"))
        self.label.setText(_translate("Frame", "RD"))
        self.label_2.setText(_translate("Frame", "(V)"))
        self.label_3.setText(_translate("Frame", "DD"))
        self.label_4.setText(_translate("Frame", "(V)"))
        self.label_9.setText(_translate("Frame", "VSS"))
        self.label_10.setText(_translate("Frame", "(V)"))
        self.label_11.setText(_translate("Frame", "OG"))
        self.label_12.setText(_translate("Frame", "(V)"))
        self.label_6.setText(_translate("Frame", "OD_EH"))
        self.label_5.setText(_translate("Frame", "(V)"))
        self.label_8.setText(_translate("Frame", "OD_FG"))
        self.label_7.setText(_translate("Frame", "(V)"))
        self.label_14.setText(_translate("Frame", "RG_hi"))
        self.label_13.setText(_translate("Frame", "RG_low"))
        self.label_15.setText(_translate("Frame", "(V)"))
        self.label_16.setText(_translate("Frame", "(V)"))
        self.label_17.setText(_translate("Frame", "DG_hi"))
        self.label_18.setText(_translate("Frame", "DG_low"))
        self.label_19.setText(_translate("Frame", "(V)"))
        self.label_20.setText(_translate("Frame", "(V)"))
        self.label_23.setText(_translate("Frame", "R01_hi"))
        self.label_24.setText(_translate("Frame", "R01_low"))
        self.label_21.setText(_translate("Frame", "(V)"))
        self.label_22.setText(_translate("Frame", "(V)"))
        self.label_25.setText(_translate("Frame", "R02_hi"))
        self.label_26.setText(_translate("Frame", "R02_low"))
        self.label_27.setText(_translate("Frame", "(V)"))
        self.label_28.setText(_translate("Frame", "(V)"))
        self.label_31.setText(_translate("Frame", "R03_hi"))
        self.label_32.setText(_translate("Frame", "R03_low"))
        self.label_29.setText(_translate("Frame", "(V)"))
        self.label_30.setText(_translate("Frame", "(V)"))
        self.label_35.setText(_translate("Frame", "I01_IM_hi"))
        self.label_36.setText(_translate("Frame", "I01_IM_low"))
        self.label_33.setText(_translate("Frame", "(V)"))
        self.label_34.setText(_translate("Frame", "(V)"))
        self.label_39.setText(_translate("Frame", "I02_IM_hi"))
        self.label_40.setText(_translate("Frame", "I02_IM_low"))
        self.label_37.setText(_translate("Frame", "(V)"))
        self.label_38.setText(_translate("Frame", "(V)"))
        self.label_41.setText(_translate("Frame", "I03_IM_hi"))
        self.label_42.setText(_translate("Frame", "I03_IM_low"))
        self.label_43.setText(_translate("Frame", "(V)"))
        self.label_44.setText(_translate("Frame", "(V)"))
        self.label_45.setText(_translate("Frame", "I04_IM_hi"))
        self.label_46.setText(_translate("Frame", "I04_IM_low"))
        self.label_47.setText(_translate("Frame", "(V)"))
        self.label_48.setText(_translate("Frame", "(V)"))
        self.label_49.setText(_translate("Frame", "I01_ST_hi"))
        self.label_50.setText(_translate("Frame", "I01_ST_low"))
        self.label_52.setText(_translate("Frame", "(V)"))
        self.label_51.setText(_translate("Frame", "(V)"))
        self.label_53.setText(_translate("Frame", "I02_ST_hi"))
        self.label_54.setText(_translate("Frame", "I02_ST_low"))
        self.label_55.setText(_translate("Frame", "(V)"))
        self.label_56.setText(_translate("Frame", "(V)"))
        self.label_57.setText(_translate("Frame", "I03_ST_hi"))
        self.label_58.setText(_translate("Frame", "I03_ST_low"))
        self.label_59.setText(_translate("Frame", "(V)"))
        self.label_60.setText(_translate("Frame", "(V)"))
        self.label_61.setText(_translate("Frame", "I04_ST_hi"))
        self.label_62.setText(_translate("Frame", "I04_ST_low"))
        self.label_63.setText(_translate("Frame", "(V)"))
        self.label_64.setText(_translate("Frame", "(V)"))

