# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './widgets/ui/diagnostics.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.setWindowModality(QtCore.Qt.WindowModal)
        Frame.resize(1154, 575)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setObjectName("gridLayout")
        self.update = QtWidgets.QPushButton(Frame)
        self.update.setObjectName("update")
        self.gridLayout.addWidget(self.update, 2, 1, 1, 1)
        self.configured_channels_box = QtWidgets.QGroupBox(Frame)
        self.configured_channels_box.setObjectName("configured_channels_box")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.configured_channels_box)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.configured_channels = QtWidgets.QTextBrowser(self.configured_channels_box)
        self.configured_channels.setStyleSheet("QTextBrowser {\n"
"    background-color: rgb(239, 235, 231);\n"
"}")
        self.configured_channels.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.configured_channels.setFrameShadow(QtWidgets.QFrame.Plain)
        self.configured_channels.setObjectName("configured_channels")
        self.horizontalLayout_5.addWidget(self.configured_channels)
        self.gridLayout.addWidget(self.configured_channels_box, 0, 10, 1, 1)
        self.clk_timings_box = QtWidgets.QGroupBox(Frame)
        self.clk_timings_box.setObjectName("clk_timings_box")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.clk_timings_box)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.clk_timings = QtWidgets.QTextBrowser(self.clk_timings_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clk_timings.sizePolicy().hasHeightForWidth())
        self.clk_timings.setSizePolicy(sizePolicy)
        self.clk_timings.setStyleSheet("QTextBrowser {\n"
"    background-color: rgb(239, 235, 231);\n"
"}")
        self.clk_timings.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.clk_timings.setFrameShadow(QtWidgets.QFrame.Plain)
        self.clk_timings.setObjectName("clk_timings")
        self.horizontalLayout_2.addWidget(self.clk_timings)
        self.gridLayout.addWidget(self.clk_timings_box, 0, 4, 1, 1)
        self.expctrl_info_box = QtWidgets.QGroupBox(Frame)
        self.expctrl_info_box.setObjectName("expctrl_info_box")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.expctrl_info_box)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.expctrl_info = QtWidgets.QTextBrowser(self.expctrl_info_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expctrl_info.sizePolicy().hasHeightForWidth())
        self.expctrl_info.setSizePolicy(sizePolicy)
        self.expctrl_info.setStyleSheet("QTextBrowser {\n"
"    background-color: rgb(239, 235, 231);\n"
"}")
        self.expctrl_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.expctrl_info.setFrameShadow(QtWidgets.QFrame.Plain)
        self.expctrl_info.setObjectName("expctrl_info")
        self.horizontalLayout_7.addWidget(self.expctrl_info)
        self.gridLayout.addWidget(self.expctrl_info_box, 1, 4, 1, 1)
        self.vlt_enables_box = QtWidgets.QGroupBox(Frame)
        self.vlt_enables_box.setObjectName("vlt_enables_box")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.vlt_enables_box)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.vlt_enables = QtWidgets.QTextBrowser(self.vlt_enables_box)
        self.vlt_enables.setStyleSheet("QTextBrowser {\n"
"    background-color: rgb(239, 235, 231);\n"
"}")
        self.vlt_enables.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.vlt_enables.setFrameShadow(QtWidgets.QFrame.Plain)
        self.vlt_enables.setObjectName("vlt_enables")
        self.horizontalLayout_8.addWidget(self.vlt_enables)
        self.gridLayout.addWidget(self.vlt_enables_box, 1, 6, 1, 1)
        self.reg_info_box = QtWidgets.QGroupBox(Frame)
        self.reg_info_box.setObjectName("reg_info_box")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.reg_info_box)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.reg_info = QtWidgets.QTextBrowser(self.reg_info_box)
        self.reg_info.setStyleSheet("QTextBrowser {\n"
"    background-color: rgb(239, 235, 231);\n"
"}")
        self.reg_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.reg_info.setFrameShadow(QtWidgets.QFrame.Plain)
        self.reg_info.setObjectName("reg_info")
        self.horizontalLayout_3.addWidget(self.reg_info)
        self.gridLayout.addWidget(self.reg_info_box, 0, 6, 1, 1)
        self.geometry_box = QtWidgets.QGroupBox(Frame)
        self.geometry_box.setObjectName("geometry_box")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.geometry_box)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.geometry = QtWidgets.QTextBrowser(self.geometry_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geometry.sizePolicy().hasHeightForWidth())
        self.geometry.setSizePolicy(sizePolicy)
        self.geometry.setStyleSheet("QTextBrowser {\n"
"    background-color: rgb(239, 235, 231);\n"
"}")
        self.geometry.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.geometry.setFrameShadow(QtWidgets.QFrame.Plain)
        self.geometry.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.geometry.setReadOnly(True)
        self.geometry.setObjectName("geometry")
        self.horizontalLayout.addWidget(self.geometry)
        self.gridLayout.addWidget(self.geometry_box, 0, 1, 1, 1)
        self.dac_voltages_box = QtWidgets.QGroupBox(Frame)
        self.dac_voltages_box.setObjectName("dac_voltages_box")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.dac_voltages_box)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.dac_voltages = QtWidgets.QTextBrowser(self.dac_voltages_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dac_voltages.sizePolicy().hasHeightForWidth())
        self.dac_voltages.setSizePolicy(sizePolicy)
        self.dac_voltages.setStyleSheet("QTextBrowser {\n"
"    background-color: rgb(239, 235, 231);\n"
"}")
        self.dac_voltages.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.dac_voltages.setFrameShadow(QtWidgets.QFrame.Plain)
        self.dac_voltages.setObjectName("dac_voltages")
        self.horizontalLayout_6.addWidget(self.dac_voltages)
        self.gridLayout.addWidget(self.dac_voltages_box, 1, 1, 1, 1)
        self.buffers_tatus_box = QtWidgets.QGroupBox(Frame)
        self.buffers_tatus_box.setObjectName("buffers_tatus_box")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.buffers_tatus_box)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.buffers_status = QtWidgets.QTextBrowser(self.buffers_tatus_box)
        self.buffers_status.setStyleSheet("QTextBrowser {\n"
"    background-color: rgb(239, 235, 231);\n"
"}")
        self.buffers_status.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.buffers_status.setFrameShadow(QtWidgets.QFrame.Plain)
        self.buffers_status.setObjectName("buffers_status")
        self.horizontalLayout_4.addWidget(self.buffers_status)
        self.gridLayout.addWidget(self.buffers_tatus_box, 0, 8, 1, 1)
        self.irq_status_box = QtWidgets.QGroupBox(Frame)
        self.irq_status_box.setObjectName("irq_status_box")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.irq_status_box)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.irq_status = QtWidgets.QTextBrowser(self.irq_status_box)
        self.irq_status.setStyleSheet("QTextBrowser {\n"
"    background-color: rgb(239, 235, 231);\n"
"}")
        self.irq_status.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.irq_status.setFrameShadow(QtWidgets.QFrame.Plain)
        self.irq_status.setObjectName("irq_status")
        self.horizontalLayout_9.addWidget(self.irq_status)
        self.gridLayout.addWidget(self.irq_status_box, 1, 8, 1, 1)
        self.phase_timings_box = QtWidgets.QGroupBox(Frame)
        self.phase_timings_box.setObjectName("phase_timings_box")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.phase_timings_box)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.phase_timings = QtWidgets.QTextBrowser(self.phase_timings_box)
        self.phase_timings.setStyleSheet("QTextBrowser {\n"
"    background-color: rgb(239, 235, 231);\n"
"}")
        self.phase_timings.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.phase_timings.setFrameShadow(QtWidgets.QFrame.Plain)
        self.phase_timings.setObjectName("phase_timings")
        self.horizontalLayout_10.addWidget(self.phase_timings)
        self.gridLayout.addWidget(self.phase_timings_box, 1, 10, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Diagnostics"))
        self.update.setText(_translate("Frame", "UPDATE"))
        self.configured_channels_box.setTitle(_translate("Frame", "Configured Channels"))
        self.clk_timings_box.setTitle(_translate("Frame", "Clock Timings"))
        self.expctrl_info_box.setTitle(_translate("Frame", "Expose Controller Status"))
        self.vlt_enables_box.setTitle(_translate("Frame", "Voltages Enables"))
        self.reg_info_box.setTitle(_translate("Frame", "Register Information"))
        self.geometry_box.setTitle(_translate("Frame", "Geometry"))
        self.dac_voltages_box.setTitle(_translate("Frame", "DAC Voltages"))
        self.buffers_tatus_box.setTitle(_translate("Frame", "Buffers Status"))
        self.irq_status_box.setTitle(_translate("Frame", "IRQ Status"))
        self.phase_timings_box.setTitle(_translate("Frame", "Phase timings"))

