# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './widgets/ui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(328, 344)
        Frame.setMinimumSize(QtCore.QSize(300, 184))
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.gridLayout_2 = QtWidgets.QGridLayout(Frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(Frame)
        self.treeWidget.setAutoFillBackground(True)
        self.treeWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.treeWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.treeWidget.setAlternatingRowColors(False)
        self.treeWidget.setTextElideMode(QtCore.Qt.ElideLeft)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setCheckState(1, QtCore.Qt.Unchecked)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2.setCheckState(1, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(1, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.treeWidget.header().setCascadingSectionResizes(True)
        self.gridLayout_2.addWidget(self.treeWidget, 1, 0, 1, 2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.button_get = QtWidgets.QPushButton(Frame)
        self.button_get.setObjectName("button_get")
        self.gridLayout_2.addWidget(self.button_get, 2, 0, 1, 1)
        self.button_set = QtWidgets.QPushButton(Frame)
        self.button_set.setObjectName("button_set")
        self.gridLayout_2.addWidget(self.button_set, 2, 1, 1, 1)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Settings"))
        self.treeWidget.headerItem().setText(0, _translate("Frame", "Properties"))
        self.treeWidget.headerItem().setText(1, _translate("Frame", "Values"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Frame", "TIMINGS"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Frame", "hor"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("Frame", "acq"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(0, _translate("Frame", "acq_skip"))
        self.treeWidget.topLevelItem(0).child(0).child(1).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(0).child(2).setText(0, _translate("Frame", "del"))
        self.treeWidget.topLevelItem(0).child(0).child(2).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(0).child(3).setText(0, _translate("Frame", "del_skip"))
        self.treeWidget.topLevelItem(0).child(0).child(3).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(0).child(4).setText(0, _translate("Frame", "overlap"))
        self.treeWidget.topLevelItem(0).child(0).child(4).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(0).child(5).setText(0, _translate("Frame", "overlap_skip"))
        self.treeWidget.topLevelItem(0).child(0).child(5).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(0).child(6).setText(0, _translate("Frame", "postrg"))
        self.treeWidget.topLevelItem(0).child(0).child(6).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(0).child(7).setText(0, _translate("Frame", "postrg_skip"))
        self.treeWidget.topLevelItem(0).child(0).child(7).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(0).child(8).setText(0, _translate("Frame", "prerg"))
        self.treeWidget.topLevelItem(0).child(0).child(8).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(0).child(9).setText(0, _translate("Frame", "prerg_skip"))
        self.treeWidget.topLevelItem(0).child(0).child(9).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(0).child(10).setText(0, _translate("Frame", "rg"))
        self.treeWidget.topLevelItem(0).child(0).child(10).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(0).child(11).setText(0, _translate("Frame", "rg_skip"))
        self.treeWidget.topLevelItem(0).child(0).child(11).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(0).child(12).setText(0, _translate("Frame", "debug_phase"))
        self.treeWidget.topLevelItem(0).child(0).child(12).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("Frame", "vert"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(0, _translate("Frame", "tdgr"))
        self.treeWidget.topLevelItem(0).child(1).child(0).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(0, _translate("Frame", "tdrg"))
        self.treeWidget.topLevelItem(0).child(1).child(1).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(1).child(2).setText(0, _translate("Frame", "tdrt"))
        self.treeWidget.topLevelItem(0).child(1).child(2).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(1).child(3).setText(0, _translate("Frame", "tdtr"))
        self.treeWidget.topLevelItem(0).child(1).child(3).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(0).child(1).child(4).setText(0, _translate("Frame", "toi"))
        self.treeWidget.topLevelItem(0).child(1).child(4).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Frame", "GEOMETRY"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("Frame", "amplifier_overscan"))
        self.treeWidget.topLevelItem(1).child(0).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("Frame", "amplifier_prescan"))
        self.treeWidget.topLevelItem(1).child(1).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("Frame", "amplifiers_en"))
        self.treeWidget.topLevelItem(1).child(2).child(0).setText(0, _translate("Frame", "EH"))
        self.treeWidget.topLevelItem(1).child(2).child(1).setText(0, _translate("Frame", "FG"))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("Frame", "ccd_active_cols"))
        self.treeWidget.topLevelItem(1).child(3).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(1).child(4).setText(0, _translate("Frame", "image_rows"))
        self.treeWidget.topLevelItem(1).child(4).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(1).child(5).setText(0, _translate("Frame", "image_shift_en"))
        self.treeWidget.topLevelItem(1).child(6).setText(0, _translate("Frame", "store_rows"))
        self.treeWidget.topLevelItem(1).child(6).setText(1, _translate("Frame", "0"))
        self.treeWidget.topLevelItem(1).child(7).setText(0, _translate("Frame", "store_shift_en"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("Frame", "DATA MANAGER"))
        self.treeWidget.topLevelItem(2).child(0).setText(0, _translate("Frame", "adc_delay_clock"))
        self.treeWidget.topLevelItem(2).child(0).setText(1, _translate("Frame", "0"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.button_get.setText(_translate("Frame", "GET"))
        self.button_set.setText(_translate("Frame", "SET"))

