
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-28T20:44:01-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "f7bb56593988d4f65b7dc8825421cf2623b6a7ba",
 "version": "0.0.104"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
